### PR TITLE
libsasl2: depends_on "openssl@1.1"

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] ~Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.~

-----

- This was taking forever to download locally and I want to go to bed,
  so let's let CI do the work.

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like their FTP server is down.

**Comment by dawidd6** [comment]
Possible mirror: https://www.cyrusimap.org/releases/cyrus-sasl-2.1.26.tar.gz

**Comment by dawidd6** [comment]
This patch might be of interest for us: https://github.com/cyrusimap/cyrus-sasl/commit/4c8e3f24bb943386a67b4de65bb849f562499dd0

**Comment by issyl0** [comment]
This formula doesn't have [a particularly high install count](https://formulae.brew.sh/formula-linux/libsasl2).

**Comment by dawidd6** [comment]
...and only `neomutt` depends on it, which isn't even bottled (because of `emacs`).

**Pull request closed without merging**
