### PR TITLE
deno: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2020-01-11T12:31:35.9423184Z In file included from ../src/base/command_line.cc:5:0:
2020-01-11T12:31:35.9423315Z ../src/base/command_line.h:21:23: fatal error: string_view: No such file or directory
2020-01-11T12:31:35.9423455Z compilation terminated.
```

**Comment by issyl0** [comment]
Looks like it's gotten further, but is now failing at the `resource "gn"` install step:

```
FAILED: gn 
g++-7 -O3 -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-strip-all -Wl,--as-needed -static-libstdc++ -pthread -o gn -Wl,--start-group src/gn/gn_main.o base.a gn_lib.a -Wl,--end-group -ldl
/home/linuxbrew/.linuxbrew/bin/ld: src/util/worker_pool.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<WorkerPool::WorkerPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
worker_pool.cc:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10WorkerPoolC4EmEUlvE_EEEEED2Ev+0x8): undefined reference to `std::thread::_State::~_State()'
/home/linuxbrew/.linuxbrew/bin/ld: src/util/worker_pool.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<WorkerPool::WorkerPool(unsigned long)::{lambda()#1}> > >::~_State_impl()':
worker_pool.cc:(.text._ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10WorkerPoolC4EmEUlvE_EEEEED0Ev+0xc): undefined reference to `std::thread::_State::~_State()'
/home/linuxbrew/.linuxbrew/bin/ld: src/util/worker_pool.o: in function `WorkerPool::WorkerPool(unsigned long)':
worker_pool.cc:(.text._ZN10WorkerPoolC2Em+0x1ff): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
/home/linuxbrew/.linuxbrew/bin/ld: worker_pool.cc:(.text._ZN10WorkerPoolC2Em+0x2ad): undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

🤷‍♂

**Comment by iMichka** [comment]
> error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

**Comment by iMichka** [comment]
I am not working on this right now.

**Pull request closed without merging**
