### PR TITLE
augustus: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++:449:in `exec': No such file or directory - g++-9 (Errno::ENOENT)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++:449:in `<main>'
Makefile:71: recipe for target 'pp_profile.o' failed
make: *** [pp_profile.o] Error 1
Makefile:71: recipe for target 'pp_scoring.o' failed
make: *** [pp_scoring.o] Error 1
Makefile:71: recipe for target 'namgene.o' failed
make: *** [namgene.o] Error 1
Makefile:71: recipe for target 'types.o' failed
make: *** [types.o] Error 1

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/augustus.rb
```

**Comment by iMichka** [comment]
CC @sjackman, we may have a weird shim problem here with gcc9?

**Comment by sjackman** [comment]
@gaberoo fixed `augustus` for macOS in PR https://github.com/Homebrew/homebrew-core/pull/40220. Those fixes need to be disabled on Linux.
@gaberoo Would you like to open a PR to make those fixes for Linux? In particular, `depends_on "gcc"` and `with_env("HOMEBREW_CC" => "gcc-9") do` should be disabled on Linux.

**Comment by iMichka** [comment]
Superseded by #13372

**Pull request closed without merging**
