### PR TITLE
gwenhywfar: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
checking for iconv... yes
checking for GTK2... no
checking for qt4 includes... not found
checking for qt4 libraries... not found
checking for qt4 moc... not found
checking for qt4 uic... not found
configure: error: 
 Compilation of QT applications is enabled but I could not find some Qt
 components (see which are missing in messages above).
 If you don't want to compile Qt4 applications please explicitly specify
 which GUIs you want to support using "--with-guis".
 

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gwenhywfar.rb
```

**Comment by issyl0** [comment]
These changes allow this formula to install locally for me and pass `brew test`:

```diff
diff --git a/Formula/gwenhywfar.rb b/Formula/gwenhywfar.rb
index 7233a1f8b4..860270912b 100644
--- a/Formula/gwenhywfar.rb
+++ b/Formula/gwenhywfar.rb
@@ -19,12 +19,11 @@ class Gwenhywfar < Formula
   depends_on "qt" unless OS.mac?
 
   def install
+    args = %W[--disable-debug --disable-dependency-tracking --prefix=#{prefix}]
+    args << (OS.mac? ? "--with-guis=cocoa" : "--with-guis=qt5")
+
     system "autoreconf", "-fiv" if build.head?
-    system "./configure", "--disable-debug",
-                          "--disable-dependency-tracking",
-                          "--prefix=#{prefix}",
-                          *("--with-guis=cocoa" if OS.mac?)
-                          *("--with-guis=qt5" unless OS.mac?)
+    system "./configure", *args
     system "make", "install"
   end
```

**Comment by iMichka** [comment]
Rebased. The error was probably due to a broken QT. The newest version fixed most of the issues.

**Comment by issyl0** [comment]
Looks like it still needs my changes to get around the syntax error.

**Comment by iMichka** [comment]
Thanks @issyl0 !

**Pull request closed without merging**
