### PR TITLE
Fix source build of apr-util via missing dependencies

### LINKED ISSUE #4570: Cannot compile apr-util due to missing dependency
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install Apache httpd, which depends on `apr-util`

- What happened (include command output)

When trying to install `apr-util` we hit an error saying `mawk` cannot be found. `mawk` is not listed as a dependency for `apr-util`.

```
==> Installing dependencies for ensembl/cask/production-biomart: apr-util, ensembl/web/httpd22, ensembl/web/mod_perl, mawk
==> Installing ensembl/cask/production-biomart dependency: apr-util
==> Downloading https://www.apache.org/dyn/closer.cgi?path=apr/apr-util-1.6.0.tar.bz2
Already downloaded: /homes/ensw/.cache/Homebrew/apr-util-1.6.0.tar.bz2
==> ./configure --prefix=/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr-util/1.6.0_1/libexec --with-apr=/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr --with-openssl=/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl --with-crypto
==> make
Last 15 lines from /homes/ensw/.cache/Homebrew/Logs/apr-util/02.make:
sed 's,^\(location=\).*$,\1installed,' < apu-1-config > apu-config.out
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_brigade.lo -c buckets/apr_brigade.c && touch buckets/apr_brigade.lo
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets.lo -c buckets/apr_buckets.c && touch buckets/apr_buckets.lo
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets_alloc.lo -c buckets/apr_buckets_alloc.c && touch buckets/apr_buckets_alloc.lo
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets_eos.lo -c buckets/apr_buckets_eos.c && touch buckets/apr_buckets_eos.lo
/bin/bash: mawk: command not found
/bin/bash: mawk: command not found
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets_file.lo -c buckets/apr_buckets_file.c && touch buckets/apr_buckets_file.lo
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets_flush.lo -c buckets/apr_buckets_flush.c && touch buckets/apr_buckets_flush.lo
/bin/bash /nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/Cellar/apr/1.6.2_1/libexec/build-1/libtool --silent --mode=compile cc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include -I/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0/include/private  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/apr/libexec/include/apr-1  -I/nfs/software/ensembl/RHEL7-JUL2017-core2/linuxbrew/opt/openssl/include  -o buckets/apr_buckets_heap.lo -c buckets/apr_buckets_heap.c && touch buckets/apr_buckets_heap.lo
make[1]: *** [exports.c] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [export_vars.c] Error 127
make[1]: Leaving directory `/tmp/apr-util-20171004-25195-1qfq4v6/apr-util-1.6.0'
make: *** [all-recursive] Error 1
READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```
- What you expected to happen

I expect to be able to install `apr-util`. 

# Formula additions or changes

I'm not sure if this is something that needs to be solved here or needs to be pushed upstream to homebrew. I'd like to know what's the best way to proceed. For the moment I manually run a `brew install mawk` to get this to work.

If I need to raise this just let me know and I'll open another issue with homebrew

### PR DESCRIPTION
**Pull request by sambrightman**
Fixes #4570.

Change-Id: I4f6337f19aa2a64d6aa16f0fdd848f737a954e21

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [X] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

https://gist.github.com/sambrightman/d52c2342ffbb4bdd3b4a5c673fb63b60
https://gist.github.com/sambrightman/87a9f6e69429f56abf31a81570a9cd4d

-----

### CODE REVIEW

**Comment by sambrightman** [comment]
I can't really tell from the CircleCI output if something is legitimately broken here.

**Comment by iMichka** [comment]
`revision OS.mac? ? 1 : 2` needs to be changed to `revision OS.mac? ? 1 : 3`

The `sha256 "f537b7832456438ce06b595199d1bf3f38a0b8800b9469db56b0b084ac1b1ac7" => :x86_64_linux` line needs to be deleted.

This will allow a new bottle to be built.

There are some unrelated build/test failures too, we can ignore these for the time being.

**Comment by sambrightman** [comment]
Is that now correct?

**Comment by iMichka** [comment]
Almost. You removed the sha256 line from the source file. You should remove the sha256 from the bottle block (`sha256 "f537b7832456438ce06b595199d1bf3f38a0b8800b9469db56b0b084ac1b1ac7" => :x86_64_linux`).

**Comment by sambrightman** [comment]
Half asleep. Fixed.

**Comment by iMichka** [comment]
Thanks @sambrightman !

**Pull request closed without merging**
