### PR TITLE
wal2json: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Error: 1 problem in 1 formula detected
wal2json:
  * 'revision 1' should be removed
==> FAILED
```

**Comment by issyl0** [comment]
```
Error: 1 problem in 1 formula detected
wal2json:
  * revision should not decrease (from 1 to 0)
==> FAILED
```

What does it want from me?!

**Comment by dawidd6** [comment]
Heh, I see the `revision 1` line is present upstream. Dunno why it complains in both situations. Just pull it as is.

**Comment by issyl0** [comment]
Done. I only applied the bottle changes from here and not the "remove revision 1" as that's just confusing.

**Pull request closed without merging**
