### PR TITLE
Add cellar :any

### PR DESCRIPTION
**Pull request by sjackman**
Add cellar `:any` or `cellar :any_skip_relocation`.
Rust is `cellar :any` on macOS, so it should also be `cellar :any` on Linux.

See https://github.com/Homebrew/linuxbrew-core/pull/21804#issuecomment-750435924

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

### CODE REVIEW

**Comment by iMichka** [comment]
Just to be clear: as long as this is not automated and done by our tooling, it will be removed on the next revision bump. And it will also not be backported to homebrew-core. Or did something change that makes all of these cellar any now?

**Comment by sjackman** [comment]
> I'm getting cellar :any_skip_relocation when I build a bottle locally. Is there a reason why that's not currently in the formula? Do we just need a new bottle request?

https://github.com/Homebrew/linuxbrew-core/pull/21804#issuecomment-749845102

If the bottle is `cellar :any` on both macOS and Linux, it's not clear why or how it was removed from Linuxbrew/core.

One hypothesis I haven't yet tested, since Linuxbrew/core only ever builds with `brew bottle --keep-old`, perhaps that can remove `cellar :any`, but never add it in, and if that's true, then there's a ratchet that over time has a tendency to remove `cellar :any` and keep it that way. I'm thinking Linuxbrew-core should just use whatever macOS has determined it to be.

**Comment by sjackman** [comment]
I've tested my hypothesis, and that does indeed seem to be what's happening. I manually removed `cellar :any` and Linux bottle from `hello`, then ran
```bash
brew install hello
brew bottle --keep-old --json hello
brew bottle --keep-old --merge --write hello--2.10.x86_64_linux.bottle.json
```
and the `cellar :any` is still missing afterward, which is what I'd expect. The point is though, if there's no process to add it back in, then it'll be missing forever.

**Comment by danielnachun** [comment]
I think the best case scenario would be for us to be able to carry over `cellar :any` from homebrew-core *and* preserve it if we added it here.  Will the platform-specific cellars @iMichka is working on (https://github.com/Homebrew/brew/issues/9315) help with this?  That would let us handle issues of bottle relocation separately on each platform, and ideally once a bottle is marked `cellar :any` or `cellar :any_skip_relocation` on a platform, it would stay that way unless we explicitly remove it.

**Comment by sjackman** [comment]
> That would let us handle issues of bottle relocation separately on each platform, and ideally once a bottle is marked cellar :any or cellar :any_skip_relocation on a platform, it would stay that way unless we explicitly remove it.

`cellar :any` is added automatically by `brew bottle`. It's not meant to be added manually. This PR is an exception, because `cellar :any` has been removed unintentionally, which isn't supposed to happen.

>  This will also get a lot easier when we merge linuxbrew-core into homebrew-core.

That should fix this problem, which results from using `brew bottle --keep-old`.

**Comment by sjackman** [comment]
Merged!

**Comment by iMichka** [comment]
I think this was merged too fast. Look at protobuf for example: https://github.com/Homebrew/linuxbrew-core/pull/21726

I had to remove the cellar line. Else brew refuses to finish the build as it told me it didn't wan't the cellar :any line.

There are other formulae in the list that I manually fixed over the months. Everything is now reset to default; and I will to remove all these lines manually at each rebuild ...

**Comment by iMichka** [comment]
On the other hand I just rebuilt a bottle for panqo and it worked. Weird.

**Comment by iMichka** [comment]
The last numpy revision bump failed with:
```
Error: --keep-old was passed but there are changes in:
cellar: old: :any, new: "/home/linuxbrew/.linuxbrew/Cellar"
```

Looks like mixed results :)

**Comment by sjackman** [comment]
> I think this was merged too fast. Look at protobuf for example: #21726
> I had to remove the cellar line. Else brew refuses to finish the build as it told me it didn't wan't the cellar :any line.

Ideally this issue would be resolved in Homebrew/brew. The quickest fix would be for `brew bottle --keep-old` to use the `cellar` previous cellar line, whatever it is, and ignore the new cellar line. This change could be limited to Linux.

**Comment by sjackman** [comment]
The non-relocatable status on Linux is likely a false positive for most bottles. The root cause fix would be to identify and fix the false positive in `brew bottle`, but that's a bigger project, though worthwhile.

**Pull request merged**
