### PR TITLE
onedrive: update to v2.4.12

### PR DESCRIPTION
**Pull request by jnooree**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Please delete the ` x86_64_linux: ` line.

**Comment by jnooree** [comment]
@iMichka Removed the bottle line!

**Comment by iMichka** [comment]
Just  FYI we are shutting down this repo and moving everything to homebrew-core as a replacement. Would you be interested to open a pull request to add onedrive as a new formula in https://github.com/Homebrew/homebrew-core ?

**Comment by jnooree** [comment]
@iMichka I can make one. Is it okay to just copy and paste the existing `onedrive` formula here?

**Comment by dawidd6** [comment]
For starter, yes. Just delete the bottle block and we'll iterate from there.

**Comment by jnooree** [comment]
Created Homebrew/homebrew-core#81048.

**Pull request merged**
