### PR TITLE
dieharder: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
Making install in libdieharder
make[1]: Entering directory '/tmp/dieharder-20190904-28060-buabnm/dieharder-3.31.1/libdieharder'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc-5 -DHAVE_CONFIG_H -I. -I..  -DVERSION=3.31.1 -DLITTLE_ENDIAN=1 -I ../include -I /home/linuxbrew/.linuxbrew/Cellar/dieharder/3.31.1_3/include  -std=c99 -Wall -pedantic -g -O2 -MT libdieharder_la-bits.lo -MD -MP -MF .deps/libdieharder_la-bits.Tpo -c -o libdieharder_la-bits.lo `test -f 'bits.c' || echo './'`bits.c
/bin/bash ../libtool  --tag=CC   --mode=compile gcc-5 -DHAVE_CONFIG_H -I. -I..  -DVERSION=3.31.1 -DLITTLE_ENDIAN=1 -I ../include -I /home/linuxbrew/.linuxbrew/Cellar/dieharder/3.31.1_3/include  -std=c99 -Wall -pedantic -g -O2 -MT libdieharder_la-chisq.lo -MD -MP -MF .deps/libdieharder_la-chisq.Tpo -c -o libdieharder_la-chisq.lo `test -f 'chisq.c' || echo './'`chisq.c
libtool: compile:  gcc-5 -DHAVE_CONFIG_H -I. -I.. -DVERSION=3.31.1 -DLITTLE_ENDIAN=1 -I ../include -I /home/linuxbrew/.linuxbrew/Cellar/dieharder/3.31.1_3/include -std=c99 -Wall -pedantic -g -O2 -MT libdieharder_la-bits.lo -MD -MP -MF .deps/libdieharder_la-bits.Tpo -c bits.c -o libdieharder_la-bits.o
libtool: compile:  gcc-5 -DHAVE_CONFIG_H -I. -I.. -DVERSION=3.31.1 -DLITTLE_ENDIAN=1 -I ../include -I /home/linuxbrew/.linuxbrew/Cellar/dieharder/3.31.1_3/include -std=c99 -Wall -pedantic -g -O2 -MT libdieharder_la-chisq.lo -MD -MP -MF .deps/libdieharder_la-chisq.Tpo -c chisq.c -o libdieharder_la-chisq.o
In file included from ../include/dieharder/libdieharder.h:22:0,
                 from bits.c:7:
/usr/include/unistd.h:1046:20: error: unknown type name ‘intptr_t’
 extern void *sbrk (intptr_t __delta) __THROW;
                    ^
In file included from ../include/dieharder/libdieharder.h:22:0,
                 from chisq.c:18:
/usr/include/unistd.h:1046:20: error: unknown type name ‘intptr_t’
 extern void *sbrk (intptr_t __delta) __THROW;
                    ^
Makefile:573: recipe for target 'libdieharder_la-chisq.lo' failed
make[1]: *** [libdieharder_la-chisq.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:566: recipe for target 'libdieharder_la-bits.lo' failed
make[1]: *** [libdieharder_la-bits.lo] Error 1
make[1]: Leaving directory '/tmp/dieharder-20190904-28060-buabnm/dieharder-3.31.1/libdieharder'
Makefile:412: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by dawidd6** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808486

**Comment by iMichka** [comment]
Interesting. Do you know if there is a specific reason why this patch has not been upstreamed?

**Comment by dawidd6** [comment]
Maybe the original author is not active anymore, dunno really.

AUR has this patch too: https://aur.archlinux.org/cgit/aur.git/tree/stdint.patch?h=dieharder

**Comment by iMichka** [comment]
Let's go with that patch. I need to make a compromise between a quick fix and running after each package maintainer to get things upstreamed :)

**Comment by dawidd6** [comment]
You may need to tweak the patch' header, namely the file paths.

**Comment by iMichka** [comment]
Thanks for the hints @dawidd6 ! Fixed

**Pull request closed without merging**
