### PR TITLE
rust: patch stage0 on Linux when brewed glibc is installed

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

This PR should fix a long standing issue where rust does not build with brewed `glibc`.  A [PR](https://github.com/Homebrew/linuxbrew-core/pull/2087) from a while ago had the right idea, but didn't quite figure everything out.  However, it gave me enough to go on that I got it to work.  This was a pretty complicated modification but I made sure that the build process for macOS and Linux without brewed `glibc` remains unaltered.

### CODE REVIEW

**Comment by iMichka** [comment]
I would like to gather some thoughts from @jonchang , @sjackman or @dawidd6 first.

I am worried that we start adding more and more code that depends on brewed glibc. The question is how do we want to migrate this to homebrew-core.

The main issue is that this code is not tested by CI: it means that it can break at any moment. I think it is also unlikely that we will not be able to backport this to homebrew-core.
Even if we find a better solution for this specific case, remains the changes we have for all the gcc, ghc and llvm formulae.

If we get rid of them, this means dropping support for all glibc versions below the one provided by ubuntu 16.04. This also means that as soon as we migrate to ubuntu 18.04 next year, we will raise the bar even more.

I was always in favour of dropping support for pre-ubuntu 16.04 glibc, and would like to see a fork of linuxbrew-core happen for old systems, but not maintained by me or the homebrew-core maintainers.

Thoughts?

**Comment by danielnachun** [comment]
My own thoughts on this are that at the moment, CentOS 7 is still widely used by many HPC clusters (including the clusters I use), and Linuxbrew is the only solution I've found that allows me to set up an up to date user space without sudo access.  

I believe that many cluster admins are exceedingly conservative about updating distributions (and personally I would prefer they use Ubuntu Server instead of CentOS, which adds a lot unneeded cruft) and this creates a huge headache for users.  But in most cases we as users have no control over this.  Cloud VMs aren't an option either until the cost/TB of high performance virtual NFS drops massively. 

I've wondered if it would be possible to create a special CI that would only be run for formula which depend on brewed `glibc`, similar to how we currently have the ability in homebrew-core to test formula on Linux by adding them to `.github/workflows/test-linux.yaml`.  CentOS 7 would be a logical choice for the CI image, as that's almost certainly the oldest Linux distro in widespread HPC use right now.  I'd be interested in trying to help with this if we see this an option.

It's also worth noting that all `gcc` and `llvm` formulae should have `cellar :any` (some `gcc` formulae currently don't, and this should be fixed), and I'm fairly sure the same is true for `ghc` and `rust` as well.  While `gcc` and `llvm` are a bit of special case, the reason `ghc` and `rust` need modifications is because they use both a prebuilt binary and brewed `gcc`/`llvm` in the build process.  This is not a very common practice and I don't know that we're going to have too many more occurrences.

Lastly, I should mention that I have been researching how we might be able to use the trick Anaconda does to make all our bottles relocatable (at least on Linux).  The TLDR summary is they build their binaries with a very long placeholder prefix, and then when installing them to their final location, replace that long prefix with what should always be the much shorter real prefix, using null padding to keep the binary the same size.  In theory that would allow us bottle everything in CI including `glibc` and use bottles in any cellar prefix.  I was going to make a post about this in Homebrew Discussions next month, but perhaps I should do so sooner if there is interest.  

Sorry for such a long post, I've just been thinking about this a lot lately as well.  I know that the homebrew maintainers have a lot on their plates and I want to make sure any suggestions I have make that better!

**Comment by sjackman** [comment]
For reference

### Not supported
Ubuntu 10 glibc 2.11
CentOS 6 glibc 2.12

### Requires brewed glibc
Debian 7 glibc 2.13
Ubuntu 12 glibc 2.15
CentOS 7 glibc 2.17
Debian 8 glibc 2.19
Ubuntu 14 glibc 2.19

### Host's glibc is new enough
Ubuntu 16 glibc 2.23
Debian 9 glibc 2.24
Ubuntu 18 glibc 2.27
CentOS 8 glibc 2.28
Debian 10 glibc 2.28
Ubuntu 20 glibc 2.31

**Comment by iMichka** [comment]
Exact. And if we add brewed glibc specific code to homebrew-core, this means we need to add `Debian 7 glibc 2.13` CI there, and build bottles. Then it does not make sense anymore to build on ubuntu 16.04.

Another strategy would be to migrate to homebrew-core without the brewed glibc support; and bottle with ubuntu 16.04 only (and with 18.04 next year). Anyone can pick linuxbrew-core up (not me) and do the daily merging to keep old linux versions alive.

I am also willing to let 16.04 live a little bit longer if that helps. But I would like to get rid of the mismatch between what we support with bottles, and what we support "on a best effort basis".

**Comment by sjackman** [comment]
> It's also worth noting that all gcc and llvm formulae should have cellar :any (some gcc formulae currently don't, and this should be fixed), and I'm fairly sure the same is true for ghc and rust as well.

I would focus your efforts here. Building from source on the user's machine is fraught with all sorts and sources of peril. `cellar :any` bottles are a much better user experience than building from source, and also easier on us maintainers. If the bottle ought to be `cellar :any`, but it's not being correctly detected as `cellar :any`, there's room for improvement in Homebrew. The relevant function is `keg_contain?`. This function is inherently heuristic in nature, so little hacks and tweaks to improve it are welcome.

https://github.com/Homebrew/brew/blob/53ef74f67415949f0a9e6377af22b967336c1011/Library/Homebrew/dev-cmd/bottle.rb#L113

**Comment by sjackman** [comment]
```console
$ readelf -V rustc-1.46.0-x86_64-unknown-linux-gnu/rustc/bin/{rustc,rustdoc} | grep -o 'GLIBC_[0-9.]*' | sort -uV | tail -n1
GLIBC_2.3.4
$ readelf -V rust-std-1.46.0-x86_64-unknown-linux-gnu/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/*.so | grep -o 'GLIBC_[0-9.]*' | sort -uV | tail -n1
GLIBC_2.4
```
It looks like these precompiled bootstrap binaries should work with `glibc` 2.4 or newer. What's the error when using them on a host with an older version of `glibc`?

**Comment by maxim-belkin** [comment]
> and Linuxbrew is the only solution I've found that allows me to set up an up to date user space without sudo access.

Have a look at [Spack](https://github.com/spack/spack/) -- it's designed for HPC clusters and can be used without root privileges. I too was (am?) trying to make Linuxbrew work for a Linux-based HPC system but the problem is that even if you figure out how to fix a problem -- it's highly unlikely that your patch will be accepted because Homebrew's target OS is Mac and this dictates a lot of things... including things like (not) supporting certain OSes. An HPC cluster and an Apple Macbook can't operate on the same timescale... nor do they have the same goals, so it makes sense to use the appropriate solution.

**Comment by danielnachun** [comment]
This is the error:

```
error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/rust-20201222-9659-fl861t/rustc-1.48.0-src/build/bootstrap/debug/deps/libproc_macro_error_attr-efb8effa561c9e33.so)
   --> /home/dnachun/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
```

The problem is that during the build process it also uses `gcc` for some parts and this leads to a conflict where the same binary is trying to link to system and brewed `glibc`: https://github.com/rust-lang/rust/issues/58394.

There was a previous attempt to fix this which I built off of: https://github.com/Homebrew/linuxbrew-core/pull/2087

I am checking right now to see if it will build as a relocatable bottle, as this would make this a lot easier.

**Comment by danielnachun** [comment]
> > and Linuxbrew is the only solution I've found that allows me to set up an up to date user space without sudo access.
> 
> Have a look at [Spack](https://github.com/spack/spack/) -- it's designed for HPC clusters and can be used without root privileges. I too was (am?) trying to make Linuxbrew work for a Linux-based HPC system but the problem is that even if you figure out how to fix a problem -- it's highly unlikely that your patch will be accepted because Homebrew's target OS is Mac and this dictates a lot of things... including things like (not) supporting certain OSes. An HPC cluster and an Apple Macbook can't operate on the same timescale... nor do they have the same goals, so it makes sense to use the appropriate solution.

Good point, I did try `spack` initially but went down the Linuxbrew route because it worked better 'out of the box'.  If the maintenance burden for Homebrew to support older HPC environments becomes too great (which I totally understand), I'd probably have to try harder to get `spack` to work instead.

**Comment by danielnachun** [comment]
I'm getting `cellar :any_skip_relocation` when I build a bottle locally.  Is there a reason why that's not currently in the formula?  Do we just need a new bottle request?

**Comment by sjackman** [comment]
> I'm getting cellar :any_skip_relocation when I build a bottle locally. Is there a reason why that's not currently in the formula? Do we just need a new bottle request?

**Comment by sjackman** [comment]
> I'm getting cellar `:any_skip_relocation` when I build a bottle locally. Is there a reason why that's not currently in the formula? Do we just need a new bottle request?

https://github.com/Homebrew/homebrew-core/blob/6f769e206794ee2e4b29b85dd9d61ee8c0251359/Formula/rust.rb#L18

Rust is `cellar :any` on macOS, so it should also be `cellar :any` on Linux.
@iMichka Thoughts on how `cellar :any` was removed?

I've opened PR https://github.com/Homebrew/linuxbrew-core/pull/21928 to add `cellar :any` to Rust.

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/linuxbrew-core/pull/21928 is superseded by PR https://github.com/Homebrew/linuxbrew-core/pull/21929, which adds `cellar :any` or `cellar :any_skip_relocation` to 92 formulae.

**Comment by sjackman** [comment]
https://github.com/rust-lang/rust/issues/58394

So it sounds like the root cause is a regression in Rust between version 1.31 and 1.32. It may be worth exploring the workaround of setting `~/.cargo/config` to either…

```toml
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/cc"
```
or perhaps
```toml
[target.x86_64-unknown-linux-gnu]
linker = "~/.linuxbrew/bin/cc"
```

**Comment by danielnachun** [comment]
> > I'm getting cellar `:any_skip_relocation` when I build a bottle locally. Is there a reason why that's not currently in the formula? Do we just need a new bottle request?
> 
> https://github.com/Homebrew/homebrew-core/blob/6f769e206794ee2e4b29b85dd9d61ee8c0251359/Formula/rust.rb#L18
> 
> Rust is `cellar :any` on macOS, so it should also be `cellar :any` on Linux.
> @iMichka Thoughts on how `cellar :any` was removed?
> 
> I've opened PR #21928 to add `cellar :any` to Rust.

I'm going to close this PR because adding `cellar :any` is a much simpler solution to this problem.  Regardless of how we ultimately decide to handle supporting older `glibc`, I 100% agree with @iMichka that we need to avoid adding code to this repo that depends on brewed `glibc` because our current CI setup can't test it.  

On a related note, after more checking I can see that `cellar :any` is missing for some versions of `gcc` and `ghc` but not all, making me think it was removed by accident (possibly because neither formula is `cellar :any` on macOS, though that may be reexamined as well).  I am going to make PRs to add this back (they're not part of the PR from @sjackman) and also remove the code that depends on brewed `glibc`.  I can also see that all versions of `llvm` already have `cellar :any`, so I can make a PR to remove the code that depends on brewed `glibc` there too.  

Ironically the main outcome of this PR seems to be that all of the formulae which currently have code relying on brewed `glibc` don't need it because no Linux users should need to build them from source.  I have a feeling that the same conditions that lead to formula needing modifications to work with brewed `glibc` make them very likely to be relocatable.  Although we may eventually encounter a formula which is non-relocatable and needs modifications to work with brewed `glibc`, for now that appears not to be the case, and it seems we won't need to do anything special to maintain support for older `glibc` as we merge with homebrew-core and update to Ubuntu 18.04.

**Comment by sjackman** [comment]
```
error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/rust-20201222-9659-fl861t/rustc-1.48.0-src/build/bootstrap/debug/deps/libproc_macro_error_attr-efb8effa561c9e33.so)
   --> /home/dnachun/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
```
This error occurs when the brewed `~/.linuxbrew/lib/libc.so.6` is used, which is correct, and the host's dynamic linker `/lib64/ld-linux-x86-64.so.2` is used rather than the brewed `~/.linuxbrew/lib/ld.so`, which is bad.

**Comment by danielnachun** [comment]
Yes it was pointed out in some conversations I found about this issue that `rust` should really not be doing that, and it's apparently not readily configurable by the user: https://github.com/rust-lang/rust/issues/58394.  I've encountered the same issue with `ghc` and `gcc` as well.  One "hack" to get around this is to unlink `glibc` while building those, but that shouldn't be necessary.  Instead they should be consistent about either ignoring the brewed `glibc` altogether, or using both the brewed `libc.so.6` and the brewed dynamic linker.  

These issues should be fixed upstream but since all the affected software can be built as relocatable bottles, we can fix it for our users right now without having to wait for that.

**Comment by danielnachun** [comment]
To follow up on my comment above, I check the `glibc` references in `gcc` and `llvm` and they are not actually in the build block, just to pull it in as a dependency and for `gcc` to make some symlinks post-install.  Because they build process itself isn't affected in those formulae, I left the `glibc` code alone.  I've submitted a PR to add back `cellar :any` to the `gcc` versions which need but that's it for now.

**Pull request closed without merging**
