### PR TITLE
petsc: fix build for Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
There is a need to replace `"#{HOMEBREW_SHIMS_PATH}/linux/super/` on linux though. The shims are sort of fake compiler scripts in homebrew that inject flags and logs build steps, and sometimes libraries keep the full paths to these shims, which we do not want.

Can you open a PR at https://github.com/Homebrew/homebrew-core with a on_macos / on_linux block, one for each platform?

**Comment by danielnachun** [comment]
This still fails even if I try to replace `"#{HOMEBREW_SHIMS_PATH}/linux/super/`.  I checked the file that is supposed to contain the shim references and there don't appear to be any on Linux.  So maybe we don't need to do this replacement?  Either way I'll move this over homebrew-core once I know what we are supposed to do.

**Comment by iMichka** [comment]
Sometimes the shims fix only needs to be done on Mac or on Linux, and sometimes on both.

**Comment by danielnachun** [comment]
Is there a way I can set up the shim fix so that it won't cause an error if no strings with shim paths are found?  I can see now in the checks that in CI there are still shim references, but on my local machine there are not.  Ideally the formula should try to remove the shim references but fail gracefully if no shim references are found.

**Comment by iMichka** [comment]
We do something like this in perl.rb, using File.readlines and grep.

**Pull request closed without merging**
