### PR TITLE
rtags 2.22

### PR DESCRIPTION
**Pull request by root42**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Hi. Version updates need to be done in https://github.com/Homebrew/homebrew-core first. The change will be merged to the linux repo later on.

**Comment by root42** [comment]
And how do I do that? I simply used the "brew bump-formula-pr" command, which doesn't ask me if I want to do linuxbrew or homebrew.

**Comment by iMichka** [comment]
You were lucky the command worked out of the box on Linux. It is rarely used for linuxbrew-core.

@sjackman should we disable `brew bump-formula-pr` on Linux?

@root42 either you run `brew bump-formula-pr` on a mac. Or just clone the mac repo, fork it, and open a pull request manually with the change.

**Comment by root42** [comment]
Well, ok. I think I can do it on my Mac. Or I‘ll manually merge the change into the homebrew repo. Thanks.

**Comment by sjackman** [comment]
Thanks for your first contribution to Linuxbrew/core, @root42, even though we weren't able to merge it this time around.

> @sjackman should we disable brew bump-formula-pr on Linux?

Yes, `brew bump-formula-pr` should display a helpful error message when used with `Homebrew/linuxbrew-core`.

@root42 Would you be interested in opening a PR to disable `brew bump-formula-pr` for Homebrew/linuxbrew-core? Here's the relevant code:
https://github.com/Homebrew/brew/blob/a00570be77da7b5a32208d645013a8bb353af941/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L69

If someone wanted to go the extra mile, it could check the current version in `Homebrew/homebrew-core` and either
1. Run `brew bump-formula-pr` if it's out of date in Homebrew-core
2. Give a helpful error message indicating that it'll be updated in Linuxbrew-core with the next merge if it's up-to-date in Homebrew-core

**Pull request closed without merging**
