### PR TITLE
fwknop: add Linux dep

### PR DESCRIPTION
**Pull request by jonchang**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
checking for firewall-cmd... no
checking for firewalld... no
checking for iptables... no
checking for ipfw... no
checking for pfctl... no
checking for ipf... no
configure: error: No firewall program was found or specified.
```

**Comment by iMichka** [comment]
Can we try `--without-firewall` ?

**Comment by cocolin041** [comment]
Hello from HackIllinois!

On `fwknop` website (http://www.cipherdyne.org/fwknop/) they say that `fwknop` needs:
- `ipfw` on Mac
- `firewalld` on Linux

There is no `--without-firewall` (or `--disable-firewall`) configure flag, so this is not an option.

This means that we need to add a new formula for `firewalld` in order to build `fwknop`.
If building `firewalld` for Linuxbrew/core is an option, I'd be happy to look into it.

Thanks!

**Comment by dawidd6** [comment]
@cocolin041 go for it!

**Comment by jonchang** [comment]
yes, adding `firewalld` or `ipfw` would be much appreciated.

**Pull request closed without merging**
