### PR TITLE
watchman: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-09-15T09:16:24.0898947Z ==> brew style watchman
2019-09-15T09:16:27.5400782Z == /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/watchman.rb ==
2019-09-15T09:16:27.5408313Z C: 67:  5: Style/MultilineIfModifier: Favor a normal if-statement over a modifier clause in a multiline statement.
2019-09-15T09:16:27.5409066Z 
2019-09-15T09:16:27.5409504Z 1 file inspected, 1 offense detected
2019-09-15T09:16:27.5409993Z ==> FAILED
```

**Comment by issyl0** [comment]
Thanks! The only manual step I had to do when merging this one was to remove the `# Build a bottle for Linuxbrew` comment.

**Comment by dawidd6** [comment]
Hmm. So when one force pushes changes, one has to delete this automated comment or what?

**Comment by issyl0** [comment]
Yes, please. We've got a script that squashes commits that just contain that line, but with force-pushes or extra commits to fix issues, we can't use it because we want to keep the changes. If we don't remove that line, the [the codebase gets littered with these comments](https://github.com/Homebrew/linuxbrew-core/pull/14766) and we have go back afterwards.

**Comment by dawidd6** [comment]
Okay then, will try to remember that next time. Though it would be nice to document it somewhere or maybe it is already?

**Comment by issyl0** [comment]
Good idea. I just amended [the ongoing docs PR in Homebrew/brew](https://github.com/Homebrew/brew/pull/6459/files#r324465631).

**Pull request closed without merging**
