### PR TITLE
volatility: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
setup.py:
  expected replacement of "ZLIB_ROOT = None" with "ZLIB_ROOT = ('/usr/lib', '/usr/include')"
```

**Comment by issyl0** [comment]
I don't understand how this ever worked, because the `inreplace` is trying to overwrite the same text twice:

```ruby
s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{zlib_prefix}/lib', '#{zlib_prefix}/include')"
s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{sdkprefix}/usr/lib', '#{sdkprefix}/usr/include')"
```

Unless something strange happened in the merge? The [macOS formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/volatility.rb#L154) only has one line.

**Comment by issyl0** [comment]
```diff
diff --git a/Formula/volatility.rb b/Formula/volatility.rb
index a0397d8507..5033376a18 100644
--- a/Formula/volatility.rb
+++ b/Formula/volatility.rb
@@ -152,13 +152,15 @@ class Volatility < Formula
       inreplace "setup.py" do |s|
         if OS.mac?
           sdkprefix = MacOS.sdk_path_if_needed ? MacOS.sdk_path : ""
-          zlib_prefix = sdkprefix/"usr"
         else
           zlib_prefix = Formula["zlib"].opt_prefix
         end
         s.gsub! "openjpeg.h", "probably_not_a_header_called_this_eh.h"
-        s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{zlib_prefix}/lib', '#{zlib_prefix}/include')"
-        s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{sdkprefix}/usr/lib', '#{sdkprefix}/usr/include')"
+        if OS.mac?
+          s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{sdkprefix}/usr/lib', '#{sdkprefix}/usr/include')"
+        else
+          s.gsub! "ZLIB_ROOT = None", "ZLIB_ROOT = ('#{zlib_prefix}/lib', '#{zlib_prefix}/include')"
+        end
         s.gsub! "JPEG_ROOT = None",
                 "JPEG_ROOT = ('#{Formula["jpeg"].opt_prefix}/lib', " \
                              "'#{Formula["jpeg"].opt_prefix}/include')"
```

fixes this locally for me and `brew test` passes.

**Comment by issyl0** [comment]
I stopped being lazy and have pushed a commit for this. :laughing:

**Comment by issyl0** [comment]
Also rebased on master so we don't needlessly build on CircleCI.

**Pull request closed without merging**
