### PR TITLE
node@8: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> brew test node@8 --verbose
Testing node@8
==> /home/linuxbrew/.linuxbrew/Cellar/node@8/8.16.2/bin/node /tmp/node@8-test-20191010-55930-1ttonbr/test.js
==> /home/linuxbrew/.linuxbrew/Cellar/node@8/8.16.2/bin/node -e 'console.log(new Intl.NumberFormat("en-EN").format(1234.56))'
==> /home/linuxbrew/.linuxbrew/Cellar/node@8/8.16.2/bin/node -e 'console.log(new Intl.NumberFormat("de-DE").format(1234.56))'
==> /home/linuxbrew/.linuxbrew/Cellar/node@8/8.16.2/bin/npm -ddd --cache=/home/vsts_azpcontainer/.cache/Homebrew/npm_cache --build-from-source install npm@latest
.
==> /home/linuxbrew/.linuxbrew/Cellar/node@8/8.16.2/bin/npm -ddd --cache=/home/vsts_azpcontainer/.cache/Homebrew/npm_cache --build-from-source install bignum
.
Last 150 lines from /home/vsts_azpcontainer/.cache/Homebrew/Logs/node@8/test.02.npm:
npm sill saveTree   │   ├── get-caller-file@1.0.2
npm sill saveTree   │   ├─┬ os-locale@2.1.0
npm sill saveTree   │   │ ├─┬ lcid@1.0.0
npm sill saveTree   │   │ │ └── invert-kv@1.0.0
npm sill saveTree   │   │ └─┬ mem@1.1.0
npm sill saveTree   │   │   └── mimic-fn@1.2.0
npm sill saveTree   │   ├── require-directory@2.1.1
npm sill saveTree   │   ├── require-main-filename@1.0.1
npm sill saveTree   │   ├── which-module@2.0.0
npm sill saveTree   │   ├── y18n@3.2.1
npm sill saveTree   │   └── yargs-parser@9.0.2
npm sill saveTree   ├── lock-verify@2.1.0
npm sill saveTree   ├── lockfile@1.0.4
npm sill saveTree   ├── lodash._baseindexof@3.1.0
npm sill saveTree   ├─┬ lodash._baseuniq@4.6.0
npm sill saveTree   │ ├── lodash._createset@4.0.3
npm sill saveTree   │ └── lodash._root@3.0.1
npm sill saveTree   ├── lodash._bindcallback@3.0.1
npm sill saveTree   ├── lodash._cacheindexof@3.0.2
npm sill saveTree   ├─┬ lodash._createcache@3.1.2
npm sill saveTree   │ └── lodash._getnative@3.9.1
npm sill saveTree   ├── lodash._getnative@3.9.1
```

**Comment by dawidd6** [comment]
Gonna pull this, as recently `node` was pulled although test was failing as it is here.

https://github.com/Homebrew/linuxbrew-core/pull/15976

**Comment by iMichka** [comment]
Agreed. Thanks!
We can not fix all the tests at once :)

**Comment by iMichka** [comment]
FYI also: everything which is an @X formula has less importance, and users which really need these old formulae should also help fix them when needed.

**Pull request closed without merging**
