### PR TITLE
netpbm: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
You must: brew install svn
```

**Comment by dawidd6** [comment]
Still: 
```
==> brew fetch --retry netpbm --build-bottle --force
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3712
You must: brew install svn
==> Retrying download
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3712
You must: brew install svn
Error: Failed to download resource "netpbm"
Failure while executing; `svn checkout https://svn.code.sf.net/p/netpbm/code/stable /home/vsts_azpcontainer/.cache/Homebrew/netpbm--svn --quiet -r 3712` exited with 1. Here's the output:
You must: brew install svn


==> FAILED
```

**Comment by dawidd6** [comment]
```
Error: 1 problem in 1 formula detected
netpbm:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
==> FAILED
```

I changed this svn source url to a plain .zip archive taken from repo trunk. Looks like it did the trick, but it's more a workaround than a solution.

**Comment by iMichka** [comment]
Let's got with this solution so that we can move forward. But definitively something that needs to be fixed.

**Pull request closed without merging**
