### PR TITLE
#19707 - fix gss_OID gcc error

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
==> Detecting if cups--2.3.1.x86_64_linux.bottle.tar.gz is relocatable...
Warning: String '/home/linuxbrew/.linuxbrew/Cellar' still exists in these files:
/home/linuxbrew/.linuxbrew/Cellar/cups/2.3.1/lib/libcups.so.2
```

**Comment by tseemann** [comment]
```
==> brew install --only-dependencies --include-test cups
All dependencies for cups are satisfied.

==> brew test cups --verbose
Testing cups
Listening on port 8000.
==> /home/linuxbrew/.linuxbrew/Cellar/cups/2.3.1/bin/ippfind
Failed to execute: /home/linuxbrew/.linuxbrew/Cellar/cups/2.3.1/bin/ippfind
Error: cups: failed
Failed executing:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1950:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1887:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1887:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cups.rb:34:in `block in <class:Cups>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1757:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
  Copy bottles1s
  Upload bottles1s
  Post Checkout tap
```

**Comment by issyl0** [comment]
I think the test will always fail on CI because it's looking for a printer.

**Comment by issyl0** [comment]
The `cups` test doesn't pass for me on master either, so I'm just going to merge this.

**Comment by issyl0** [comment]
Thanks, @tseemann!

**Comment by tseemann** [comment]
@issyl0 the test looks like it's forking a process to act as a fake printer, and then querying to see if any printers are listening on a port?

**Pull request merged**
