### PR TITLE
ghc@8.8: fix lint of installed?

### PR DESCRIPTION
**Pull request by sambrightman**
- [Y] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [Y] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [Y] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [N] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Review by issyl0 — APPROVED** [review]
Thanks so much, @sambrightman! You fixed the bottle rebuild the right way!

**Comment by sambrightman** [comment]
It's not clear to me what the build failure is about but I've tried to push a fix based on what I read in #13301.

**Comment by iMichka** [comment]
Hi. Please do not remove the bottle line. We will not rebuild it; and just merge the code change as-is. Please ignore the build failure related to this, our CI setup is a little bit broken on Linux (this will be improved once we merge this repo into the upstream Mac repo).

**Comment by issyl0** [comment]
Oops, sorry for the misinformation!

**Comment by sambrightman** [comment]
Reverted. No problem! Could this be documented somewhere prominent until fixed?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
We could, but this repo is due to be deleted once it is merged into homebrew core, so I am not really focusing on the documentation of soon to be deprecated things (and I am lazy too :D). We do have the main homebrew documentation though, and this could be added there.

**Pull request merged**
