### PR TITLE
postgres-xc: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
```
checking thread safety of required library functions... no
configure: error: thread test program failed
This platform is not thread-safe.  Check the file 'config.log' or compile
and run src/test/thread/thread_test for the exact reason.
Use --disable-thread-safety to disable thread safety.
```

**Comment by iMichka** [comment]
> ERROR: `flex' is missing on your system. It is needed to create the

**Comment by dawidd6** [comment]
Well, yes, but flex should be available already: https://github.com/Homebrew/linuxbrew-core/blob/34a209c1cb7718ca0414263ec034a002cef1a286/Formula/postgres-xc.rb#L22

**Comment by dawidd6** [comment]
```
***
ERROR: `flex' is missing on your system. It is needed to create the
file `gtm_opt_scanner.c'. You can either get flex from a GNU mirror site
or download an official distribution of PostgreSQL, which contains
pre-packaged flex output.
***
```

`flex` still missing, hmm.

**Comment by iMichka** [comment]
I tried to use that env variable they set in the source code. Looks like we need to dig through more source code.

**Comment by dawidd6** [comment]
I got this nonsense locally:
```
checking for flex... configure: WARNING:
*** The installed version of Flex, /home/linuxbrew/.linuxbrew/opt/flex/bin/flex, is too old to use with PostgreSQL.
*** Flex version 2.5.31 or later is required, but this is flex 2.6.4.
configure: WARNING:
*** The installed version of Flex, /home/linuxbrew/.linuxbrew/opt/flex/bin/lex, is too old to use with PostgreSQL.
*** Flex version 2.5.31 or later is required, but this is lex 2.6.4.
no
configure: WARNING:
*** Without Flex you will not be able to build PostgreSQL from Git nor
*** change any of the scanner definition files.  You can obtain Flex from
*** a GNU mirror site.  (If you are using the official distribution of
*** PostgreSQL then you do not need to worry about this because the Flex
*** output is pre-generated.)
```

**Comment by dawidd6** [comment]
Tbh I would drop this package from Homebrew at all, as it seems to be unmaintained anyway: https://tracker.debian.org/news/691354/removed-11-2-from-unstable/

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/pull/43945

It was indeed removed from Homebrew, so I'm going to remove it here too.

**Comment by iMichka** [comment]
Cool. This happens sometimes when a formula is delete upstream and there is a merge conflict when merging into linuxbrew-core: the file sometimes stays in our repo.

I try to have a extra look at formula deletions when I merge, to be sure the file is removed.

**Pull request closed without merging**
