### PR TITLE
amtk: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> cmake
Emacs Lisp files have been installed to:
  /home/linuxbrew/.linuxbrew/share/emacs/site-lisp/cmake
==> FAILED
```

**Comment by iMichka** [comment]
The "Failed" comes at the end of all the post-install steps. This means that one of the post-install steps failed. I searched for `Warning: The post-install step did not complete successfully` in the logs:

```
2019-10-06T10:34:06.4292690Z /home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12/bin/gtk3-update-icon-cache: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
2019-10-06T10:34:06.7560607Z Warning: The post-install step did not complete successfully
2019-10-06T10:34:06.7561621Z You can try again using `brew postinstall gtk+3
```

**Comment by dawidd6** [comment]
So, depends on `gdk-pixbuf`?

**Comment by iMichka** [comment]
`gtk+3` already depends on `gdk-pixbuf`.

This was fixed like this back then: https://github.com/Homebrew/linuxbrew-core/pull/10039, but then this patch broke other stuff ...
This all comes from this `meson` madness (see https://github.com/Homebrew/linuxbrew-core/pull/14979#issuecomment-524663553), and I have no clue what is going on ...

**Pull request closed without merging**
