### PR TITLE
grpc: fix build for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I ran into the same `recompile with -fPIC` errors when trying to build `vtk` while linking to `pugixml` and found that adding `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` to the CMake args for `pugixml` fixed it.  In this case we would need to add it to `abseil` which `grpc` is linking to.  Not sure if that is the solution here but it seems the build still has the same error reported in https://github.com/Homebrew/linuxbrew-core/issues/21699.  

Perhaps we should consider adding `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` as a standard CMake arg as well?  It is my understanding that it makes sure `-fPIC` is always set for shared libraries, and I'm not aware of any situation where that is undesirable.

**Comment by iMichka** [comment]
@danielnachun 99% of the -fPic issues are because the dependency does not provided shared libraries (.so files). abseil only provided static libraries (.a). So -fPic allows to mix both, but ideally we would like to avoid this and use .so files everywhere.

I am trying to build the shared libraries for abseil here: #21791

**Comment by danielnachun** [comment]
I see, the -fPIC warnings are more of a symptom than the cause of the problem.  There are a couple other formulae I've been working on which had similar issues, and now I can check if explicitly enabling shared libraries is sufficient to fix them.  Thanks for the explanation!

**Comment by iMichka** [comment]
```
2020-12-13T14:37:52.8369117Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-9 -Dgrpc___EXPORTS -I/tmp/grpc-20201213-17015-7nmz7z/include -I/tmp/grpc-20201213-17015-7nmz7z -I/tmp/grpc-20201213-17015-7nmz7z/third_party/address_sorting/include -I/tmp/grpc-20201213-17015-7nmz7z/src/core/ext/upb-generated -I/tmp/grpc-20201213-17015-7nmz7z/src/core/ext/upbdefs-generated -I/tmp/grpc-20201213-17015-7nmz7z/third_party/upb -I/tmp/grpc-20201213-17015-7nmz7z/cmake/build/gens -DNDEBUG -fPIC -std=c++17 -o CMakeFiles/grpc++.dir/src/cpp/client/channel_cc.cc.o -c /tmp/grpc-20201213-17015-7nmz7z/src/cpp/client/channel_cc.cc
2020-12-13T14:37:52.8373441Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::strings_internal::CatPieces[abi:cxx11](std::initializer_list<std::basic_string_view<char, std::char_traits<char> > >)'
2020-12-13T14:37:52.8375575Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::Cord::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
2020-12-13T14:37:52.8378275Z /home/linuxbrew/.linuxbrew/bin/ld: libgpr.so.13.0.0: undefined reference to `bool absl::lts_2020_09_23::str_format_internal::FormatArgImpl::Dispatch<std::basic_string_view<char, std::char_traits<char> > >(absl::lts_2020_09_23::str_format_internal::FormatArgImpl::Data, absl::lts_2020_09_23::str_format_internal::FormatConversionSpecImpl, void*)'
2020-12-13T14:37:52.8380974Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::Status::GetPayload(std::basic_string_view<char, std::char_traits<char> >) const'
2020-12-13T14:37:52.8383084Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::Status::SetPayload(std::basic_string_view<char, std::char_traits<char> >, absl::lts_2020_09_23::Cord)'
2020-12-13T14:37:52.8385378Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::EqualsIgnoreCase(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >)'
2020-12-13T14:37:52.8387661Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::Status::Status(absl::lts_2020_09_23::StatusCode, std::basic_string_view<char, std::char_traits<char> >)'
2020-12-13T14:37:52.8389962Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::numbers_internal::safe_strto64_base(std::basic_string_view<char, std::char_traits<char> >, long*, int)'
2020-12-13T14:37:52.8392183Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::ByChar::Find(std::basic_string_view<char, std::char_traits<char> >, unsigned long) const'
2020-12-13T14:37:52.8394170Z /home/linuxbrew/.linuxbrew/bin/ld: libgrpc.so.13.0.0: undefined reference to `absl::lts_2020_09_23::numbers_internal::safe_strto32_base(std::basic_string_view<char, std::char_traits<char> >, int*, int)'
2020-12-13T14:37:52.8395227Z collect2: error: ld returned 1 exit status
2020-12-13T14:37:52.8396321Z CMakeFiles/check_epollexclusive.dir/build.make:142: recipe for target 'check_epollexclusive' failed
2020-12-13T14:37:52.8397210Z make[2]: *** [check_epollexclusive] Error 1
2020-12-13T14:37:52.8398144Z make[2]: Leaving directory '/tmp/grpc-20201213-17015-7nmz7z/cmake/build'
2020-12-13T14:37:52.8399304Z CMakeFiles/Makefile2:429: recipe for target 'CMakeFiles/check_epollexclusive.dir/all' failed
2020-12-13T14:37:52.8400247Z make[1]: *** [CMakeFiles/check_epollexclusive.dir/all] Error 2
2020-12-13T14:37:52.8400928Z make[1]: *** Waiting for unfinished jobs....
```

**Comment by iMichka** [comment]
> I see, the -fPIC warnings are more of a symptom than the cause of the problem

Exactly. Took me some time to find that out. There are still some -fPic flags in this repo: we will eventually get rid them of them when someone has time to check what shared libraries are missing.

I triggered a new build here, and the build is now failing with weird linkage errors ...

**Comment by danielnachun** [comment]
Strangely enough, I tried to build this with gcc-5 and it worked.  Maybe a newer GCC is not needed?

**Comment by iMichka** [comment]
I tried a build with gcc5:

```
2020-12-14T22:51:11.0832078Z CMakeFiles/grpc_cli.dir/test/cpp/util/cli_credentials.cc.o: In function `_GLOBAL__sub_I__ZN3fLB16FLAGS_enable_sslE':
2020-12-14T22:51:11.0835372Z cli_credentials.cc:(.text.startup+0x99): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0837812Z cli_credentials.cc:(.text.startup+0xc8): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0841178Z cli_credentials.cc:(.text.startup+0x13c): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0844988Z cli_credentials.cc:(.text.startup+0x1f4): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0848803Z cli_credentials.cc:(.text.startup+0x2ac): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0852585Z cli_credentials.cc:(.text.startup+0x364): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0856379Z cli_credentials.cc:(.text.startup+0x41c): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0860616Z CMakeFiles/grpc_cli.dir/test/cpp/util/cli_credentials.cc.o:cli_credentials.cc:(.text.startup+0x4d4): more undefined references to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)' follow
2020-12-14T22:51:11.0863378Z CMakeFiles/grpc_cli.dir/test/cpp/util/grpc_tool.cc.o: In function `_GLOBAL__sub_I__ZN4grpc7testing3fLB7FLAGS_lE':
2020-12-14T22:51:11.0865362Z grpc_tool.cc:(.text.startup+0xdf): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0867654Z grpc_tool.cc:(.text.startup+0x10e): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0870753Z grpc_tool.cc:(.text.startup+0x189): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0874475Z grpc_tool.cc:(.text.startup+0x248): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0878249Z grpc_tool.cc:(.text.startup+0x307): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0881036Z grpc_tool.cc:(.text.startup+0x37a): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0883173Z grpc_tool.cc:(.text.startup+0x3a9): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0886192Z grpc_tool.cc:(.text.startup+0x424): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0888990Z grpc_tool.cc:(.text.startup+0x497): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0891143Z grpc_tool.cc:(.text.startup+0x4c6): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0893281Z grpc_tool.cc:(.text.startup+0x4f5): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0897670Z grpc_tool.cc:(.text.startup+0x570): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
2020-12-14T22:51:11.0900484Z grpc_tool.cc:(.text.startup+0x5e3): undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
2020-12-14T22:51:11.0902696Z grpc_tool.cc:(.text.startup+0x612): undefined reference to `google::FlagRegisterer::FlagRegisterer<double>(char const*, char const*, char const*, double*, double*)'
2020-12-14T22:51:11.0904685Z libgrpc++_test_config.so.1.33.2: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
2020-12-14T22:51:11.0905717Z collect2: error: ld returned 1 exit status
2020-12-14T22:51:11.0906693Z CMakeFiles/grpc_cli.dir/build.make:314: recipe for target 'grpc_cli' failed
2020-12-14T22:51:11.0907393Z make[3]: *** [grpc_cli] Error 1
2020-12-14T22:51:11.0908403Z make[3]: Leaving directory '/tmp/grpc-20201214-13640-f04ier/cmake/build'
2020-12-14T22:51:11.0909539Z CMakeFiles/Makefile2:2738: recipe for target 'CMakeFiles/grpc_cli.dir/all' failed
2020-12-14T22:51:11.0910381Z make[2]: *** [CMakeFiles/grpc_cli.dir/all] Error 2
2020-12-14T22:51:11.0911337Z make[2]: Leaving directory '/tmp/grpc-20201214-13640-f04ier/cmake/build'
2020-12-14T22:51:11.0912497Z CMakeFiles/Makefile2:2745: recipe for target 'CMakeFiles/grpc_cli.dir/rule' failed
2020-12-14T22:51:11.0913411Z make[1]: *** [CMakeFiles/grpc_cli.dir/rule] Error 2
2020-12-14T22:51:11.0914385Z make[1]: Leaving directory '/tmp/grpc-20201214-13640-f04ier/cmake/build'
2020-12-14T22:51:11.0915447Z Makefile:940: recipe for target 'grpc_cli' failed
2020-12-14T22:51:11.0916008Z make: *** [grpc_cli] Error 2
```

This looks like it needs at least a c++11 compatible compiler, which gcc5 is not. This is why I tried newer version.

**Comment by danielnachun** [comment]
What happens if you add  `ENV.append "CXXFLAGS", "--std=c++14"` to the formula while trying to use `gcc5`?  In my build logs for `grpc`, I see it actually set `--std=c++1z` which is a synonym for `std=c++17`.

I may be be mistaken, but I think according to [this page](https://gcc.gnu.org/projects/cxx-status.html), `gcc5` actually supports up C++14 fully, and even a few features from C++17.  I've definitely used the brewed `gcc5` to compile a bunch of C++14 code for R packages without any issues.

**Comment by danielnachun** [comment]
That makes me wonder if the C++11 errors  (or C++14 in other packages) are misleading - `gcc5` supports both standards but does not do so by default.  If CMake doesn't set this properly and we don't explicitly set it, it will only work with versions of GCC that enable C++11/C++14 by default.  

Perhaps I get different results for some packages because CMake decides whether to add `--std=c++11/`/`--std=c++14` based on things they pick up in the host environment, which varies between CI and my local environment for example.  

I was actually able to get `libproxy` to compile with `gcc5` by explicitly adding `--std=c++14` to the `CXXFLAGS` as well.  And `protobuf`, `mysql`, and `mariadb` all worked with `gcc5` without needing any modification for me, and I can see they have append `--std=c++11` automatically (though I suspect they don't in CI).

**Comment by danielnachun** [comment]
If adding `--std=c++11`/`--std=c++14` explicitly allows us to use `gcc5` to compile any software which needs C++11/C++14, we might be able to revisit whether other packages which appear to need to a newer version of `gcc` actually do not.  The only packages I currently have installed which don't work with `gcc5` are ones which explicitly say in their build instructions that they need full C++17 support - currently `ccls` and `pstoedit`.

**Comment by gromgit** [comment]
@danielnachun , you can add to your list `atomicparsley`, which someone just requested a bottle for. The nature of the failure:

https://github.com/Homebrew/linuxbrew-core/runs/1568019099?check_suite_focus=true#step:5:130

points towards a general need to be explicit about required C++ standards.

**Comment by danielnachun** [comment]
I see in the CI that this failed.  I have one more crazy idea.  Before I found that `mariadb` built with `gcc5`, I could not get it to build with a newer version of `gcc` unless I replaced the `$(brew --prefix)/lib/libstdc++.so.6` with a symlink to `libstdc++.so.6` from whatever newer version of `gcc` I was using (I tried all versions from 6 to 9 and everything happened the same way).  

I don't really understand why files in `$(brew --prefix)/lib` would affect the build process because I thought those are "hidden" by the superenv.  But my guess was that if you link to other libraries which also link to `libstdc++.so.6` a conflict can happen where you are trying to link to two different versions of `libstdc++.so.6`.  I can see that protobuf is one of the dependencies for `grpc` and it depends on gcc6.  If `protobuf` can be built with gcc5 (again by explicitly specifying C++ standards), then I think all the dependencies of `grpc` would be linking to the same version of `libstdc++.so.6`, and that might fix it.

I could be totally wrong about this, but you never know what could end up working!  This issue seems to point to some larger challenges around how to deal with multiple versions of the GCC standard libraries (`libgfortran` might theoretically suffer from the same issue).

**Comment by iMichka** [comment]
Found it: #21859
`gflags` needed to be compiled with gcc6 (so it uses c++11 I guess).

`grpc` now builds fine. I just need to understand why the test is failing here.

**Pull request closed without merging**
