### PR TITLE
pyenv: drop python2 dependency

### PR DESCRIPTION
**Pull request by ulidtko**
Hi!

The crux of this PR is [this](https://github.com/pyenv/pyenv#in-contrast-with-pythonbrew-and-pythonz-pyenv-does-not), that `pyenv` doesn't require python to build and install, and never did.

That the formula here mentions python2, I think, is a bug.

It looks like it's causing a CI failure here: ycm-core/ycmd#1301

OSX's homebrew doesn't install python2 for `pyenv` either; so I'm sending the PR to this repo, per CONTRIBUTING.md.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> brew style pyenv
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pyenv.rb ==
C: 22:  1: Layout/TrailingWhitespace: Trailing whitespace detected.

1 file inspected, 1 offense detected
==> FAILED
```

**Comment by ulidtko** [comment]
Hey @iMichka, thanks for your reply.

> We are testing if pyenv works correctly.

So python2 is only a test dependency of pyenv, is this what you're saying?..

I wonder then why doesn't the [`pyenv` formula in the main OSX homebrew][•] have a similar declaration, even though it does define testing as well?..

[•]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb

--------
Perhaps this is altogether irrelevant; [the actual issue](http://xyproblem.info/) I'm trying to solve is this Dockerfile not building:

```Dockerfile
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        git \
        make \
        clang-3.5 \
        openssl \
        sudo \
        && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 100 ; \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.5 100 ; \
    adduser tester ; \
    echo "tester ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER tester

RUN echo "Installing linuxbrew" ; \
    eval "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

RUN echo "Installing pyenv from brew" ; \
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && \
    brew install pyenv

RUN echo "Installing Python 2.7.16 via pyenv" ; \
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && \
    eval "$(pyenv init -)" && \
    pyenv install 2.7.16
```

```
$ # Single-line repro if you have Docker:
$ docker build https://gist.github.com/ulidtko/5373443f70f4ab4e6d6030f301c4334f/raw/b232b84c76eebc053237ca23cdb87415f84838b8/Dockerfile.brew.minimal
    [...]
 ---> Running in 6a09ab385992
Installing Python 2.7.16 via pyenv
Downloading Python-2.7.16.tar.xz...
-> https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tar.xz
Installing Python-2.7.16...
python-build: use readline from homebrew
ERROR: The Python zlib extension was not compiled. Missing the zlib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 16.04 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20190916101452.249
Results logged to /tmp/python-build.20190916101452.249.log

Last 10 log lines:
rm -f /home/tester/.pyenv/versions/2.7.16/share/man/man1/python.1
(cd /home/tester/.pyenv/versions/2.7.16/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
	case no in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
The command '/bin/sh -c echo "Installing Python 2.7.16 via pyenv" ;     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" &&     eval "$(pyenv init -)" &&     pyenv install 2.7.16' returned a non-zero code: 1

```

`pyenv` itself does get installed; however, `pyenv install 2.7.16` fails.

The build logs reveal that the built Python 2.7.16 fails to import its native modules e.g. `_ctypes.so`, `_struct.so`, `_ssl.so`, `zlibmodule.so`, etc.

Could you please shed some light here; is it even supposed to work like this? Or do I need to pass more compile flags via the environment, like the brew's "Caveats" output suggests?

------
P.S. I'd fixed the trailing whitespace issue raised above, by force-pushing.

**Comment by ulidtko** [comment]
Re:

> Using :test makes sure no python gets installed on your setup, it will only be install on the CI system.

Okay, I understand and accept the intent here.

However, that doesn't match what really happens. As part of `brew install pyenv` on my user-side system (not on homebrew CI), this happens:

> ==> Installing dependencies for pyenv: patchelf, xz, zlib, m4, gmp, mpfr, libmpc, isl@0.18, gcc, gdbm, openssl@1.1, berkeley-db, libbsd, expat, perl, autoconf, pkg-config, ncurses, readline, sqlite, bzip2 and python@2

and of course, a python2 *does* get installed a bit later. This isn't the pyenv's python, it's the brew
one. So the `:test` decoration doesn't work as intended. Or I'm horribly confused :)

**Comment by ulidtko** [comment]
Ah yes. I do definitely get interference with brew's python@2 when building new python2 with pyenv.

Errors like [here][•], undefined references to PyUnicodeUCS4_* symbols -- indicate some kind of link path problem leading to python-build picking up .so modules from brew's python@2.

Further, the errors go away once I `brew uninstall python@2` just before `pyenv install -v 2.7.16`.

[•]: https://effbot.org/pyfaq/when-importing-module-x-why-do-i-get-undefined-symbol-pyunicodeucs2.htm

**Comment by iMichka** [comment]
```
So python2 is only a test dependency of pyenv, is this what you're saying?..

I wonder then why doesn't the pyenv formula in the main OSX homebrew have a similar declaration, even though it does define testing as well?..
```

Because on mac, Python 2 is already there. So the test can use the system Python 2. On Linux, we need to install it.

> ==> Installing dependencies for pyenv: patchelf, xz, zlib, m4, gmp, mpfr, libmpc, isl@0.18, gcc, gdbm, openssl@1.1, berkeley-db, libbsd, expat, perl, autoconf, pkg-config, ncurses, readline, sqlite, bzip2 and python@2

Weird. Once you remove `python@2` from this formula, `python@2` is not in the list anymore. You can also check:
`brew deps --tree --include-build --include-test pyenv`

Though your list looks bigger. I see gcc in there for example. So `python@2` probably comes in through another dependency requirement.

I also played around, without any modification:
```
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# brew uninstall python@2
Uninstalling /home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16_1... (5,689 files, 87.3MB)
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# python
bash: python: command not found
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# brew test pyenv
Error: pyenv is missing test dependencies: python@2
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# 
```

Notice how brew asks for `python@2` to be installed.
I then removed the `python@2` dependency, and ran the test again:

```
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# brew test pyenv
Testing pyenv
==> eval "$(/home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.13_1/bin/pyenv init -)" && pyenv versions
Warning: no Python detected on the system
Error: pyenv: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
root@f97bf7430b4a:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula# pyenv versions
Warning: no Python detected on the system
```

`pyenv` does ask for Python 2.

**Comment by ulidtko** [comment]
> Because on mac, Python 2 is already there. So the test can use the system Python 2. On Linux, we need to install it.

Understood.

> Error: pyenv is missing test dependencies: python@2
> Notice how brew asks for python@2 to be installed.

This is again understood and expected. No questions here.

> Weird. Once you remove python@2 from this formula, python@2 is not in the list anymore.

Yes, exactly. I'm fine if `python@2` installs because I passed `--include-test`. But without `--include-test`, it shouldn't appear.

----------

> pyenv does ask for Python 2.

Let me disagree in the following way. pyenv [does not need][•] python to install or run. But, with the way how `brew test` is defined in the formula, it's not testing "pyenv works" -- it's testing "pyenv can run && there's a python version installed which pyenv can find". Since `brew test` doesn't exercise  `pyenv install 3.4.5`, the test becomes equivalent to "did brew get us any python already" (to be found by `pyenv versions` as a "system" python), and so it fails with the "fixed" formula.

In fact, try a better test: revert to the original formula, `brew install pyenv && eval $(pyenv init -) && pyenv install -v 2.7.16`. It will fail. Even if you set up the environment [perfectly][°]. Next, compare to `brew install pyenv && brew uninstall python@2 && eval $(pyenv init -) && pyenv install -v 2.7.16` -- this will work. If this dependency wouldn't be unneeded *and breaking stuff*, I wouldn't be here.

-------

[•]: https://github.com/pyenv/pyenv#in-contrast-with-pythonbrew-and-pythonz-pyenv-does-not
[°]: https://gist.github.com/ulidtko/5373443f70f4ab4e6d6030f301c4334f#file-dockerfile-brew-minimal

Frankly, pyenv has its own test suite, https://github.com/pyenv/pyenv/tree/master/test
To be completely thorough, you'd run *that* in `brew test`.

**Comment by ulidtko** [comment]
Agh... Sorry for torturing you with that python/brew/pyenv/install word soup. I tried to keep it simple -- it just isn't.

Let's say it straight: my current patch, as it stands, is incorrect. Perhaps this:

diff
-    depends_on "python@2" => :test unless OS.mac?
+    depends_on "python@2" => :test

... It's linuxbrew after all.

My Ruby isn't strong, but I wonder whether precedence grouping of `unless` is what's misfiring here.

**Comment by ulidtko** [comment]
I had updated the patch. But from my testing, it doesn't really solve the issue: `brew install pyenv` still pulls python@2. I'd expect it to only pull python@2 when I do `brew install --include-test pyenv`.

So, the `:test` decoration isn't working as intended. And I'm out of ideas at this point.

**Comment by iMichka** [comment]
I opened an issue for the :test dependency: https://github.com/Homebrew/brew/issues/6470. I agree that `:test` dependencies should not be installed by default, only on request or on our CI. This is a regression that was introduced lately I guess.

Nevertheless, you may install any other formula needing `python@2`, and end up with `python@2` on your system. Having `python@2` installed should not break `pyenv`.

Regarding you python build failure, I ran `pyenv install 2.7.16` in our docker container, and it gave me:

```
*** WARNING: renaming "readline" since importing it failed: libreadline.so.8: cannot open shared object file: No such file or directory
building '_curses' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I./Include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I/root/.pyenv/versions/2.7.16/include -fPIC -I. -IInclude -I./Include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I/root/.pyenv/versions/2.7.16/include -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/tmp/python-build.20190917190212.79234/Python-2.7.16/Include -I/tmp/python-build.20190917190212.79234/Python-2.7.16 -c /tmp/python-build.20190917190212.79234/Python-2.7.16/Modules/_cursesmodule.c -o build/temp.linux-x86_64-2.7/tmp/python-build.20190917190212.79234/Python-2.7.16/Modules/_cursesmodule.o
In file included from /tmp/python-build.20190917190212.79234/Python-2.7.16/Modules/_cursesmodule.c:114:0:
Include/py_curses.h:52:20: fatal error: curses.h: No such file or directory
compilation terminated.

Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _curses_panel      _sqlite3        
_ssl               _tkinter           bsddb185        
bz2                dbm                dl              
gdbm               imageop            sunaudiodev     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
_curses            readline                           
```

I have the feeling that all these are `pyenv` issues. It fails to find the right dependencies to build `python 2`. Not much we can about this: either it is a bug in `pyenv`, or either you need to give it the right paths for the build to happen.

Note:
> Frankly, pyenv has its own test suite, https://github.com/pyenv/pyenv/tree/master/test
To be completely thorough, you'd run that in brew test.

We let upstream run their test suite most of the time. That's their responsibility. Our tests are just a quick check to see if everything is fine, and a little bit more involved than `command --help` or `command --version`. See https://docs.brew.sh/Formula-Cookbook#add-a-test-to-the-formula for the guidelines regarding tests.

**Comment by ulidtko** [comment]
Great, so they indeed fixed it.

I tested that the `unless` issue is still there; with the patch in this PR, pyenv installs as expected with and without `--include-test`. I've bumped the revision and pushed a "ready to merge" version.

Totally agreed with your previous comment. `pyenv` is certainly to be improved, but I'll let it be for now.

Please merge if you're happy with the change (and the CI goes green). Sincerely thanks for you patience and understanding. Keep up the great work!

**Comment by ulidtko** [comment]
Ah well.

>   * C: 22: col 3: FormulaAudit/DependencyOrder: dependency "python@2" (line 22) should be put before dependency "readline" (line 21)

**Comment by ulidtko** [comment]
>   * C: 21: col 3: FormulaAudit/DependencyOrder: dependency "python@2" (line 21) should be put before dependency "pkg-config" (line 20)

Ehh... it's not the sort order?.. I don't get this.

https://github.com/Homebrew/brew/blob/6053b6dc5b4de6919222123b6c504f149fdd6636/Library/Homebrew/rubocops/dependency_order_cop.rb#L5-L11

Time to run `brew audit` myself I guess.

**Comment by iMichka** [comment]
> Ehh... it's not the sort order?

Everything which has `:build`, `test`, and so on goes to the top of the list and has it's own order.

Note that the `--include-test` flag only works for `brew deps`, not for `brew install`.

I do not believe that removing `unless OS.mac?` changes anything to the logic on Linux. It is the same as:
```
unless OS.mac?
  depends_on "python@2" => :test
end
```

Which means:
```
unless False
  depends_on "python@2" => :test
end
```

I could not reproduce the difference you mention by removing it.

**Comment by iMichka** [comment]
The fix in https://github.com/Homebrew/brew/issues/6470 has been reverted, but a fix will eventually come. This will prevent the installation of test dependencies when not needed.

The other pyenv failures are not related to brew: this is a setup problem, pyenv probably needs some flags to know where to find it's dependencies.

I will close this PR as there is nothing on our side we can do.

**Pull request closed without merging**
