### PR TITLE
Remove circular reference in issue templates

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----
Instead, redirect macOS users to the Homebrew/homebrew-core repo.

See https://github.com/Homebrew/discussions/discussions/858

I don't think this will cause any issues with merges unless there are changes made to the issue template `config.yml` file in homebrew/core (which is pretty rare).

### CODE REVIEW

**Review by iMichka — APPROVED** [review]

**Comment by Bo98** [comment]
Looks like bug.yml doesn't work properly here (or bottle requests are the only thing allowed here). Maybe bottle.md needs converting to bottle.yml to be consistent.

**Comment by mellery451** [comment]
if I have a "brew install" failure on linux only...where do we create the issue? Seem like this is going to make us go to homebrew-core, unless I misunderstand the links here

**Comment by Rylan12** [comment]
Ah, I see. I misunderstood the problem a little bit. Yeah, it looks like the `bug` issue template is no longer available, which explains your confusion, @mellery451. There isn't actually way to open an issue, at the moment. I think the solution is to move the `bottle` template to the new issue template format. I'll have a go at converting in a few minutes.

**Comment by Rylan12** [comment]
Okay, I modified the `bottle` template to use the new template syntax. I think I've got everything set up correctly, but I haven't been able to test. I also don't know if we need to somehow enable the new templates for this repository. I think(?) this will bring back both the `bug` and `bottle` templates.

CC: @MikeMcQuaid (if this doesn't work can you help diagnose?)

**Comment by MikeMcQuaid** [comment]
> I also don't know if we need to somehow enable the new templates for this repository

I think it's been shipped for the whole org.

**Comment by Bo98** [comment]
> haven't been able to test

It's one of those cases where you just have to merge and see if it works.

**Comment by Rylan12** [comment]
Agreed. As this is blocking potential issues from being opened, can this be merged?

**Comment by Bo98** [comment]
The syntax has now changed :-)

See here for an example: https://github.com/Homebrew/homebrew-core/pull/71202

(Might be easier for a merge to happen for the bug.yml change first?)

**Comment by Rylan12** [comment]
Ah, perfect timing! I was just about to comment that this shouldn't be merged yet 😅

I'm fine with waiting. No real preference. Either way, the issue templates won't be 100% working until both are fixed, I think.

**Comment by Rylan12** [comment]
Okay, I believe I've updated to use the new syntax. When this is merged, I'll double-check to make sure there are no syntax errors.

**Review by Bo98 — APPROVED** [review]

**Comment by Rylan12** [comment]
Now that the syntax fixes from Homebrew/homebrew-core [have been merged](https://github.com/Homebrew/linuxbrew-core/commit/6004e8d07a09f37730a230c9dbbdfe9f4413b721), I think this is ready for a first attempt.

**Comment by Rylan12** [comment]
Thanks, @issyl0!

Unfortunately, this [didn't seem to work](https://github.com/Homebrew/linuxbrew-core/issues/new/choose):

Screen Shot 2021-02-20 at 11 21 45 AM

**Comment by Bo98** [comment]
It looks like it's just not been enabled properly on this repository. @MikeMcQuaid will know who to ask to try get it enabled here.

**Comment by Rylan12** [comment]
(In the process of reverting)

**Comment by MikeMcQuaid** [comment]
> It looks like it's just not been enabled properly on this repository. @MikeMcQuaid will know who to ask to try get it enabled here.

This has been done now.

**Comment by Rylan12** [comment]
Thanks, Mike! I opened #22358 to fix everything up.

**Pull request merged**
