### PR TITLE
libsasl2: fix upstream URL

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----
 
The upstream URL for this doesn't work anymore, but the Github repository provides the exact same file.

### CODE REVIEW

**Comment by jonchang** [comment]
This should be submitted to homebrew/core instead. Please do so and tag me so we can get it merged. Thanks!

**Comment by danielnachun** [comment]
I'll move it over to homebrew/core

**Comment by danielnachun** [comment]
This formula is Linux only, so I think we should leave it here.

**Comment by jonchang** [comment]
My bad, good catch!

**Pull request merged**
