### PR TITLE
awscli: needs zlib

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> brew linkage --test awscli
==> FAILED
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
No broken library linkage detected
```

Even though I added zlib dependency.
@iMichka could you help here?

**Comment by jonchang** [comment]
I'm fairly certain I know what the fix is. Testing it out now.

**Comment by jonchang** [comment]
Ah nevermind, for some reason PyInstaller is listed as a dependency. Pretty sure they only use that for packaging purposes and we can just :boom: that.

**Comment by jonchang** [comment]
We really should move to vendored resources in upstream homebrew/core now that the python resource updater is merged. pyinstaller isn't listed in their setup.py

**Comment by iMichka** [comment]
Can you back port this change to homebrew-core?

**Comment by jonchang** [comment]
Sure, once homebrew-core is working again 😅

**Comment by dawidd6** [comment]
Thanks @jonchang !

**Pull request merged**
