### PR TITLE
netdata: fix build for linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
libnetdata/libnetdata.h:88:23: fatal error: uuid/uuid.h: No such file or directory
compilation terminated.
```

**Comment by dawidd6** [comment]
Guess this has to be adapted:

```
UUID_CFLAGS=-I/usr/include
```

**Comment by danielnachun** [comment]
I think we need to change `UUID_LIBS` to `-luuid` on Linux as well.  Right now its trying to use `glibc` for that because of `-lc`, which I think will be incompatible with the headers from `util-linux`.

**Comment by iMichka** [comment]
Thanks, that worked. Backporting here: https://github.com/Homebrew/homebrew-core/pull/70926

**Pull request closed without merging**
