### PR TITLE
crystal: Fix build for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Looks like it didn't fix it:

```
==> make crystal release=true FLAGS=--no-debug CRYSTAL_CONFIG_LIBRARY_PATH=
Using /home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config [version=11.1.0]
CRYSTAL_CONFIG_LIBRARY_PATH="" CRYSTAL_CONFIG_BUILD_COMMIT="" SOURCE_DATE_EPOCH="1612278414" ./bin/crystal build --no-debug --release  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `std::_Sp_make_shared_tag::_S_eq(std::type_info const&)@GLIBCXX_3.4.26'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/11.1.0_1/lib/libLLVM-11.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `gcc-5 "${@}" -o /tmp/crystal-20210315-7565-goc1ju/crystal-0.36.1/.build/crystal  -rdynamic -L/home/linuxbrew/.linuxbrew/opt/bdw-gc/lib -L/home/linuxbrew/.linuxbrew/lib -L/tmp/crystal-20210315-7565-goc1ju/crystal-0.36.1/boot/bin/../lib/crystal/lib /tmp/crystal-20210315-7565-goc1ju/crystal-0.36.1/src/llvm/ext/llvm_ext.o `"/home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config" --libs --system-libs --ldflags 2> /dev/null` -lstdc++ -lpcre -lm -lgc -lpthread /tmp/crystal-20210315-7565-goc1ju/crystal-0.36.1/src/ext/libcrystal.a -L/home/linuxbrew/.linuxbrew/Cellar/libevent/2.1.12/lib -levent -lrt -ldl`
Makefile:121: recipe for target '.build/crystal' failed
make: *** [.build/crystal] Error 1
/usr/bin/ruby -e puts\ RUBY_VERSION
```

**Comment by alexanderadam** [comment]
How can I test this patch locally? :thinking:

**Comment by dawidd6** [comment]
For example:

```
cd $(brew --repo homebrew/core)
hub pr checkout 22492
brew install -sv crystal
```

**Comment by iMichka** [comment]
My conclusion here is that `crystal` only builds with llvm9.

I am struggling with brew compiler selector though. I might need to add llvm 9 to the PATH as it is keg-only?

**Comment by alexanderadam** [comment]
Does the bot unstale this issue on comments?

**Comment by iMichka** [comment]
Yes. But nobody is working on a fix nevertheless.

**Comment by alexanderadam** [comment]
> Yes.

It doesn't seem so. The `stale` tag is still present.

> But nobody is working on a fix nevertheless.

What a pity.

> My conclusion here is that `crystal` only builds with llvm9.

I'm not sure whether it is relevant but people in [this issue](https://github.com/crystal-lang/crystal/issues/8725) seem to be using LLVM from 6 to [10](https://github.com/crystal-lang/crystal/issues/8725#issuecomment-619731346).

I don't know anything about homebrew though (nor what "keg-only" means). :disappointed:

**Comment by Blacksmoke16** [comment]
@iMichka Might be worth trying again with LLVM 11.

Ref: https://github.com/Homebrew/homebrew-core/pull/79289

**Comment by iMichka** [comment]
The latest changes fixed it, there is now a bottle again for crystal.

**Pull request closed without merging**
