### PR TITLE
Add lm_sensors support for htop on Linux

### PR DESCRIPTION
**Pull request by henryhchchc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Added `lm_sensors` support for htop on Linux, which enables showing CPU temperatures.

### CODE REVIEW

**Comment by henryhchchc** [comment]
Hi the CI error shows a difference in the sha256 of the bottles. Should I add a commit to update it accordingly?

**Comment by danielnachun** [comment]
We're very close to merging this repo with homebrew-core, so once this is PR looks good, I will be closing it and opening one in homebrew-core instead.

**Comment by iMichka** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/80412, will close here, the change will be merged to this repo soon.

**Comment by iMichka** [comment]
Thanks @henryhchchc !

**Pull request closed without merging**
