### PR TITLE
balena-cli: remove --unsafe-perm

### PR DESCRIPTION
**Pull request by dawidd6**
Wait for https://github.com/Homebrew/brew/pull/7089 to get merged first.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by jonchang** [comment]
This would also need to wait for a stable Homebrew/brew release to be tagged after that pull request is merged.

**Comment by dawidd6** [comment]
We only need this option to build the bottle on CI, where root is used.

**Comment by jonchang** [comment]
Ah, that's right, so this is a no-op change on non-CI builds.

**Comment by iMichka** [comment]
No need to bump the revision then. We can just drop the flag.

**Comment by dawidd6** [comment]
Sure, I just want to see a green tick first :D

**Pull request merged**
