### PR TITLE
rethinkdb: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-09-10T17:31:02.6572411Z python:                         error
2019-09-10T17:31:02.6572736Z * Error: missing PYTHON. Install it or specify the full path with PYTHON=
2019-09-10T17:31:02.6572983Z 
2019-09-10T17:31:02.6573139Z * Aborting configure
2019-09-10T17:31:03.6106664Z 
2019-09-10T17:31:03.6107683Z ==> Formula
2019-09-10T17:31:03.6119062Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rethinkdb.rb
```

**Comment by iMichka** [comment]
```
2019-09-10T19:36:48.4247488Z     [157/429] CC build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o
2019-09-10T19:36:48.4247745Z In file included from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:0:
2019-09-10T19:36:48.4249479Z ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:502:10: error: field â€˜bn_â€™ has incomplete type â€˜BIGNUM {aka bignum_st}â€™
2019-09-10T19:36:48.4249879Z    BIGNUM bn_;
2019-09-10T19:36:48.4250088Z           ^
2019-09-10T19:36:48.4250795Z In file included from /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/bn.h:19:0,
2019-09-10T19:36:48.4251161Z                  from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
2019-09-10T19:36:48.4251375Z                  from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
2019-09-10T19:36:48.4252017Z /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/ossl_typ.h:80:16: note: forward declaration of â€˜BIGNUM {aka struct bignum_st}â€™
2019-09-10T19:36:48.4252511Z  typedef struct bignum_st BIGNUM;
2019-09-10T19:36:48.4252742Z                 ^
2019-09-10T19:36:48.4252937Z In file included from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:0:
2019-09-10T19:36:48.4254039Z ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h: In constructor â€˜geo::ExactFloat::ExactFloat()â€™:
2019-09-10T19:36:48.4254891Z ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:562:15: error: â€˜BN_initâ€™ was not declared in this scope
2019-09-10T19:36:48.4255237Z    BN_init(&bn_);
2019-09-10T19:36:48.4255437Z                ^
2019-09-10T19:36:48.4255954Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In function â€˜int geo::BN_ext_count_low_zero_bits(const BIGNUM*)â€™:
2019-09-10T19:36:48.4256656Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:93:25: error: invalid use of incomplete type â€˜const BIGNUM {aka const struct bignum_st}â€™
2019-09-10T19:36:48.4257210Z    for (int i = 0; i < bn->top; ++i) {
2019-09-10T19:36:48.4258016Z                          ^
2019-09-10T19:36:48.4258407Z In file included from /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/bn.h:19:0,
2019-09-10T19:36:48.4258654Z                  from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
2019-09-10T19:36:48.4258858Z                  from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
2019-09-10T19:36:48.4259493Z /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/ossl_typ.h:80:16: note: forward declaration of â€˜BIGNUM {aka struct bignum_st}â€™
2019-09-10T19:36:48.4259798Z  typedef struct bignum_st BIGNUM;
2019-09-10T19:36:48.4259989Z                 ^
2019-09-10T19:36:48.4260885Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:94:20: error: invalid use of incomplete type â€˜const BIGNUM {aka const struct bignum_st}â€™
2019-09-10T19:36:48.4262104Z      BN_ULONG w = bn->d[i];
2019-09-10T19:36:48.4262498Z                     ^
2019-09-10T19:36:48.4262892Z In file included from /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/bn.h:19:0,
2019-09-10T19:36:48.4263181Z                  from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
2019-09-10T19:36:48.4263392Z                  from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:3:
2019-09-10T19:36:48.4263986Z /home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl/ossl_typ.h:80:16: note: forward declaration of â€˜BIGNUM {aka struct bignum_st}â€™
2019-09-10T19:36:48.4264773Z  typedef struct bignum_st BIGNUM;
2019-09-10T19:36:48.4265202Z                 ^
2019-09-10T19:36:48.4265812Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In constructor â€˜geo::ExactFloat::ExactFloat(double)â€™:
2019-09-10T19:36:48.4266430Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:108:15: error: â€˜BN_initâ€™ was not declared in this scope
2019-09-10T19:36:48.4266782Z    BN_init(&bn_);
2019-09-10T19:36:48.4266998Z                ^
2019-09-10T19:36:48.4267538Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In constructor â€˜geo::ExactFloat::ExactFloat(int)â€™:
2019-09-10T19:36:48.4268137Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:131:15: error: â€˜BN_initâ€™ was not declared in this scope
2019-09-10T19:36:48.4269106Z    BN_init(&bn_);
2019-09-10T19:36:48.4269371Z                ^
2019-09-10T19:36:48.4269975Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In copy constructor â€˜geo::ExactFloat::ExactFloat(const geo::ExactFloat&)â€™:
2019-09-10T19:36:48.4291506Z src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:143:15: error: â€˜BN_initâ€™ was not declared in this scope
2019-09-10T19:36:48.4292354Z    BN_init(&bn_);
2019-09-10T19:36:48.4292616Z                ^
2019-09-10T19:36:48.4293178Z src/build.mk:390: recipe for target 'build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o' failed
2019-09-10T19:36:48.4293523Z make[1]: *** [build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o] Error 1
2019-09-10T19:36:48.4345792Z make[1]: *** Waiting for unfinished jobs....
2019-09-10T19:36:48.4346796Z Makefile:52: recipe for target 'make' failed
2019-09-10T19:36:48.4347110Z make: *** [make] Error 2
2019-09-10T19:36:50.3280408Z 
2019-09-10T19:36:50.3283803Z ==> Formula
2019-09-10T19:36:50.3286193Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rethinkdb.rb
```

**Comment by iMichka** [comment]
https://github.com/rethinkdb/rethinkdb/issues/6706

**Comment by iMichka** [comment]
> is RethinkDB dead?

https://github.com/rethinkdb/rethinkdb/issues/6747#issue-462418599

**Comment by iMichka** [comment]
I tried to use the recommended release from this fork:
https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1

This asked for endless dependencies (node, jemalloc, cofeescript, browserify...), and there were even more errors and issues.

As the downloads attempts are around 20 per month right now, I will not invest more time in this. The project looks somewhat dead right now.

**Comment by gabor-boros** [comment]
Hello @iMichka,
How could I help you resolve this issue instead of just closing it?

**Comment by dawidd6** [comment]
You can try to build the `rethinkdb` formulae locally in Docker container using `homebrew/brew` image and submit a PR with needed changes if you succeed.

**Comment by gabor-boros** [comment]
@dawidd6 Thank you! I'll take a note about it, and send the PR as soon as I get there. Which version of the DB should be built? I mean we have a v2.3.6 (currently out), v2.3.7 and v2.4.0 (both will be released soon).

**Comment by dawidd6** [comment]
Just grab the latest formula from this repo and hack.

**Comment by gabor-boros** [comment]
@dawidd6, I do not know what went wrong on @iMichka's side, but the proposed change `depends_on "python@2" unless OS.mac?` partially there as `depends_on "python@2" => :build unless OS.mac?`. As I can see iMichka's fork is not up-to-date with the master (?). I tried to install the formula on a fresh Ubuntu and it just works. Also tried with the proposed change (removing `=> :build`) and still works. Instead of "fixing" this "issue", I would go with updating the DB version if you do not mind.

In case I missed something or I should open a PR to remove `=> :build` please let me know.

**Comment by iMichka** [comment]
The error was not about python, it was a compilation error, see my comment: https://github.com/Homebrew/linuxbrew-core/pull/15419#issuecomment-530104704

We do not build on our local ends, but on our continuous integration, in a new docker container each time we run a build. This ensures the env is not polluted and the build is reproducible.

I can try to trigger a new build later today. But it needs to pass CI.

**Comment by gabor-boros** [comment]
Oh, now I see. Thank you for your quick response @iMichka.

Is there a way I can test it somehow which is more similar to your CI? I tried to build it with docker and it worked as well. If it still fails for you, could you please help me with some info about your dockerfile like the base image, additionally installed packages and so on?

**Comment by iMichka** [comment]
Actually I saw that we fixed the build here #17159. I missed that (there is so much activity here that I can't follow everything). If you update you should be good to go.

**Comment by iMichka** [comment]
And for the CI, we have our own docker image which can be downloaded here: https://hub.docker.com/r/homebrew/brew

This is the one used for the builds, and we try to reproduce bugs in there when needed.

**Pull request closed without merging**
