### PR TITLE
lttng-ust: add bottle block

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
The trick is to add an empty bottle  block (72007a953b8c3091ac68eeff242b93a0ac29c241) and request a bottle, and then hope everything goes well.

**Comment by danielnachun** [comment]
Good to know.  When I tried that locally, `brew audit` didn't like that and I assumed it would fail in CI, but that seems not be an issue.

**Comment by iMichka** [comment]
It will fail in CI, so you can't open any other PR or merge anything until the bottle block is filled.

**Comment by Bo98** [comment]
```
Library/Taps/homebrew/homebrew-core/Formula/lttng-ust.rb:12:3: C: [Correctable] FormulaAudit/ComponentsOrder: bottle (line 12) should be put before depends_on (line 8)
```

**Comment by iMichka** [comment]
Fixed: 4f5021fec1cce8b0f1dafe67e69098f4bb5925e3

That's when you things manually ...

**Pull request closed without merging**
