### PR TITLE
gcc@5: align with upstream, modernise

### PR DESCRIPTION
**Pull request by iMichka**
In preparation of the migration to homebrew-core

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I tried to build `gcc@5` by playing with the different flags ... and was unable to do so. It fails with weird compilation errors.

The main difference is that this formula is using "make bootstrap" and builds `isl` as a resource. Using the `isl@0.18` formula and using a plain `make` works.

Unless someone from @Homebrew/linux has an idea, I'll go for the external `isl@0.18` solution and backport that to homebrew-core.

**Comment by jonchang** [comment]
Yeah, sounds good :+1:

**Comment by iMichka** [comment]
@jonchang I thought a little bit more about this and vending works. I opened a PR in homebrew-core to get the update in there first: https://github.com/Homebrew/homebrew-core/pull/62773

**Comment by iMichka** [comment]
Brew linkage still fails:

```
Unwanted system libraries:
  /usr/lib/x86_64-linux-gnu/libisl.so.15
```

`brew linkage --reverse gcc@5` tells me:
```
/usr/lib/x86_64-linux-gnu/libisl.so.15
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1obj
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1objplus
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1plus
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/f951
  libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/lto1
```

These are still linking to the system isl, but it should be linking to the one I installed in libexec.

**Pull request closed without merging**
