### PR TITLE
komposition: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
/usr/bin/ld: warning: /home/linuxbrew/.linuxbrew/Cellar/libepoxy/1.5.3/lib/libepoxy.so, needed by /home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgtk-3.so, not found (try using -rpath or -rpath-link)
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_eglMakeCurrent'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glGetRenderbufferParameteriv'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glBindVertexArray'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glXBindTexImageEXT'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glFrameTerminatorGREMEDY'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_eglCreateContext'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_eglGetCurrentContext'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_eglDestroyContext'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgtk-3.so: undefined reference to `epoxy_glFramebufferRenderbufferEXT'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glFlush'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_is_desktop_gl'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgtk-3.so: undefined reference to `epoxy_glGenTextures'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgtk-3.so: undefined reference to `epoxy_glDeleteRenderbuffersEXT'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgtk-3.so: undefined reference to `epoxy_glBindRenderbuffer'
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.12_2/lib/libgdk-3.so: undefined reference to `epoxy_glXGetConfig'
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/18655

**Comment by dawidd6** [comment]
```
gcc-5: error: unrecognized command line option '-no-pie'
`gcc-5' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/issues/17812

**Comment by dawidd6** [comment]
```
Failed to install gi-glib-2.0.23
Build log ( /tmp/komposition-20200107-91806-nj89jo/komposition-0.2.0/.cabal-sandbox/logs/ghc-8.8.1/gi-glib-2.0.23-1LiJDalddxWCuGmdaBypRc.log ):
cabal: Entering directory '/tmp/cabal-tmp-92483/gi-glib-2.0.23'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-92483/gi-glib-2.0.23/dist/dist-sandbox-a5613834/setup/setup.hs, /tmp/cabal-tmp-92483/gi-glib-2.0.23/dist/dist-sandbox-a5613834/setup/Main.o )
Linking /tmp/cabal-tmp-92483/gi-glib-2.0.23/dist/dist-sandbox-a5613834/setup/setup ...
Did not find a GI repository for GLib-2.0 in ["/usr/local/share/gir-1.0","/usr/share/gir-1.0"].
CallStack (from HasCallStack):
  error, called at lib/Data/GI/GIR/Repository.hs:89:20 in haskell-gi-0.23.0-Bj15GldJWlELgIskn6kufP:Data.GI.GIR.Repository
cabal: Leaving directory '/tmp/cabal-tmp-92483/gi-glib-2.0.23'
Failed to install gi-cairo-1.0.23
Build log ( /tmp/komposition-20200107-91806-nj89jo/komposition-0.2.0/.cabal-sandbox/logs/ghc-8.8.1/gi-cairo-1.0.23-JEuBUpyj3DC9MCTrnVnuwX.log ):
cabal: Entering directory '/tmp/cabal-tmp-92484/gi-cairo-1.0.23'
[1 of 1] Compiling Main             ( /tmp/cabal-tmp-92484/gi-cairo-1.0.23/dist/dist-sandbox-a5613834/setup/setup.hs, /tmp/cabal-tmp-92484/gi-cairo-1.0.23/dist/dist-sandbox-a5613834/setup/Main.o )
Linking /tmp/cabal-tmp-92484/gi-cairo-1.0.23/dist/dist-sandbox-a5613834/setup/setup ...
Did not find a GI repository for cairo-1.0 in ["/usr/local/share/gir-1.0","/usr/share/gir-1.0"].
CallStack (from HasCallStack):
  error, called at lib/Data/GI/GIR/Repository.hs:89:20 in haskell-gi-0.23.0-Bj15GldJWlELgIskn6kufP:Data.GI.GIR.Repository
cabal: Leaving directory '/tmp/cabal-tmp-92484/gi-cairo-1.0.23'
cabal: Error: some packages failed to install:
gi-atk-2.0.21-D9e5QbaUDl9G7p1fEylrk depends on gi-atk-2.0.21 which failed to
install.
gi-cairo-1.0.23-JEuBUpyj3DC9MCTrnVnuwX failed during the configure step. The
exception was:
ExitFailure 1
gi-gdk-3.0.22-JgTGCDjtAu9BKsJ7Furce1 depends on gi-gdk-3.0.22 which failed to
install.
gi-gdkpixbuf-2.0.23-A3aXSIoZyGw4S8XVuqJ0u7 depends on gi-gdkpixbuf-2.0.23
which failed to install.
gi-gio-2.0.25-AoEn2baZszy82VnJBTJqDq depends on gi-gio-2.0.25 which failed to
install.
```

**Comment by issyl0** [comment]
Attempting to debug this (maybe it's related to the wider problem Homebrew/homebrew-core has surfaced with Haskell formulae - we'll see). Installing what feels like the entire world...

```
$ brew install komposition
==> Installing dependencies for komposition: leptonica, gobject-introspection, yasm, gstreamer, orc, gst-plugins-base, gst-libav, gsettings-desktop-schemas, linuxbrew/xorg/libdrm, linuxbrew/xorg/libomxil-bellagio, linuxbrew/xorg/wayland, linuxbrew/xorg/libva-internal, linuxbrew/xorg/libvdpau, linuxbrew/xorg/wayland-protocols, lm-sensors, linuxbrew/xorg/mesa, linuxbrew/xorg/glu, freeglut, libepoxy, dbus, at-spi2-core, at-spi2-atk, iso-codes, linuxbrew/xorg/xkeyboardconfig, libxkbcommon, gtk+3, libshout, glib-networking, libpsl, vala, libsoup, taglib, gst-plugins-good, mad, opusfile and sox
```

😆

**Comment by dawidd6** [comment]
The problem seems to be lying in this line:

```
Did not find a GI repository for cairo-1.0 in ["/usr/local/share/gir-1.0","/usr/share/gir-1.0"].
```

Dunno how to fix it tho.

**Comment by issyl0** [comment]
No, me neither. If a user wants to run `komposition`, they nuild from source and propose a fix! Thanks for your efforts, though.

**Pull request closed without merging**
