### PR TITLE
haskell-stack: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
optparse-applicative  > [ 8 of 16] Compiling Options.Applicative.Help.Core
safe-exceptions       > Configuring safe-exceptions-0.1.7.0...
optparse-applicative  > <command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
safe-exceptions       > build
safe-exceptions       > Preprocessing library for safe-exceptions-0.1.7.0..
safe-exceptions       > Building library for safe-exceptions-0.1.7.0..
safe-exceptions       > [1 of 1] Compiling Control.Exception.Safe
safe-exceptions       > copy/register
safe-exceptions       > Installing library in /tmp/haskell-stack-20200127-6325-1lunqzn/stack-2.1.3/.stack/snapshots/x86_64-linux/6bb38d597153a2e63d0f820520334c69d9ad730d0be6947ca0d30cbb1742b0c5/8.4.4/lib/x86_64-linux-ghc-8.4.4/safe-exceptions-0.1.7.0-CIqAp2Sa5w7DPtMChRKXk1
safe-exceptions       > Registering library for safe-exceptions-0.1.7.0..

--  While building package optparse-applicative-0.14.3.0 using:
      /tmp/haskell-stack-20200127-6325-1lunqzn/stack-2.1.3/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.2.0.1 build --ghc-options ""
    Process exited with code: ExitFailure 1
```

**Comment by zemanlx** [comment]
@dawidd6 thank you for doing this! I am not sure if it helps but I wanted to create the same PR and it was compiling just fine on my computer with `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)` so maybe this one is going to old version `gcc` in Ubuntu 16.04.

**Comment by dawidd6** [comment]
No, the problem here is:

```
libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
```

Need to somehow let the build know where to find it.

**Comment by dawidd6** [comment]
@zemanix Looks like the build went fine finally. Maybe you would like to make some functional tests?

**Comment by zemanlx** [comment]
@dawidd6 Sorry, did not have a chance to test it properly before it's got merged, but I was working for me already as my computer has `libgmp-dev` installed.

**Pull request closed without merging**
