### PR TITLE
sratoolkit: build and fix

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

@sjackman

### CODE REVIEW

**Comment by sjackman** [comment]
```
gcc -c  -std=c11  -DNDEBUG -m64   -DLINUX -DUNIX -D_GNU_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPKGNAME=linux64 -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=lib -DSHLIBEXT=so  -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/interfaces/override -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/tools/driver-tool/json/linux -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/tools/driver-tool/json/unix -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/tools/driver-tool/json -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/ -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/cc/gcc/x86_64 -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/cc/gcc -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/os/linux -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/os/unix -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ncbi-vdb-source/interfaces/ext -I/tmp/sratoolkit-20201001-18095-wv73ng/sra-tools-2.10.8/ngs-sdk-prefix/include -I. -MD -shared -o libutf8proc.so.2.2.0 -Wl,-soname -Wl,libutf8proc.so.2 utf8proc.o
gcc-5: warning: utf8proc.o: linker input file unused because linking not done
chmod: cannot access 'libutf8proc.so.2.2.0': No such file or directory
Makefile:81: recipe for target 'libutf8proc.so.2.2.0' failed
```
https://github.com/Homebrew/linuxbrew-core/pull/21162/checks?check_run_id=1192453916#step:7:1579

There's something wrong with this command, and it seems with the `Makefile`. This command line uses `gcc -c` to compile an object file, but the rest of the command line makes it clear that it's trying to link `libutf8proc.so.2.2.0`.

**Comment by sjackman** [comment]
It probably shouldn't be trying to build `libutf8proc.so.2.2.0` though if we're suppling it as a dependency.

**Comment by dawidd6** [comment]
Can't fix it. Dunno what to do with that.

**Comment by sjackman** [comment]
Thanks for trying, Dawid. I'll take a look at it when I get a chance.

**Pull request closed without merging**
