### PR TITLE
gdk-pixbuf: set install_rpath for meson to keep rpath

### PR DESCRIPTION
**Pull request by Char-Aznable**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

Temporary solution for https://github.com/Homebrew/linuxbrew-core/issues/14202

-----

### CODE REVIEW

**Comment by iMichka** [comment]
@Char-Aznable we had a similar patch back then, which then created a lot of mess and broke the build, see #11862. I had to remove that.

**Comment by Char-Aznable** [comment]
@iMichka That patch had included some very dynamic components in the regex and probably some upstream changes invalidated the regex. In any case, unless one can figure out an acceptable patch to meson itself, it's unlikely we can work around this by other means.

**Comment by iMichka** [comment]
Agreed that we need that patch. The dynamic regex did not break anything, and the change was applying correctly. But the patch resulted in the following error:
```
FAILED: tests/59830eb@@pixbuf-pixdata@exe/meson-generated_.._resources.c.o 
gcc-5 -Itests/59830eb@@pixbuf-pixdata@exe -Itests -I../tests -I. -I../ -Igdk-pixbuf -I../gdk-pixbuf -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.43/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.3/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.3/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.32.1_2/include/libmount -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.32.1_2/include/blkid -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.32.1_2/include/uuid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE -D_XOPEN_SOURCE -DHAVE_CONFIG_H=1 -pthread -Wpointer-arith -Wformat=2 -Wstrict-prototypes -Wnested-externs -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wcast-align -Wmissing-noreturn -Wmissing-format-attribute -Wlogical-op -fno-strict-aliasing -Wno-int-conversion -Wno-uninitialized -Wno-discarded-qualifiers -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=empty-body -fvisibility=hidden  -MD -MQ 'tests/59830eb@@pixbuf-pixdata@exe/meson-generated_.._resources.c.o' -MF 'tests/59830eb@@pixbuf-pixdata@exe/meson-generated_.._resources.c.o.d' -o 'tests/59830eb@@pixbuf-pixdata@exe/meson-generated_.._resources.c.o' -c tests/resources.c
gcc-5: error: tests/resources.c: No such file or directory
gcc-5: fatal error: no input files
```

Which is exactly the same than the one on CI in this PR.

**Comment by Char-Aznable** [comment]
There is an earlier error as described here: https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues/123 which looks exactly the same as the one here.

**Comment by Char-Aznable** [comment]
Seems this might be the actual cause of the errors:
```
g_module_open() failed for /tmp/gdk-pixbuf-20190716-34838-7bcuhq/gdk-pixbuf-2.38.1/build/gdk-pixbuf/libpixbufloader-png.so: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/linuxbrew/.linuxbrew/lib/libpng16.so.16)
```
I can't reproduce this on my local machine

**Comment by iMichka** [comment]
Yes, I came to the same conclusion:
https://github.com/Homebrew/linuxbrew-core/pull/11862#issuecomment-470401809

And a list of similar issues:
https://github.com/Homebrew/linuxbrew-core/pull/11862#issuecomment-473456281

Or maybe we need to rebuild one of the dependencies? Maybe try to rebuild zlib or libpng from source?

**Comment by Char-Aznable** [comment]
Could it also be meson stripping off rpath from the intermediate objects that were not protected by this patch? I am not sure if there is a global parameter to prevent meson from pruning rpath during a build

**Comment by Char-Aznable** [comment]
@iMichka Switching to meson-internal solves all these problems

**Comment by iMichka** [comment]
Thanks @Char-Aznable !

**Pull request closed without merging**
