### PR TITLE
gcc@5: force cellar: :any on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I know we don't like manually setting `cellar :any` like this, but given the importance of this formula for setting up Linuxbrew on older systems, we still need to set it.  I've looked through the strings that flag it is as non-relocatable, and I'm not sure there's a way for us to ignore those without mistakenly letting other bottles be flagged as relocatable.  If we want to fix this in `brew` itself, I think we'd have to basically just tell it to set `cellar :any` if the formula is a version of GCC.

**Comment by iMichka** [comment]
I am not in favour of the manual way.
Either we have an allow_list in brew that hardcodes this behaviour, or we have a GitHub Action that adds cellar any back each time it is removed.

Any manual action will be forgotten by the maintainers.

**Comment by danielnachun** [comment]
>we have a GitHub Action that adds cellar any back each time it is removed.

This sounds great, though I'm not clear if this is something that should be done in homebrew-github-actions, homebrew-test-bot, or brew?  I'm not exactly sure where to start as I still don't know those parts of the code base as well.

**Comment by iMichka** [comment]
It's defined in brew, in the bottle command (https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bottle.rb#L490-L501) and above. You'll have to add a linux-only / Mac-only allowlist.

There is already a ALLOWABLE_HOMEBREW_REPOSITORY_LINKS list at the top of the file.

**Comment by iMichka** [comment]
I am closing this as we won't merge this pull request. A better solution has to be found within Homebrew/brew, sorry.

**Pull request closed without merging**
