### PR TITLE
build-bottles.yml: tap xorg

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Why this change? Shouldn't xorg be tapped by test-bot?

**Comment by iMichka** [comment]
Because I can't get `vala` to build.
See https://github.com/Homebrew/linuxbrew-core/runs/534305176?check_suite_focus=true

Looks this change did not help anyway.

**Comment by dawidd6** [comment]
You've made the change in wrong workflow.

**Comment by iMichka** [comment]
I did. Reverted in #19930

**Pull request merged**
