### PR TITLE
Stoken: depends on gtk+3

### PR DESCRIPTION
**Pull request by Char-Aznable**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by Char-Aznable** [comment]
This builds fine but the bottling step failed:
```
Error: --keep-old was passed but there are changes in:
cellar: old: :any, new: "/home/linuxbrew/.linuxbrew/Cellar"
==> FAILED
```

**Comment by iMichka** [comment]
Yes, our CI setup is not really working. To make this work, you need to remove `cellar :any`.

I am wondering if we can push this change to https://github.com/Homebrew/homebrew-core first? I would like to keep both repos aligned as much as possible.

The only dependency which is really missing here is `libxml2`. The GUI seems to be optional, do you really need it?

**Comment by Char-Aznable** [comment]
IIRC, the original formula wouldn't build and complained about missing gtk+3 specifically. 

I don't have a mac to test this for now and I don't know how much it takes to make this work on mac too

**Comment by iMichka** [comment]
I have gtk3 installed on my system but stoken does not try to pick it up.

Also:
```
brew linkage stoken
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libgmp.so.10 (gmp)
  /home/linuxbrew/.linuxbrew/lib/libxml2.so.2 (libxml2)
  /home/linuxbrew/.linuxbrew/lib/libhogweed.so.4 (nettle)
  /home/linuxbrew/.linuxbrew/lib/libnettle.so.6 (nettle)
  /home/linuxbrew/.linuxbrew/lib/libstoken.so.1 (stoken)
Indirect dependencies with linkage:
  gmp
```

Could we try to just add `libxml2`. I would like to see the explicit gtk3 error to determine if it really needed. If we can avoid to pull a full GUI toolkit for a token generator, that would be great.

**Comment by Char-Aznable** [comment]
... because you were looking for the wrong binary. The stoken-gui one does depends on gtk+3.

**Comment by iMichka** [comment]
> ls /home/linuxbrew/.linuxbrew/Cellar/stoken/0.92/bin/
stoken

No stoken-gui binary gets built on my system. Even with system gtk3 and brewed gtk3 being there (but not explicitly declared as a dependency in the formula).

**Comment by Char-Aznable** [comment]
I don't want to waste me time on this any more

**Comment by iMichka** [comment]
No problem. Anybody can pick this up later. Thanks.

**Pull request closed without merging**
