### PR TITLE
cups: update test

### PR DESCRIPTION
**Pull request by jonchang**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Good luck with that one, I was never able to fix it. If it works, the best is to backport the changes to homebrew-core directly.

**Comment by jonchang** [comment]
It works locally for me so I'll probably backport the change in a bit.

**Comment by iMichka** [comment]
Cool. Yes I tried to setup avahi, and it needed a cups user on the system too. It was a huge pain so I just gave up. Thanks for finding this out!

**Comment by jonchang** [comment]
Yeah, now we just have to figure out how to build openjdk@8 for Linux :sob:

**Pull request merged**
