### PR TITLE
k9s 0.21.2 (new formula)

### PR DESCRIPTION
**Pull request by crunchtime-ali**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [X] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----
k9s is an insanely handy and popular interactive CLI to deal with Kubernetes clusters. There is an official formula available here https://github.com/derailed/homebrew-k9s/blob/master/Formula/k9s.rb but I think it should be added to the core repo for more exposure.

### CODE REVIEW

**Comment by crunchtime-ali** [comment]
I am a little bit lost with the CI errors (see below) from `Run brew test-bot --only-setup`
Can someone help me? @imichka maybe?

image

**Comment by iMichka** [comment]
The CI errors are unrelated, it's a bug in our setup. We are trying to fix it.

**Comment by crunchtime-ali** [comment]
@iMichka I am a bit confused. `k9s` was added yesterday by @chenrui333 here https://github.com/Homebrew/linuxbrew-core/commit/599982d54987562aac1d9f993e513148f57bbe7b after it was added to `homebrew-core` but the linuxbrew Formula only contains macOS bottles. Will the Linux bottle be added once the build system is working again?

Is there a tracking issue for this build system problem I can follow or maybe help with fixing?

**Comment by iMichka** [comment]
```
Linuxbrew is a fork of Homebrew. Homebrew is merged into Linuxbrew roughly once per day.
```

See https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md

I lag a little bit behind right now but the update for your formula should be in there tomorrow.

Regarding the issue, I do not have a tracking bug right now, but we are discussing this on a separate channel with other maintainers.

**Comment by chenrui333** [comment]
> Merge branch 'master' into add-k9s

we dont support `merge master to branch` operation, you need to rebase your branch to the latest master.

**Comment by crunchtime-ali** [comment]
> > Merge branch 'master' into add-k9s
> 
> we dont support `merge master to branch` operation, you need to rebase your branch to the latest master.

I did not read https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md beforehand (shame on me).
Right now I see no value in this PR at all and would like to close it. Or am I missing something here? @chenrui333

**Comment by chenrui333** [comment]
> > > Merge branch 'master' into add-k9s
> > 
> > 
> > we dont support `merge master to branch` operation, you need to rebase your branch to the latest master.
> 
> I did not read https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md beforehand (shame on me).
> Right now I see no value in this PR at all and would like to close it. Or am I missing something here? @chenrui333

Yeah, indeed, I thought your comment is in homebrew-core side, but it turns out in linuxbrew. Yeah, we dont need to do extra mile in here (it is all automated) :)

**Comment by crunchtime-ali** [comment]
@chenrui333 @iMichka I am sorry for wasting your precious time. At least it has enlightened me. I will try to make up for it with some other contributions to the projects in the future.

**Comment by iMichka** [comment]
No issue. I added a bottle for Linux meanwhile: def4b4bb827b09ce62919dffc3081c04f79aa4ce

**Pull request closed without merging**
