### PR TITLE
workflows: use actions instead of custom scripts

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

Cleaner and easier to maintain.

Might be slightly faster, because there is no need to install `unzip` anymore.

### CODE REVIEW

**Comment by jonchang** [comment]
On mobile so I’ll review this in depth later but I think we should limit ourselves to github-official actions or copy them into Homebrew/actions. Thoughts?

**Comment by dawidd6** [comment]
Might be a good idea. `action-download-artifact` could use a JavaScript rewrite tho, but I don't know this language.

**Comment by jonchang** [comment]
I'm going to coalesce all my GitHub Actions-related code for next weekend when the GitHub Actions competition starts. I'll look at porting the code over to TypeScript then. I found it actually pretty straightforward so you could give it a shot too. Happy to help either way.

**Comment by sjackman** [comment]
> On mobile so I’ll review this in depth later but I think we should limit ourselves to github-official actions or copy them into Homebrew/actions. Thoughts?

Agreed. We should limit ourselves to actions found under either `actions/` or `homebrew/`.

**Pull request closed without merging**
