### PR TITLE
newsboat: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
I get this error locally:

```
a2x -f xhtml -D doc/xhtml doc/faq.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  --output "/tmp/newsboat-20191003-4141-18rohen/newsboat-2.17.1/doc/xhtml/faq.html" "/home/linuxbrew/.linuxbrew/Cellar/asciidoc/8.6.10_4/etc/asciidoc/docbook-xsl/xhtml.xsl" "/tmp/newsboat-20191003-4141-18rohen/newsboat-2.17.1/doc/xhtml/faq.xml" returned non-zero exit status 127
```

**Comment by iMichka** [comment]
And this:
```
error: failed to download from `https://crates.io/api/v1/crates/openssl-sys/0.9.46/download`

Caused by:
  [35] SSL connect error (error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error)
make: *** [Makefile:109: target/release/libnewsboat.a] Error 101

```

**Comment by issyl0** [comment]
It needed more dependencies, at least on my local machine. Let's see if this works.

**Comment by issyl0** [comment]
It works! But now I think about it, both these can be contributed upstream to Homebrew/homebrew-core as `uses_from_macos`. I've done a PR there, so shall we wait until we've merged that in to build and pull the bottle?

**Comment by dawidd6** [comment]
I'm gonna pull this and keep in mind later doing merge to accept the upstream.

**Comment by dawidd6** [comment]
The rebuild seem to be necessary anyway, as upstream did.

**Pull request closed without merging**
