### PR TITLE
mpd: use gcc@7

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
As with previous cases, it seems when building with a newer `gcc`, we can resolve `libstdc++` issues by prepending `-L#{Formula["gcc@VERSION"].opt/lib}/gcc/VERSION` to the LDFLAGS.  

The test failure in `mpd` is similar to others I have seen fail - `localhost` doesn't work in CI like we expect it to: https://medium.com/it-dead-inside/docker-containers-and-localhost-cannot-assign-requested-address-6ac7bc0d042b.

**Comment by iMichka** [comment]
Should gcc@7 not be a runtime dependency too?

**Comment by danielnachun** [comment]
Yes.  Is adding ":test" sufficient to achieve this?

**Comment by danielnachun** [comment]
In researching for https://github.com/Homebrew/brew/pull/10606, I figured out that this and all other similar errors are happening because something in the dependency tree is installing gcc-5 in CI with `depends_on "gcc"`, which was probably added to fix something in macOS (it should never be needed in Linux).  Once `gcc` points to gcc-10, these kinds of errors will go away.  I'll close this for now until we've resolved the issues with `gcc`.

**Pull request closed without merging**
