### PR TITLE
Remove formulae migrated to "homebrew/cask" from the tap migrations list

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] ~Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [ ] ~Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [ ] ~Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~
- [ ] ~Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.~

-----

- Having them here is misleading for Linux users as casks aren't supported on non-MacOS installations and with them in this list, brew suggests installing them.
- This was suggested as an alternative approach in https://github.com/Homebrew/brew/pull/6156. If I remove the code I added there in favour of this change, the result is the same. :tada:

### CODE REVIEW

**Comment by iMichka** [comment]
The only issue I see with this is that each time a new line is added, we will get a merge conflict when merging. This also means that we need to keep the list maintained throughout time, which I can't guarantee.

I see that https://github.com/Homebrew/brew/pull/6156 is still open. That solution looks more general (also, if there are other linux taps out there, https://github.com/Homebrew/brew/pull/6156 may be a good thing).

**Comment by issyl0** [comment]
Yeah, I was concerned about you having to deal with merge conflicts too. 😕

**Comment by iMichka** [comment]
> This was suggested as an alternative approach in Homebrew/brew#6156. If I remove the code I added there in favour of this change, the result is the same. 

@issyl0 Is this still true?

**Comment by issyl0** [comment]
@iMichka Does an example of what this PR does (vs `master`) make things clearer? (I backed out the [original code I wrote to do this in Homebrew/brew](https://github.com/Homebrew/brew/pull/6156#discussion_r286707528).)
```
╭─issyl0@grus /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core ‹master› 
╰─ $ brew install keybase
Error: No available formula with the name "keybase" 
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew cask install keybase

╭─issyl0@grus /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core ‹master› 
╰─ $ git checkout remove_casks_from_linuxbrew_tap_migrations_list                                                                           
Switched to branch 'remove_casks_from_linuxbrew_tap_migrations_list'
Your branch is up-to-date with 'issyl0/remove_casks_from_linuxbrew_tap_migrations_list'.

╭─issyl0@grus /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core ‹remove_casks_from_linuxbrew_tap_migrations_list› 
╰─ $ brew install keybase                                         
Error: No available formula with the name "keybase" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by iMichka** [comment]
Thanks @issyl0 !

**Pull request merged**
