### PR TITLE
.github: Use image homebrew/ubuntu16.04:master

### PR DESCRIPTION
**Pull request by sjackman**
Use Docker image `homebrew/ubuntu16.04:master ` rather than `homebrew/brew:latest`.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

Depends on PR https://github.com/Homebrew/brew/pull/7617

### CODE REVIEW

**Comment by jonchang** [comment]
Need to login to Github Packages in order to download them.

**Comment by sjackman** [comment]
I think it may be impossible to use a Docker image hosted by GitHub Packages with GitHub Actions in the `image:` line of the YAML file, because it's not possible to login before the `image` is downloaded, which if true is truly bizarre.

**Comment by sjackman** [comment]
As far as I know it's not possible to use a Docker image hosted on GitHub Packages with GitHub Actions in the `image: …` line, because it's not possible to `docker login -u … -p $GITHUB_TOKEN` before the image is automatically downloaded, which is super weird.

I've changed `docker.pkg.github.com/homebrew/brew/ubuntu16.04` to `homebrew/ubuntu16.04:master`.

**Comment by MikeMcQuaid** [comment]
> As far as I know it's not possible to use a Docker image hosted on GitHub Packages with GitHub Actions in the `image: …` line, because it's not possible to `docker login -u … -p $GITHUB_TOKEN` before the image is automatically downloaded, which is super weird.

This seems odd. Might be worth a shout to GitHub Support about?

**Comment by sjackman** [comment]
> This seems odd. Might be worth a shout to GitHub Support about?

I believe it's a known issue.

https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888/highlight/true#M1294
https://github.community/t5/GitHub-Actions/How-to-use-Docker-image-from-GitHub-Package-Registry-in-Actions/m-p/44925/highlight/true#M5971
https://github.community/t5/GitHub-Actions/How-do-I-use-a-public-Docker-image-from-GitHub-Packages-in-my/m-p/48513/highlight/true#M7198

@ethomson Is it possible to use a Docker Image hosted on GitHub Packages in the `container: image: …` configuration of the GitHub Actions YAML file?

**Comment by ethomson** [comment]
> Is it possible to use a Docker Image hosted on GitHub Packages in the container: image: … configuration of the GitHub Actions YAML 

Not yet.  But it’s something that we’re looking at.

**Pull request merged**
