### PR TITLE
gcc@5: add missing symlinks

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I've confirmed we don't have `gcc@5` as a dependency in any formulae right now, and there's no reason it ever should be.  In theory this could still break users building formula from source which need a newer `libstdc++.so.6`, but I need to confirm this is still a problem.  

If it's still a problem, I will open a PR to prepend the `LDFLAG` for a newer GCC in `brew`, but right now I think this is more important, because any bottle which has a dependency on GCC runtime libs can't find them when using brewed `gcc@5`.  While this is not difficult for users to fix, it's confusing and inconvenient, especially for newer users.

**Comment by iMichka** [comment]
You'll need to bump the revision.

Also, would it be possible to:
- either add the same fix for all other gcc formulae? First in path would then be used?
- change the spec file to find these libraries (if it helps?)

**Comment by danielnachun** [comment]
> Also, would it be possible to:
> 
> * either add the same fix for all other gcc formulae? First in path would then be used?

The files we're symlinking mostly have the same name across GCC versions, so we can't put all of them into `$HOMEBREW_PREFIX/lib`.  For bottles built in CI with any GCC other than 5, we are using a brewed GCC to do it, which uses our custom spec file to add the RPATH for `$HOMEBREW_PREFIX/lib/gcc/VERSION`.  

> * change the spec file to find these libraries (if it helps?)

That won't help, because this is specifically addressing the scenario where the user is installing a bottle built in CI using the host GCC 5 shipped by Ubuntu.  Building formulae from source using brewed gcc-5 is fine because it uses our specs file which adds the RPATHs to the GCC runtime libs.  But when a bottle built in CI is poured it doesn't contain an RPATH for brewed GCC 5, because that's not what was used to build it.

**Comment by iMichka** [comment]
Ok, thanks for the explanation. Can you bump the revision and this should be good to go.

**Comment by danielnachun** [comment]
The revision is bumped so I'm merging now.

**Comment by iMichka** [comment]
I fixed the revision to bring it in line with our OS.mac? policy: 42321f0e824ce557f38781891765b4ff36a3cd7f
I also unbolted the formula: bae4971e3b8496ae28caa609002fd7d0fd8f34ee

I'll request a bottle build. I think you can just use the "publish and commit bottles" workflow to pull automatically do all of this.

**Comment by danielnachun** [comment]
Ah thanks, sorry for missing the `OS.mac?` part of the revision and unbottling!  I'll keep in mind the publish and commit bottles workflow for these tasks in the future.

**Pull request merged**
