### PR TITLE
osmfilter: adding zlib-dependency (again)

### PR DESCRIPTION
**Pull request by kkdd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by jonchang** [comment]
You need to keep `cellar :any` but remove the line ending with `:x86_64_linux`.

**Comment by iMichka** [comment]
The zlib dependency is already declared in that formula. So the issue is somewhere else.

**Comment by iMichka** [comment]
The actual fix should be different.

In 8f55047c5fcfe59784dbc1109bf6c7d04bf3eabc, the dependency was added. This was fine for people building from source. But no bottle was rebuilt for Linux since then, so osmconvert was never shipped.

Please change in this PR:
- remove the `depends_on "zlib" => :build unless OS.mac?` line, it is not needed, as zlib is already declared
- Add `revision 1 unless OS.mac?` just before the ` head "https://gitlab.com/osm-c-tools/osmctools.git"` line.

A new bottle will be built, which will contain osmconvert.

**Comment by kkdd** [comment]
Thank you for your suggestion to solve this situation. I will try it.

**Comment by iMichka** [comment]
Thanks @kkdd !

**Pull request merged**
