### PR TITLE
mariadb: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
> cc1plus: error: -Werror=misleading-indentation: no option -Wmisleading-indentation

I think this needs gcc6 at least.

**Comment by iMichka** [comment]
```
2019-11-01T20:15:29.7035388Z ==> /home/linuxbrew/.linuxbrew/Cellar/mariadb/10.4.6_1/bin/mysql_install_db --verbose --user=root --basedir=/home/linuxbrew/.linuxbrew/Cellar/mariadb/10.4.6_1 --datadir=/home/linuxbrew/.linuxbrew/var/mysql --tmpdir=/tmp
2019-11-01T20:15:29.7297897Z .
2019-11-01T20:15:29.7301576Z Last 150 lines from /home/vsts_azpcontainer/.cache/Homebrew/Logs/mariadb/post_install.01.mysql_install_db:
2019-11-01T20:15:29.7318883Z 2019-11-01 20:15:29 +0000
2019-11-01T20:15:29.7322822Z 
2019-11-01T20:15:29.7323309Z /home/linuxbrew/.linuxbrew/Cellar/mariadb/10.4.6_1/bin/mysql_install_db
2019-11-01T20:15:29.7324103Z --verbose
2019-11-01T20:15:29.7325025Z --user=root
2019-11-01T20:15:29.7325683Z --basedir=/home/linuxbrew/.linuxbrew/Cellar/mariadb/10.4.6_1
2019-11-01T20:15:29.7326179Z --datadir=/home/linuxbrew/.linuxbrew/var/mysql
2019-11-01T20:15:29.7326599Z --tmpdir=/tmp
2019-11-01T20:15:29.7326845Z 
2019-11-01T20:15:29.7327197Z chown: cannot access '/auth_pam_tool_dir': No such file or directory
2019-11-01T20:15:29.7327525Z Cannot change ownership of the '/auth_pam_tool_dir' directory
2019-11-01T20:15:29.7327992Z  to the 'root' user. Check that you have the necessary permissions and try again.
2019-11-01T20:15:30.0455073Z Warning: The post-install step did not complete successfully
2019-11-01T20:15:30.0501067Z You can try again using `brew postinstall mariadb`
2019-11-01T20:15:30.0501561Z ==> Failed executing:
2019-11-01T20:15:30.0502134Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1911:in `block in system'
2019-11-01T20:15:30.0502835Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1848:in `open'
2019-11-01T20:15:30.0503290Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1848:in `system'
2019-11-01T20:15:30.0508752Z /tmp/bottles/mariadb--10.4.6_1.x86_64_linux.bottle.tar.gz:120:in `post_install'
2019-11-01T20:15:30.0509325Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1010:in `block (2 levels) in run_post_install'
2019-11-01T20:15:30.0510000Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:867:in `with_logging'
2019-11-01T20:15:30.0510475Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1009:in `block in run_post_install'
2019-11-01T20:15:30.0511205Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:475:in `with_env'
2019-11-01T20:15:30.0511773Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1001:in `run_post_install'
2019-11-01T20:15:30.0512364Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/postinstall.rb:18:in `<main>'
```

**Comment by dawidd6** [comment]
Yea, I saw that, but don't really know how to get around it. Any ideas?

**Comment by iMichka** [comment]
I tried to build this locally, this also needs libxml:

```
/tmp/mariadb-20191110-98289-146i463/mariadb-10.4.10/storage/connect/libdoc.cpp:8:10: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [storage/connect/CMakeFiles/connect.dir/build.make:690: storage/connect/CMakeFiles/connect.dir/libdoc.cpp.o] Error 1
make[2]: Leaving directory '/tmp/mariadb-20191110-98289-146i463/mariadb-10.4.10'
make[1]: *** [CMakeFiles/Makefile2:1438: storage/connect/CMakeFiles/connect.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by iMichka** [comment]
Depending `linux-pam` fixes this. And please also add `libxml2`.

**Comment by dawidd6** [comment]
Still the same.

**Comment by iMichka** [comment]
:(

But now the auth_pam_tool path is correct, and not `/auth_pam_tool` anymore.

I found this: https://github.com/datacharmer/dbdeployer/pull/68

Can we try to set `--auth-root-authentication-method=normal` for the `mysql_install_db` step on Linux?

**Comment by dawidd6** [comment]
Still the same.

**Comment by dawidd6** [comment]
@iMichka any new ideas?

**Comment by iMichka** [comment]
We could pull it, but as the post install step is still broken, it's not really helping. But better than nothing.

The only thing would be to open an issue upstream.

**Pull request closed without merging**
