### PR TITLE
github actions: use linuxbrew user

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Options are documented here:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-12

See also this:
https://stackoverflow.com/questions/58955666/how-to-set-the-docker-user-in-github-actions

@jonchang @issyl0 @dawidd6 
Looks like it did not work though:
https://pipelines.actions.githubusercontent.com/uNkVeqsj19TAYb9SL5rHzheWuQqAPB1QzqI0vYAmDxP7fQuepx/_apis/pipelines/1/runs/5499/signedlogcontent/3?urlExpires=2020-02-15T15%3A06%3A41.7669150Z&urlSigningMethod=HMACV1&urlSignature=ZAGMUFQjypcbLuTIYIAn34XMzZOWlovWdxDoikOs9hc%3D

**Comment by issyl0** [comment]
Huh... the docs and what you did here seem to match, so I'm confused as to why it doesn't work.

**Comment by jonchang** [comment]
Yeah no clue. Your guess is as good as mine?

**Comment by iMichka** [comment]
It looks like it works for PR's: https://github.com/Homebrew/linuxbrew-core/pull/19646

**Comment by iMichka** [comment]
Here is what you get on a PR with this change:

```
Run actions/checkout@v2
  with:
    repository: Homebrew/linuxbrew-core
    token: ***
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
/usr/bin/docker exec  35dd66797421d58590112fe748b062ff72775e3f53220e1668dbdf8f853a9839 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: Homebrew/linuxbrew-core
Working directory is '/__w/linuxbrew-core/linuxbrew-core'
/usr/bin/git version
git version 2.25.0
Deleting the contents of '/__w/linuxbrew-core/linuxbrew-core'
/usr/bin/git init /__w/linuxbrew-core/linuxbrew-core
/__w/linuxbrew-core/linuxbrew-core/.git: Permission denied
Removed matchers: 'checkout-git'
##[error]The process '/usr/bin/git' failed with exit code 1
##[error]Node run failed with exit code 1
```

I will revert this to be able to build some stuff.

**Pull request merged**
