### PR TITLE
itk: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

Closes: #16902

### CODE REVIEW

**Comment by dawidd6** [comment]
```
CMake Error at /home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/home/linuxbrew/.linuxbrew/Cellar/mesa/19.2.1/lib/libEGL.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/17003

**Comment by dawidd6** [comment]
```
==> brew linkage --test itk
Missing libraries:
  libjawt.so
  libjvm.so
  libmawt.so
  libodbcinst.so
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libthread_db.so.1
==> FAILED
```

@iMichka any ideas where to get those from?

**Comment by dawidd6** [comment]
```
==> brew linkage --test itk
Missing libraries:
  libjawt.so
  libjvm.so
  libmawt.so
==> FAILED
```

These libraries are provided by openjdk version 7, which is not brewed and I don't really want to toy with it. So I would just pull this as is, @iMichka thoughts?

**Comment by iMichka** [comment]
Sorry I did not answer you. I think we can leave it as-is for the moment. We will improve this later.

**Pull request closed without merging**
