### PR TITLE
patchelf 0.12

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
2020-09-03T19:41:39.6320595Z [31mError:[0m No available formula with the name "/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version" 
2020-09-03T19:41:39.6321361Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:310:in `get_formula'
2020-09-03T19:41:39.6322021Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:347:in `factory'
2020-09-03T19:41:39.6322676Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:25:in `block in to_formulae'
2020-09-03T19:41:39.6323648Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:24:in `map'
2020-09-03T19:41:39.6324283Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:24:in `to_formulae'
2020-09-03T19:41:39.6324899Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/fetch.rb:59:in `fetch'
2020-09-03T19:41:39.6325496Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

**Comment by jonchang** [comment]
This suggests a bug in brew or test-bot.

**Comment by iMichka** [comment]
Looks like more debug output was added to test bot lately:

```
020-11-16T21:32:45.4085504Z [32m==>[0m [1mTesting patchelf[0m
2020-11-16T21:32:46.1281342Z [31mError:[0m patchelf: failed
2020-11-16T21:32:46.1305476Z An exception occurred within a child process:
2020-11-16T21:32:46.1306689Z   RuntimeError: cannot find child processes without `pgrep`, please install!
2020-11-16T21:32:46.1311297Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
2020-11-16T21:32:46.1329638Z [31m==>[0m [1m[31mFAILED[0m[0m
2020-11-16T21:32:46.1329941Z 
2020-11-16T21:32:46.1339435Z [34m==>[0m [1mbrew uninstall --force /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version[0m
2020-11-16T21:32:46.1345315Z brew uninstall --force /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git\ --version
2020-11-16T21:32:46.7268532Z [31mError:[0m No available formula with the name "/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version".
```

**Comment by iMichka** [comment]
I'll add pgrep to our docker container.

**Comment by iMichka** [comment]
I added some debug output to test-bot.

```
==> Running Formulae#formula!(patchelf)
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version
```

This happens at the `formula = Formulary.factory(formula_name)` line in test-bot.

Wondering where this `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/git --version` line comes from, but is definitively coming from brew not from test-bot.

**Comment by iMichka** [comment]
The workflow will be fixed by #21527

**Comment by iMichka** [comment]
Note to self: this was merged using the publish-commit-bottles workflow, by using the `--workflow=wheezy_tests.yml` flag.

**Pull request closed without merging**
