### PR TITLE
workflows: remove legacy workflows

### PR DESCRIPTION
**Pull request by iMichka**
It was a nice experiment, but it did not work out as planned ...

### CODE REVIEW

**Comment by dawidd6** [comment]
Sooo, how are we going to operate now? How to test fixes without burning our CPUs?

**Comment by issyl0** [comment]
This has conflicts and needs a rebase.

**Comment by jonchang** [comment]
Hold off on this for now, we can reuse this code for fork-merge workflows.

**Comment by jonchang** [comment]
Superseded by my 100 workflow commits.

**Pull request closed without merging**
