### PR TITLE
mysql: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
> tls_context.cc:103:1: error: expression <throw-expression> is not a constant-expression

**Comment by iMichka** [comment]
```
2019-09-16T20:30:42.6171315Z > #include <mysql/service_rules_table.h>
2019-09-16T20:30:42.6171541Z > #include <string>
2019-09-16T20:30:42.6171745Z CMake Error at cmake/do_abi_check.cmake:86 (MESSAGE):
2019-09-16T20:30:42.6171975Z   ABI check found difference between
2019-09-16T20:30:42.6172809Z   /tmp/mysql-20190916-8860-49mycp/mysql-8.0.17/include/mysql/services.h.pp
2019-09-16T20:30:42.6173369Z   and /tmp/mysql-20190916-8860-49mycp/mysql-8.0.17/abi_check.out
2019-09-16T20:30:42.6173850Z 
2019-09-16T20:30:42.6174089Z 
2019-09-16T20:30:42.6174612Z CMakeFiles/abi_check.dir/build.make:60: recipe for target 'CMakeFiles/abi_check' failed
```

**Comment by iMichka** [comment]
Interesting patch. I am not sure I understand what it does, but it fixed it. Looks like our `cc/cxx` shim interferes with the build process (as the nix shim also does)?

Glad you found a solution.

The test is failing though:
```
2019-10-10T18:23:33.5631455Z 2019-10-10T18:23:33.558427Z 0 [System] [MY-010116] [Server] /home/linuxbrew/.linuxbrew/Cellar/mysql/8.0.17_1/bin/mysqld (mysqld 8.0.17) starting as process 54536
2019-10-10T18:23:33.5632803Z 2019-10-10T18:23:33.562189Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2019-10-10T18:23:33.5639507Z 2019-10-10T18:23:33.562252Z 0 [ERROR] [MY-010119] [Server] Aborting
2019-10-10T18:23:33.5640889Z 2019-10-10T18:23:33.562525Z 0 [System] [MY-010910] [Server] /home/linuxbrew/.linuxbrew/Cellar/mysql/8.0.17_1/bin/mysqld: Shutdown complete (mysqld 8.0.17)  Homebrew.
```

**Comment by dawidd6** [comment]
Adding `--user=#{ENV["USER"]}` to second invocation of mysqld might help.

**Comment by iMichka** [comment]
I think it's the first call which already fails. I'll try to see what needs to be done locally.

**Comment by sjackman** [comment]
Is this PR good to be merged?
See https://discourse.brew.sh/t/installing-mysql-error/6109

**Comment by iMichka** [comment]
I gave up on fixing the test. But it should be OK now.

**Pull request closed without merging**
