### PR TITLE
grpc: Fix build for Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
https://github.com/grpc/grpc/issues/25118

**Comment by dawidd6** [comment]
Testing building abseil as a module.

**Comment by dawidd6** [comment]
Build succeeded with bundled abseil, but linking failed because it wants to install it into prefix too.

**Comment by dawidd6** [comment]
I think the problem might be with our abseil formula. We want to build it with c++17 standard with gcc-5 which does not support this standard.

**Comment by iMichka** [comment]
Superseded by #22197

**Pull request closed without merging**
