### PR TITLE
pulumi: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
Same error (fixed): https://github.com/jesseduffield/lazydocker/pull/163

**Comment by iMichka** [comment]
```
go install -ldflags "-X github.com/pulumi/pulumi/pkg/version.Version=v1.0.0+dirty" github.com/pulumi/pulumi
# golang.org/x/xerrors
../../../../pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/adaptor_go1_13.go:16:14: undefined: errors.Frame
../../../../pkg/mod/golang.org/x/xerrors@v0.0.0-20190410155217-1f06c39b4373/format_go1_13.go:12:18: undefined: errors.Formatter
Makefile:22: recipe for target 'dist' failed
make: *** [dist] Error 2
```

**Comment by dawidd6** [comment]
https://github.com/pulumi/pulumi/pull/3188

**Comment by iMichka** [comment]
I'll wait a little bit until the patch is merged. We will then add it to homebrew-core.

This is an issue when build dependencies are bumped: we do not rebuild everything, because we do not have the computing resources to do so.

**Comment by dawidd6** [comment]
Fixed in: https://github.com/Homebrew/homebrew-core/commit/c0e2317b02142eb33e81e2efb0d5d90727b72e0d

**Pull request closed without merging**
