### PR TITLE
ncview: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
Blocked by #14556

**Comment by issyl0** [comment]
“Bottle already published”. Did you do this separately, @iMichka?

**Comment by iMichka** [comment]
2.1.7_10 was published 6 months ago. I did not do anything regarding the bottle.
Maybe there was a mistake done in 164a5ea00766ee4afa093a762eda1181e318a1f1 ?

It should probably be: `revision OS.mac? ? 10 : 11`

**Comment by issyl0** [comment]
Thanks, this was my mistake!

**Pull request closed without merging**
