### PR TITLE
php: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module
==> FAILED
```

**Comment by eduardoturconi** [comment]
The line with `--with-os-sdkpath=#{MacOS.sdk_path_if_needed}` should be changed as well, I think. At least, when removed that, I didn't get the error `undefined method 'sdk_path_if_needed' `

**Comment by dawidd6** [comment]
```
checking whether to enable the SQLite3 extension... yes
checking for sqlite3 > 3.7.4... yes
checking for sqlite3_stmt_readonly in -lsqlite3... no
configure: error: Please install SQLite 3.7.4 first or check libsqlite3 is present
```

**Comment by iMichka** [comment]
I merged this by mistake, follow up PR opened at #17963

**Pull request closed without merging**
