### PR TITLE
crystal: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
I kicked the Lambda to make the bottle appear in [the releases](https://github.com/LinuxbrewTestBot/homebrew-core/releases?after=pr-13540), but it still hasn't.

**Comment by iMichka** [comment]
This one is a little bit special.

At one point, we introduced these `CIRequirement` lines, to disable bottle building, because of the 4Gb memory limit of circle-ci. Looks like this build worked, I removed the requirement. Anyway, I think we can remove all these `CIRequirement` lines, as with the azure build I can trigger a bottle upload manually right now.

**Comment by issyl0** [comment]
Are we able to remove all the CIRequirement lines for CircleCI for [every formula that has them](https://github.com/Homebrew/linuxbrew-core/search?q=CIRCLECI%22%5D.nil%3F&unscoped_q=CIRCLECI%22%5D.nil%3F), given Azure now exists?

**Comment by iMichka** [comment]
Yes, we can try to remove all of these, one by one, and have a look at the azure build.

**Pull request closed without merging**
