### PR TITLE
apt (new formula)

### PR DESCRIPTION
**Pull request by iMichka**
@issyl0 @sjackman 

Quick and dirty hack to try to get apt to build ...

Right now I am stuck at building the `po4a` resource ... this fails with:

```
==> Verifying 3d9d5fe4074f9ae8482e6b86dddba1ebe85cde358bc6ffaa5a9c8e1983073457--po4a-0.56.tar.gz checksum
tar xof /root/.cache/Homebrew/downloads/3d9d5fe4074f9ae8482e6b86dddba1ebe85cde358bc6ffaa5a9c8e1983073457--po4a-0.56.tar.gz -C /tmp/d20190903-34315-7uclli
cp -pR /tmp/d20190903-34315-7uclli/po4a-0.56/. /tmp/apt--po4a-20190903-34315-pykxks/po4a-0.56
chmod -Rf +w /tmp/d20190903-34315-7uclli
==> perl Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'po4a' version '0.56'
==> ./Build
Created META.yml and META.json
 (1361 entries)
Error: failed to execute 'msgmerge -U po/pod/ca.po po/pod/po4a-pod.pot  --previous --backup=none': No such file or directory.
Died at Po4aBuilder.pm line 161.
```

### CODE REVIEW

**Comment by dawidd6** [comment]
Maybe `gettext` is needed at build time. Seems like `msgmerge` should be a part of this package.

**Comment by dawidd6** [comment]
It seems to build fine one my machine after making those changes to formula:

```diff
--- apt.orig.rb	2019-09-04 13:18:40.405081831 +0200
+++ apt.rb	2019-09-04 13:13:51.676896341 +0200
@@ -10,6 +10,10 @@
   depends_on "cmake" => :build
   depends_on "docbook-xsl" => :build
   depends_on "doxygen" => :build
+  depends_on "libxslt" => :build
+  depends_on "perl" => :build
+  depends_on "w3m" => :build
+  depends_on "dpkg" => :build
   depends_on "docbook"
   depends_on "gnutls"
   depends_on "berkeley-db"
@@ -67,12 +71,18 @@
     sha256 "d95636906bf71d9ce5131f57045b84c46ae33417346e2437a90013ee01e7d04f"
   end
 
+  resource "triehash" do
+    url "https://github.com/julian-klode/triehash/archive/v0.3.tar.gz"
+    sha256 "289a0966c02c2008cd263d3913a8e3c84c97b8ded3e08373d63a382c71d2199c"
+  end
+
   def install
     # Find our docbook catalog
     ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"
     
     ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5"
     ENV.prepend_path "PERL5LIB", libexec/"lib"
+    ENV.prepend_path "PATH", bin
 
     (buildpath/"gtest").install resource("gtest")
 
@@ -88,12 +98,6 @@
       system "make", "install"
     end
 
-    resource("Locale::gettext").stage do                
-      system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
-      system "make"
-      system "make", "install"
-    end
-
     resource("Term::ReadKey").stage do                
       system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
       system "make"
@@ -113,6 +117,7 @@
     end
 
     resource("SGMLS").stage do                
+      system "chmod", "-v", "644", "MYMETA.yml"
       system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
       system "make"
       system "make", "install"
@@ -136,16 +141,23 @@
       system "./Build", "install"
     end
 
-    system "cmake", ".",
-           "-DDOCBOOK_XSL=#{Formula["docbook-xsl"].opt_prefix}/docbook-xsl",
-           "-DBERKELEY_DB_INCLUDE_DIRS=#{Formula["berkeley-db"].opt_include}",
-           "-DGTEST_ROOT=gtest/googletest",
-           *std_cmake_args
-    system "make", "install"
-
-    # Install the development files too
-    include.install apt-inst
-    include.install apt-pkg
+    resource("triehash").stage do
+      bin.install "triehash.pl" => "triehash"
+    end
+
+    mkdir "build" do
+      system "cmake", "..",
+             "-DDPKG_DATADIR=#{Formula["dpkg"].opt_libexec}/share/dpkg",
+             "-DDOCBOOK_XSL=#{Formula["docbook-xsl"].opt_prefix}/docbook-xsl",
+             "-DBERKELEY_DB_INCLUDE_DIRS=#{Formula["berkeley-db"].opt_include}",
+             "-DGTEST_ROOT=gtest/googletest",
+             *std_cmake_args
+      system "make", "install"
+
+      # Install the development files too
+      #include.install apt-inst
+      #include.install apt-pkg
+   end
   end
 
   test do
```

**Comment by iMichka** [comment]
Hey! Cool, thanks! I was able to build it too with these changes.

Still some audits to fix on my side:
```
2019-09-04T19:19:33.8490503Z Error: 17 problems in 1 formula detected
2019-09-04T19:19:33.8559130Z apt:
2019-09-04T19:19:33.8574486Z   * C: 4: col 3: FormulaAudit/Urls: Please use https://deb.debian.org/debian/ for https://mirrors.ocf.berkeley.edu/debian/pool/main/a/apt/apt_1.9.3.tar.xz
2019-09-04T19:19:33.8575480Z   * C: 5: col 3: FormulaAudit/Urls: Please use https://deb.debian.org/debian/ for https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/a/apt/apt_1.9.3.tar.xz
2019-09-04T19:19:33.8576058Z   * C: 16: col 3: FormulaAudit/DependencyOrder: dependency "dpkg" (line 16) should be put before dependency "w3m" (line 15)
2019-09-04T19:19:33.8576539Z   * C: 19: col 3: FormulaAudit/DependencyOrder: dependency "gettext" (line 19) should be put before dependency "gnutls" (line 18)
2019-09-04T19:19:33.8578379Z   * C: 20: col 3: FormulaAudit/DependencyOrder: dependency "berkeley-db" (line 20) should be put before dependency "gnutls" (line 18)
2019-09-04T19:19:33.8580024Z   * C: 23: col 3: FormulaAudit/DependencyOrder: dependency "bzip2" (line 23) should be put before dependency "zlib" (line 22)
2019-09-04T19:19:33.8582647Z   * C: 30: col 22: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8583827Z   * C: 83: col 1: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8584337Z   * C: 90: col 43: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8584825Z   * C: 96: col 41: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8585302Z   * C: 102: col 39: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8585774Z   * C: 108: col 40: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8587260Z   * C: 114: col 36: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8588357Z   * C: 121: col 15: FormulaAudit/Miscellaneous: Use the `chmod` Ruby method instead of `system "chmod", "-v", "644", "MYMETA.yml"`
2019-09-04T19:19:33.8589117Z   * C: 127: col 39: Layout/TrailingWhitespace: Trailing whitespace detected.
2019-09-04T19:19:33.8589641Z   * The URL https://anonscm.debian.org/git/apt/apt.git is not reachable (HTTP status code 404)
2019-09-04T19:19:33.8590080Z   * HEAD: The URL https://anonscm.debian.org/git/apt/apt.git is not a valid git URL
```

We also still have one build failure on the CI:
```
2019-09-04T19:18:03.2863947Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5  -DNDEBUG   CMakeFiles/copy.dir/copy.cc.o  -o copy -Wl,-rpath,/tmp/apt-20190904-27312-ek12wk/apt-1.9.3/build/apt-pkg: ../apt-pkg/libapt-pkg.so.5.90.0 
2019-09-04T19:18:03.2865031Z /usr/bin/ld: copy: hidden symbol `__cpu_indicator_init' in /usr/lib/gcc/x86_64-linux-gnu/5/libgcc.a(cpuinfo.o) is referenced by DSO
2019-09-04T19:18:03.2865263Z /usr/bin/ld: final link failed: Bad value
2019-09-04T19:18:03.2865441Z collect2: error: ld returned 1 exit status
2019-09-04T19:18:03.2865853Z methods/CMakeFiles/copy.dir/build.make:87: recipe for target 'methods/copy' failed
2019-09-04T19:18:03.2866054Z make[2]: *** [methods/copy] Error 1
2019-09-04T19:18:03.2866427Z make[2]: Leaving directory '/tmp/apt-20190904-27312-ek12wk/apt-1.9.3/build'
2019-09-04T19:18:03.2866872Z CMakeFiles/Makefile2:1094: recipe for target 'methods/CMakeFiles/copy.dir/all' failed
2019-09-04T19:18:03.2867271Z make[1]: *** [methods/CMakeFiles/copy.dir/all] Error 2
2019-09-04T19:18:03.2867470Z make[1]: *** Waiting for unfinished jobs....
2019-09-04T19:18:03.2868021Z [ 92%] Building CXX object apt-private/CMakeFiles/apt-private.dir/private-cacheset.cc.o
2019-09-04T19:18:03.2868917Z cd /tmp/apt-20190904-27312-ek12wk/apt-1.9.3/build/apt-private && 
```

**Comment by dawidd6** [comment]
Great!
I could fix those audit warnings tomorrow easily if you want some help.
Dunno about this error on CI. Maybe something about different `gcc` versions?

**Comment by dawidd6** [comment]
Wow, it works. So what was wrong @iMichka ?

**Comment by iMichka** [comment]
> Wow, it works. So what was wrong @iMichka ?

I saw somewhere that this issue was maybe related to c++11, or had something to do with PIE, and this is sometimes handled weirdly with gcc5. So I tried with gcc 6 and it worked.

**Comment by iMichka** [comment]
The test is failing on CI:
```
019-09-07T11:40:12.7620168Z ==> /home/linuxbrew/.linuxbrew/Cellar/apt/1.9.3/bin/apt --version
2019-09-07T11:40:12.7703497Z W: Unable to read /home/linuxbrew/.linuxbrew/Cellar/apt/1.9.3/etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
2019-09-07T11:40:12.7706098Z E: Error reading the CPU table
2019-09-07T11:40:12.7788156Z Error: apt: failed
2019-09-07T11:40:12.7907719Z An exception occurred within a child process:
2019-09-07T11:40:12.7907984Z   Test::Unit::AssertionFailedError: <0> expected but was
2019-09-07T11:40:12.7908107Z <100>.
```

**Comment by dawidd6** [comment]
https://stackoverflow.com/questions/47417666/q-e-error-reading-the-cpu-table-in-ubuntu

Maybe depend on dpkg at runtime, not only build.

**Pull request closed without merging**
