### PR TITLE
libsoup: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
Comment in formula says:
> # if this test start failing, the problem might very well be in glib-networking instead of libsoup

**Comment by iMichka** [comment]
I tested this locally and it works.

I'll test in a new "clean" container ...

**Comment by dawidd6** [comment]
Still the same.

**Comment by iMichka** [comment]
Found it: msg->reason_phrase returns: Unacceptable TLS certificate

I then installed openssl from linuxbrew, and it worked. It looks like it does not find the certificates installed by `openssl@1.1` (which is keg-only) ...

**Pull request closed without merging**
