### PR TITLE
dog: fix dependencies

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

Fixes https://github.com/ogham/dog/issues/22

### CODE REVIEW

**Comment by vladimyr** [comment]
Am I missing a revision bump (`revision 1 unless OS.mac?`) here? 🤔

**Comment by gromgit** [comment]
Yes. As a rule of thumb, revision bumps are needed if you want to build and distribute new bottles.

**Comment by jonchang** [comment]
Thanks @vladimyr. Merging

**Comment by vladimyr** [comment]
@jonchang Huh I should have probably convert it to draft because, as @gromgit explained, I'm missing a revision bump. Thanks anyway, new PR is on the way 🙃

**Comment by jonchang** [comment]
Revision bump isn't needed since we didn't have Linux bottles for this formula yet.

**Comment by vladimyr** [comment]
Oh, that's right!
Sorry about asking beginner level questions and missing on the important stuff, I'm still warming up in the linuxbrew world 🙃

**Comment by gromgit** [comment]
Whoops, sorry, didn't notice that the original formula wasn't building successfully. Must avoid posting during lunch coma. :stuck_out_tongue_closed_eyes:

**Pull request merged**
