### PR TITLE
libsoup: set install_rpath for meson to keep rpath

### PR DESCRIPTION
**Pull request by Char-Aznable**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

Temporary solution for https://github.com/Homebrew/linuxbrew-core/issues/14202

-----

### CODE REVIEW

**Comment by Char-Aznable** [comment]
Bottling failed because gtk+3 can't be built:
```
==> Installing geocode-glib dependency: gtk+3
==> Downloading https://download.gnome.org/sources/gtk+/3.24/gtk+-3.24.10.tar.xz
==> Downloading from https://mirror.umd.edu/gnome/sources/gtk+/3.24/gtk+-3.24.10.tar.xz
/usr/bin/curl -q --show-error --user-agent Linuxbrew/2.1.7-12-g74920d9\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.6\ LTS\)\ curl/7.47.0 --fail --silent --location --remote-time --continue-at 0 --output /root/.cache/Homebrew/downloads/36c3e83c9911abee8de48fefe0ee45f4bdde3199c5f843bb4fbb22f32d2266f0--gtk\ -3.24.10.tar.xz.incomplete https://mirror.umd.edu/gnome/sources/gtk\+/3.24/gtk\+-3.24.10.tar.xz
==> Verifying 36c3e83c9911abee8de48fefe0ee45f4bdde3199c5f843bb4fbb22f32d2266f0--gtk -3.24.10.tar.xz checksum
tar xof /root/.cache/Homebrew/downloads/36c3e83c9911abee8de48fefe0ee45f4bdde3199c5f843bb4fbb22f32d2266f0--gtk\ -3.24.10.tar.xz -C /tmp/d20190712-24146-w5tf8v
cp -pR /tmp/d20190712-24146-w5tf8v/gtk\+-3.24.10/. /tmp/gtk\+3-20190712-24146-1qnw243/gtk\+-3.24.10
chmod -Rf +w /tmp/d20190712-24146-w5tf8v
==> Patching
patching file libgail-util/meson.build
patching file meson.build
==> meson --prefix=/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.10 -Dx11_backend=false -Dquartz_backend=true -Dgtk_doc=false -Dman=true -Dintrospection=true ..
.
Last 150 lines from /root/.cache/Homebrew/Logs/gtk+3/01.meson:
2019-07-12 19:20:48 +0000

meson
--prefix=/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.10
-Dx11_backend=false
-Dquartz_backend=true
-Dgtk_doc=false
-Dman=true
-Dintrospection=true
..

The Meson build system
Version: 0.51.0
Source dir: /tmp/gtk+3-20190712-24146-1qnw243/gtk+-3.24.10
Build dir: /tmp/gtk+3-20190712-24146-1qnw243/gtk+-3.24.10/build
Build type: native build
Project name: gtk+-3.0
Project version: 3.24.10
C compiler for the build machine: gcc-5 (gcc 5.4.0 "gcc-5 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609")
C compiler for the host machine: gcc-5 (gcc 5.4.0 "gcc-5 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Has header "crt/externs.h" : NO 
Has header "dlfcn.h" : YES 
Has header "ftw.h" : YES 
Has header "inttypes.h" : YES 
Has header "linux/memfd.h" : YES 
Has header "linux/input.h" : YES 
Has header "dev/evdev/input.h" : NO 
Has header "locale.h" : YES 
Has header "memory.h" : YES 
Has header "stdint.h" : YES 
Has header "stdlib.h" : YES 
Has header "string.h" : YES 
Has header "strings.h" : YES 
Has header "sys/mman.h" : YES 
Has header "sys/param.h" : YES 
Has header "sys/stat.h" : YES 
Has header "sys/sysinfo.h" : YES 
Has header "sys/systeminfo.h" : NO 
Has header "sys/time.h" : YES 
Has header "sys/types.h" : YES 
Has header "unistd.h" : YES 
Library m found: YES
Checking for function "dcgettext" with dependency -lm: YES 
Checking for function "getpagesize" with dependency -lm: YES 
Checking for function "getresuid" with dependency -lm: YES 
Checking for function "lstat" with dependency -lm: YES 
Checking for function "mmap" with dependency -lm: YES 
Checking for function "nearbyint" with dependency -lm: YES 
Checking for function "posix_fallocate" with dependency -lm: YES 
Checking for function "_lock_file" with dependency -lm: NO 
Checking for function "flockfile" with dependency -lm: YES 
Checking for function "mkstemp" with dependency -lm: YES 
Checking for function "mallinfo" with dependency -lm: YES 
Checking for function "round" with dependency -lm: YES 
Checking for function "rint" with dependency -lm: YES 
Checking for function "log2" with dependency -lm: YES 
Checking for function "exp2" with dependency -lm: YES 
Checking for function "sincos" with dependency -lm: YES 
Checking for function "trunc" with dependency -lm: YES 
Checking for function "localtime_r" with dependency -lm: YES 
Header <math.h> has symbol "isinf" : YES 
Header <math.h> has symbol "isnan" : YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wimplicit-function-declaration: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers -Wdiscarded-qualifiers: YES 
Compiler for C supports arguments -Werror=implicit: YES 
Compiler for C supports arguments -Werror=nonnull: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=main: YES 
Compiler for C supports arguments -Werror=missing-braces: YES 
Compiler for C supports arguments -Werror=sequence-point: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=trigraphs: YES 
Compiler for C supports arguments -Werror=array-bounds: YES 
Compiler for C supports arguments -Werror=write-strings: YES 
Compiler for C supports arguments -Werror=address: YES 
Compiler for C supports arguments -Werror=int-to-pointer-cast: YES 
Compiler for C supports arguments -Werror=pointer-to-int-cast: YES 
Compiler for C supports arguments -Werror=empty-body: YES 
Compiler for C supports arguments -Werror=write-strings: YES (cached)
Checking if "-Wl,-Bsymbolic" links: YES 
Checking if "-Wl,-z,relro" links: YES 
Checking if "-Wl,-z,now" links: YES 
Found pkg-config: /home/linuxbrew/.linuxbrew/opt/pkg-config/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.60.5
Run-time dependency gobject-2.0 found: YES 2.60.5
Run-time dependency gio-unix-2.0 found: YES 2.60.5
Run-time dependency gmodule-2.0 found: YES 2.60.5
Run-time dependency cairo found: YES 1.16.0
Run-time dependency cairo-gobject found: YES 1.16.0
Run-time dependency pango found: YES 1.42.4
Run-time dependency fribidi found: YES 1.0.5
Run-time dependency pangoft2 found: YES 1.42.4
Run-time dependency freetype2 found: YES 23.1.17
Run-time dependency pangocairo found: YES 1.42.4
Run-time dependency gdk-pixbuf-2.0 found: YES 2.38.1
Run-time dependency epoxy found: YES 1.5.3
Run-time dependency atk found: YES 2.32.0
Run-time dependency harfbuzz found: YES 2.5.3
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xkbcommon found: NO (tried pkgconfig)

meson.build:453:0: ERROR: Dependency "xkbcommon" not found, tried pkgconfig

A full log can be found at /tmp/gtk+3-20190712-24146-1qnw243/gtk+-3.24.10/build/meson-logs/meson-log.txt

```

**Comment by iMichka** [comment]
Yes. I am currently working on this and I made good progress: #13704.
Still struggling with some weird dbus linking errors ...

**Comment by iMichka** [comment]
FYI I fixed gtk3+ (#13704).

**Comment by Char-Aznable** [comment]
@iMichka This works now. We can consider switching to meson-internal when it's more up-to-date

**Comment by iMichka** [comment]
> meson-internal currently doesn't work for #14203 because it's a few revision behind (0.46 vs 0.48) what is required by libsoup.

I would like to update the version then, so that we can use it.

Looking at the patch proposed upstream in https://github.com/mesonbuild/meson/pull/2577 (which was for mac), they tell us that this has been fixed differently by https://github.com/mesonbuild/meson/pull/3691.

I need to read through all these issues. If upstream says it is fixed, I do not understand why version 0.51.1 would not work, and we still have an old meson-internal version on mac ...

**Comment by iMichka** [comment]
Superseded by #16054. This should be fixed now.

**Pull request closed without merging**
