### PR TITLE
grib-api: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
```
CMake Error at cmake/ecbuild_add_library.cmake:270 (add_library):
  Target "grib_api" links to item " -L/home/linuxbrew/.linuxbrew/lib
  -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm" which has leading or
  trailing whitespace.  This is now an error according to policy CMP0004.
Call Stack (most recent call first):
  cmake/ecbuild_add_library.cmake:578 (ecbuild_add_library_impl)
  src/CMakeLists.txt:346 (ecbuild_add_library)
```

👀

**Comment by issyl0** [comment]
Hmmm, builds fine for me locally...

**Comment by issyl0** [comment]
Ah, I see that this still has a Linux bottle line. So it can't have been a conflict. I hunted upstream and it was a deletion: https://github.com/Homebrew/linuxbrew-core/pull/17458/commits/a1e5753b835b6c16bace70f87b58bcc82bda302f.

**Comment by iMichka** [comment]
Yes I made a mistake and opened a PR for this one. Sorry.

**Pull request closed without merging**
