### PR TITLE
boost: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
cc @lcoombe

**Comment by sjackman** [comment]
@imichka Any thoughts on this CI failure? Can the number of concurrent processes be reduced?

**Comment by iMichka** [comment]
This one can only be built locally.

**Comment by sjackman** [comment]
Thanks for bottling, Michka!
@lcoombe `boost` is bottled.

**Pull request closed without merging**
