### PR TITLE
gcc@10: Fix build for Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
Adding `libgcc` to the RPATH didn't appear to fix anything.  I'll have to check locall if the problem is actually with the `gfortran` binary or something else.

**Comment by danielnachun** [comment]
I got this to work!  There was an issue with `suffix_version` needing to be declared as a separate method (which I took from the `gcc` formula).  As for the original test failure, it turned out that none of the test binaries were actually linking to the `gcc-10` libs.  The only reason the C++ and C tests passed was because the sonames of the other libraries are the same as the system `gcc-5` libs, while they are not for `libgfortran`.  

I will try to see if both the RPATH and and LDFLAGS are needed.  This may just be an artifact of the way we are building our test binaries, or it may actually reflect a deeper issue with how we built GCC.

**Comment by magneticflux-** [comment]
I just tried this patch and it seems to be working fine on my machine (WSL 2 Pengwin/Debian):
```
 /h/l/.l/H/L/T/h/homebrew-core > master > curl "https://patch-diff.githubusercontent.com/raw/Homebrew/linuxbrew-core/pull/23212.patch" | git apply

 ~ > brew upgrade gcc@10
==> Upgrading 1 outdated package:
gcc@10 10.2.0_1 -> 10.3.0
==> Upgrading gcc@10 10.2.0_1 -> 10.3.0
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-10.3.0/gcc-10.3.0.tar.xz
Already downloaded: /home/mitchell/.cache/Homebrew/downloads/2cb384f09c41ad776914cfab9abe9acc934d02927b12e24dc9bf7e3c9223b10d--gcc-10.3.0.tar.xz
==> ../configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.3.0 --libdir=/home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.3.0/lib/gcc/10 --disable-nls --enable-checking=release --enable-languages=c,c++,objc
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
==> make install
==> Creating the GCC specs file: /home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.3.0/lib/gcc/10/gcc/x86_64-pc-linux-gnu/10.3.0/specs
🍺  /home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.3.0: 1,503 files, 2.0GB, built in 10 minutes 47 seconds
Removing: /home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.2.0.reinstall... (1,485 files, 264.5MB)
Removing: /home/linuxbrew/.linuxbrew/Cellar/gcc@10/10.2.0_1... (1,487 files, 264.3MB)
Removing: /home/mitchell/.cache/Homebrew/gcc@10--10.2.0_1.x86_64_linux.bottle.tar.gz... (88.0MB)
Removing: /home/mitchell/.cache/Homebrew/gcc@10--10.2.0.x86_64_linux.bottle.tar.gz... (88.0MB)
Removing: /home/mitchell/.cache/Homebrew/gcc@10--10.2.0.tar.xz... (71.5MB)
```

**Comment by danielnachun** [comment]
@iMichka I guess this does work without modifying the tests.  I think this is ready to merge.   Does it need a version bump?

**Comment by iMichka** [comment]
I triggered a bottle pull and merge, no need to rev bump; there was no bottle here previously.

**Pull request closed without merging**
