### PR TITLE
mkvtoolnix: Build with gcc

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
2021-04-10T21:07:35.4528074Z           LINK src/mkvpropedit
2021-04-10T21:07:35.4529601Z /home/linuxbrew/.linuxbrew/bin/ld: src/propedit/libmtxpropedit.a(attachment_target.o): in function `attachment_target_c::matches_by_uid_name_or_mime_type(libmatroska::KaxAttached&)':
2021-04-10T21:07:35.4531369Z attachment_target.cpp:(.text+0x45b7): undefined reference to `libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&() const'
2021-04-10T21:07:35.4532283Z collect2: error: ld returned 1 exit status
```

**Comment by iMichka** [comment]
`libebml` does build with gcc 5, and `mkvtoolnix` does not. `mkvtoolnix` needs to build against a `libebml` built with gcc (see the error above). This means the whole stack needs to be compiled with gcc. @Homebrew/linux thoughts?

**Comment by dawidd6** [comment]
I'm ok with this. `libebml` seems to be almost exclusively used by `mkvtoolnix`.

**Comment by danielnachun** [comment]
Gentoo also had to do this for `libebml`: https://forums.gentoo.org/viewtopic-t-1077132-start-0.html.  Also relevant: https://gitlab.com/mbunkus/mkvtoolnix/-/issues/1987.

**Pull request closed without merging**
