### PR TITLE
crystal: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
Let's try this again on Azure...

**Comment by iMichka** [comment]
> tmp/crystal-20190810-32591-1w7gk7j/crystal-0.30.0/bin/crystal build -o /tmp/crystal-20190810-32591-1w7gk7j/crystal-0.30.0/.build/shards src/shards.cr

This look more than 6 hours and did not complete.

**Comment by iMichka** [comment]
We are hitting this issue:
https://github.com/crystal-lang/crystal/issues/8044

We should be able to compile with `--threads=1`. Can you add this to the `system "bin/crystal", "build",` step?

**Comment by issyl0** [comment]
Building this locally with `--threads=1`, I'm not convinced it's any faster. It's still taking _forever_ at the shards step.

**Comment by issyl0** [comment]
As soon as I typed that it finished. :roll_eyes: Pushed the `--threads=1` fix.

**Pull request closed without merging**
