### PR TITLE
snapcraft: Fix build for Linux

### LINKED ISSUE #14107: snapcraft: error during installation
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to install `snapcraft` package via `brew` in official Docker `linuxbrew/brew` image.

1. Pull `linuxbrew/brew` Docker image and run it.
2. Execute `brew install snapcraft`
3. Observe getting this output and error at the end:
```
root@fde41254f50b:/home/linuxbrew# brew install snapcraft
==> Downloading https://files.pythonhosted.org/packages/ff/9c/07776f4f192a3bb454221ef00cc865fbbbd5d5285d134b36b6aa1890d91d/snapcraft-3.3.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/287800da8f61ad73d39d0e079ce88b0dc2a54ef548c7344acfd963fa60db224d--snapcraft-3.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/37/27/706af3ee62032933a3217454609c50a5325a6bd9c2c2f495b58c456ba286/virtualenv-16.6.1.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/3c930834dac51edb05b7f34f88664cf348741680c6b1d860dc7ddc084d5b17eb--virtualenv-16.6.1.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/snapcraft--homebrew-virtualenv-20190704-30398-k2kz5o/target --install-scripts=/tmp/snapcraft--ho
==> python3 -s /tmp/snapcraft--homebrew-virtualenv-20190704-30398-k2kz5o/target/bin/virtualenv -p python3 /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec
==> Downloading https://files.pythonhosted.org/packages/15/d4/2f888fc463d516ff7bf2379a4e9a552fef7f22a94147655d9b1097108248/certifi-2018.1.18.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/70a3328b3bef7ddb73f01e9ddbe220926f47db5433fef0afbda5f5b776abd9a9--certifi-2018.1.18.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--certifi-20190704-30398-tbf
==> Downloading https://files.pythonhosted.org/packages/10/f7/3b302ff34045f25065091d40e074479d6893882faef135c96f181a57ed06/cffi-1.11.4.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/3d53a7cdf7a28834246876483f8b6dd34efcc79e2a91ba99c88eb4db7216318d--cffi-1.11.4.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--cffi-20190704-30398-18fv6x
Last 15 lines from /root/.cache/Homebrew/Logs/snapcraft/04.pip:
Removed build tracker '/tmp/pip-req-tracker-ki32ooj0'
ERROR: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-ixryuuh2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo8saavf/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-ixryuuh2/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-ixryuuh2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zo8saavf/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-ixryuuh2/

READ THIS: https://docs.brew.sh/Troubleshooting
```

---

```
root@fde41254f50b:/home/linuxbrew# brew config             
HOMEBREW_VERSION: 2.1.6-44-g895467a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 895467ad9f57a9245c36def26abca729f2559fbb
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 86502d381a32704b36a8bc09ee1dbdb983b0f913
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /root/.cache/Homebrew
HOMEBREW_LOGS: /root/.cache/Homebrew/Logs
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.22.0 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.15.0-52-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

```
root@fde41254f50b:/home/linuxbrew# brew doctor
Your system is ready to brew.
```

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

- Fixes #14107.
- The `cffi` package was failing to install for snapcraft because we
  were missing a dependency and its location:
  ```
  ==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/snapcraft--cffi-20190705-15295-1gqcfqj/cffi-1.11.4
  Last 15 lines from /root/.cache/Homebrew/Logs/snapcraft/04.pip:
  Removed build tracker '/tmp/pip-req-tracker-6j1hbkub'
  ERROR: Command "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-yui2p5h7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v8780eqo/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/cffi" failed with error code 1 in /tmp/pip-req-build-yui2p5h7/
  ```

### CODE REVIEW

**Comment by issyl0** [comment]
I have fixed this so it _builds_, but it does not _run_. When I try and run `snapcraft`, or `brew test snapcraft`, it errors with:

```
==> /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/bin/snapcraft --version
Last 15 lines from /home/issyl0/.cache/Homebrew/Logs/snapcraft/test.01.snapcraft:
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/snapcraft/__init__.py", line 343, in <module>
    from snapcraft._store import (  # noqa
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/snapcraft/_store.py", line 37, in <module>
    from snapcraft.internal import cache, deltas, repo
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/snapcraft/internal/repo/__init__.py", line 31, in <module>
    from ._deb import Ubuntu  # noqa
  File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/lib/python3.7/site-packages/snapcraft/internal/repo/_deb.py", line 32, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
Error: snapcraft: failed
```

Adding another `resource` block that pulls in [python-apt from PyPi](https://pypi.org/project/python-apt/#history) doesn't seem to fix it.

While I've fixed the reported issue here, it's obviously not functional. :grimacing:

**Comment by issyl0** [comment]
I did some more digging, and the PyPi version of `python-apt` is old (probably why it doesn't work for ys here) and unofficial. There was discussion on some [Debian mailing lists](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845330#10) about it:

> [python-apt] is tightly coupled with APT, and not supposed to be distributed in any fashion other than via Debian packages.

In light of that, I don't know what we can do here to make this to work. If we can't ask people to install host packages (because they might not have `sudo` permissions, or out of date, or whatever), how will this ever work if python-apt isn't distributed alternatively?

However, the [snapcraft requirements.txt file does include a line for a `.tar.gz` of python-apt from Launchpad](https://github.com/snapcore/snapcraft/blob/master/requirements.txt#L10) - could we build that in a separate formula and depend on it? I don't know how deep down this rabbit hole it's advisable/practical to go!

**Comment by sjackman** [comment]
Here's the source package for `python-apt` from Debian:
https://packages.debian.org/sid/python-apt
http://deb.debian.org/debian/pool/main/p/python-apt/python-apt_1.8.4.tar.xz

**Comment by sjackman** [comment]
> I don't know how deep down this rabbit hole it's advisable/practical to go!

Hard to say! You never know how deep the rabbit hole is. It depends on how badly you want to get `snapcraft` installable using Homebrew.

**Comment by issyl0** [comment]
@sjackman Thanks for the links! I've gone further down the rabbit hole (dependencies of dependencies) and at least I have some new errors? :thought_balloon:

**Comment by iMichka** [comment]
```
snapcraft:
  * Stable resource "distutils-extra": The URL http://deb.debian.org/debian/pool/main/p/python-distutils-extra/python-distutils-extra_2.38.orig.tar.gz should use HTTPS rather than HTTP
  * Stable resource "python-apt": The URL http://deb.debian.org/debian/pool/main/p/python-apt/python-apt_1.8.4.tar.xz should use HTTPS rather than HTTP
```

**Comment by iMichka** [comment]
```
Running setup.py install for python-apt: started
    Running command /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-r2g25itp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8a1z4vu5/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.3/libexec/include/site/python3.7/python-apt
    W: [python3.7] Sphinx import error.
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized
  Running setup.py install for python-apt: finished with status 'error'
Cleaning up...
```

**Comment by issyl0** [comment]
The `--single-version-externally-managed` error seems to come from [out of date `setuptools` and `wheel` packages](https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind)? Adding a "setuptools" resource fails the audit, as it's already included in the virtualenv settings, and specifying a "wheel" resource for the latest version does not immediately solve it locally. My next avenue is maybe it's something to do with the paths to things installed via `resources`, especially given the other warning about Sphinx not being found even though it installed successfully. :thinking:

**Comment by iMichka** [comment]
We are setting up this command line here: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L72-L89

Still investigating

**Comment by iMichka** [comment]
Looking at the setup.py file from python-apt, which is from 2002!, the code imports the distutils library, and probably does not recognise the `--single-version-externally-managed` flag.

In this case we need to install we need to install that resource manually ourselves, like we do in https://github.com/Homebrew/linuxbrew-core/blob/13dd4ef15534c740e72fcdc34bdd9cb8e6f206fd/Formula/dnsviz.rb#L46-L52

Could you try that?

**Comment by issyl0** [comment]
Thanks, Michka. Unfortunately, I just tried a load of permutations of the above example to no avail:

- Adding all the things.
- Just including the `resource("python-apt")` block.
- Changing the `setup.py` line to not `build_ext`, but just `install`.
- Only including the `setup.py` lines.

¯\\_(ツ)_/¯

**Comment by dawidd6** [comment]
I think that the main problem here is:
```sh
python/apt_pkgmodule.h:14:28: fatal error: apt-pkg/hashes.h: No such file or directory
```

According to `debian/control`, `python-apt` package build_depends on `libapt-pkg-dev`.
So, I would say there is a need to do another resource maybe with `apt`, but using only `libapt`, cause whole `apt` would be useless.

**Comment by issyl0** [comment]
Thank you, @dawidd6, that was very helpful! :1st_place_medal: I think using the beta build from Launchpad is good for us, given that the Snapcraft project itself uses that build.

Now the issue remains of how we get it working given that `sudo apt-get install libapt-pkg-dev` isn't ideal as a pre-requisite as our users may not always have `sudo` permissions. Back to :thinking:.

**Comment by dawidd6** [comment]
Well, I actually started brewing the whole `apt`, but I have a really hard time with `po4a`, which is a build dependency. Maybe I should make another PR with `apt` or maybe you will find a better solution @issyl0 :)

Tbh it's kinda weird, that `snapcraft` needs `apt` on linux but not on darwin.

**Comment by iMichka** [comment]
Here was my attempt back in 2017 to package apt: https://github.com/Homebrew/linuxbrew-core/pull/3622/files#diff-551dc4084a0e03e22110397dcaa903a6

I must admit that I gave up after spending multiple hours on that task ...

**Comment by issyl0** [comment]
[There's a new version of `snapcraft` in a PR in Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/pull/43191). I hope that we can make progress after that for building this on Linux, maybe things have changed in their build process/dependencies?

**Comment by dawidd6** [comment]
`python-apt` is still in the `requirements.txt` file, so I would say nothing should change.

**Comment by issyl0** [comment]
This is blocked on https://github.com/Homebrew/linuxbrew-core/pull/15285. 😍

**Comment by issyl0** [comment]
Out of curiosity, I rebased my local branch and added `depends_on "apt"` and [here are the logs](https://gist.github.com/issyl0/6c405661b606f9f055e31a008483c9f2). I've not investigated the error at all.

**Comment by iMichka** [comment]
Here is the error:

```
gcc-5 -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -I/home/linuxbrew/.linuxbrew/opt/libffi/lib/libffi-3.2.1/include -fPIC -I/home/linuxbrew/.linuxbrew/opt/python/include/python3.7m -c python/acquire.cc -o build/temp.linux-x86_64-3.7/python/acquire.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
    python/acquire.cc: In function 'PyObject* acquireworker_get_current_size(PyObject*, void*)':
    python/acquire.cc:54:58: error: 'class pkgAcquire::Worker' has no member named 'CurrentSize'
         return MkPyNumber(GetCpp<pkgAcquire::Worker*>(self)->CurrentSize);
                                                              ^
    python/acquire.cc: In function 'PyObject* acquireworker_get_total_size(PyObject*, void*)':
    python/acquire.cc:59:58: error: 'class pkgAcquire::Worker' has no member named 'TotalSize'
         return MkPyNumber(GetCpp<pkgAcquire::Worker*>(self)->TotalSize);
                                                              ^
    python/acquire.cc: In function 'PyObject* acquireworker_get_resumepoint(PyObject*, void*)':
    python/acquire.cc:64:58: error: 'class pkgAcquire::Worker' has no member named 'ResumePoint'
         return MkPyNumber(GetCpp<pkgAcquire::Worker*>(self)->ResumePoint);
                                                              ^
    python/acquire.cc: In function 'PyObject* PkgAcquireNew(PyTypeObject*, PyObject*, PyObject*)':
    python/acquire.cc:335:14: error: 'class pkgAcquire' has no member named 'Setup'
         fetcher->Setup(progress);
                  ^
    error: command 'gcc-5' failed with exit status 1
  Running setup.py install for python-apt: finished with status 'error'
```

**Comment by iMichka** [comment]
Rebased. I updated python-apt to the latest version.

**Comment by iMichka** [comment]
We have a different error now:

```
2019-11-04T19:12:58.3077436Z /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/bin/pip
2019-11-04T19:12:58.3077932Z install
2019-11-04T19:12:58.3078842Z -v
2019-11-04T19:12:58.3079390Z --no-deps
2019-11-04T19:12:58.3080445Z --no-binary
2019-11-04T19:12:58.3080825Z :all:
2019-11-04T19:12:58.3081307Z --ignore-installed
2019-11-04T19:12:58.3086977Z /tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0
2019-11-04T19:12:58.3087425Z 
2019-11-04T19:12:58.3087988Z Created temporary directory: /tmp/pip-ephem-wheel-cache-9fhok9fy
2019-11-04T19:12:58.3088513Z Created temporary directory: /tmp/pip-req-tracker-2rwiuf1k
2019-11-04T19:12:58.3089014Z Created requirements tracker '/tmp/pip-req-tracker-2rwiuf1k'
2019-11-04T19:12:58.3089481Z Created temporary directory: /tmp/pip-install-h6r5_g8w
2019-11-04T19:12:58.3090538Z Processing /tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0
2019-11-04T19:12:58.3091127Z   Created temporary directory: /tmp/pip-req-build-_pqmix0a
2019-11-04T19:12:58.3095711Z   Added file:///tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0 to build tracker '/tmp/pip-req-tracker-2rwiuf1k'
2019-11-04T19:12:58.3096500Z     Running setup.py (path:/tmp/pip-req-build-_pqmix0a/setup.py) egg_info for package from file:///tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0
2019-11-04T19:12:58.3096836Z     Running command python setup.py egg_info
2019-11-04T19:12:58.3097070Z     W: [python3.7] Sphinx import error.
2019-11-04T19:12:58.3097253Z     running egg_info
2019-11-04T19:12:58.3097697Z     creating /tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info
2019-11-04T19:12:58.3098584Z     writing /tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/PKG-INFO
2019-11-04T19:12:58.3099158Z     writing dependency_links to /tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/dependency_links.txt
2019-11-04T19:12:58.3099720Z     writing top-level names to /tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/top_level.txt
2019-11-04T19:12:58.3101223Z     writing manifest file '/tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/SOURCES.txt'
2019-11-04T19:12:58.3101823Z     reading manifest file '/tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/SOURCES.txt'
2019-11-04T19:12:58.3102368Z     writing manifest file '/tmp/pip-req-build-_pqmix0a/pip-egg-info/python_apt.egg-info/SOURCES.txt'
2019-11-04T19:12:58.3103027Z   Source in /tmp/pip-req-build-_pqmix0a has version 0.0.0, which satisfies requirement python-apt==0.0.0 from file:///tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0
2019-11-04T19:12:58.3107696Z   Removed python-apt==0.0.0 from file:///tmp/snapcraft--python-apt-20191104-18671-1k08whf/python-apt-1.9.0 from build tracker '/tmp/pip-req-tracker-2rwiuf1k'
2019-11-04T19:12:58.3108453Z Skipping wheel build for python-apt, due to binaries being disabled for it.
2019-11-04T19:12:58.3108964Z Installing collected packages: python-apt
2019-11-04T19:12:58.3109435Z   Created temporary directory: /tmp/pip-record-fdrm8lmb
2019-11-04T19:12:58.3110399Z     Running setup.py install for python-apt: started
2019-11-04T19:12:58.3111614Z     Running command /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fdrm8lmb/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/include/site/python3.7/python-apt
2019-11-04T19:12:58.3112239Z     W: [python3.7] Sphinx import error.
2019-11-04T19:12:58.3112487Z     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
2019-11-04T19:12:58.3112955Z        or: setup.py --help [cmd1 cmd2 ...]
2019-11-04T19:12:58.3113662Z        or: setup.py --help-commands
2019-11-04T19:12:58.3114095Z        or: setup.py cmd --help
2019-11-04T19:12:58.3114312Z 
2019-11-04T19:12:58.3114743Z     error: option --single-version-externally-managed not recognized
2019-11-04T19:12:58.3115214Z     Running setup.py install for python-apt: finished with status 'error'
2019-11-04T19:12:58.3115463Z Cleaning up...
2019-11-04T19:12:58.3115871Z   Removing source in /tmp/pip-req-build-_pqmix0a
2019-11-04T19:12:58.3116367Z Removed build tracker '/tmp/pip-req-tracker-2rwiuf1k'
2019-11-04T19:12:58.3122907Z ERROR: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fdrm8lmb/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/include/site/python3.7/python-apt Check the logs for full command output.
2019-11-04T19:12:58.3123658Z Exception information:
2019-11-04T19:12:58.3123919Z Traceback (most recent call last):
2019-11-04T19:12:58.3124437Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
2019-11-04T19:12:58.3124733Z     status = self.run(options, args)
2019-11-04T19:12:58.3125352Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 455, in run
2019-11-04T19:12:58.3125651Z     use_user_site=options.use_user_site,
2019-11-04T19:12:58.3126168Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
2019-11-04T19:12:58.3126455Z     **kwargs
2019-11-04T19:12:58.3126938Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 888, in install
2019-11-04T19:12:58.3127240Z     cwd=self.unpacked_source_directory,
2019-11-04T19:12:58.3127734Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
2019-11-04T19:12:58.3128018Z     spinner=spinner,
2019-11-04T19:12:58.3128510Z   File "/home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2019-11-04T19:12:58.3128783Z     raise InstallationError(exc_msg)
2019-11-04T19:12:58.3129789Z pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_pqmix0a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fdrm8lmb/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/snapcraft/3.8_1/libexec/include/site/python3.7/python-apt Check the logs for full command output.
2019-11-04T19:12:59.1424725Z 
2019-11-04T19:12:59.1425077Z ==> Formula
2019-11-04T19:12:59.1425970Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/snapcraft.rb
```

**Comment by iMichka** [comment]
I squashed all these changes and merged this as-is. This PR has been open since July and has not made much progress since then. Let's close this until somebody wants to pick it up.

**Comment by issyl0** [comment]
<3 Thanks, Michka!

**Pull request closed without merging**
