### PR TITLE
adoptopenjdk@11 11.0.8.10

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
==> brew audit adoptopenjdk@11 --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
adoptopenjdk@11:
  * JARs were installed to "/home/linuxbrew/.linuxbrew/opt/adoptopenjdk@11/lib"
    Installing JARs to "lib" can cause conflicts between packages.
    For Java software, it is typically better for the formula to
    install to "libexec" and then symlink or wrap binaries into "bin".
    See "activemq", "jruby", etc. for examples.
    The offending files are:
      /home/linuxbrew/.linuxbrew/opt/adoptopenjdk@11/lib/jrt-fs.jar

==> brew linkage --test adoptopenjdk@11
==> FAILED
Missing libraries:
  unexpected (libX11.so.6)
  unexpected (libXext.so.6)
  unexpected (libXi.so.6)
  unexpected (libXrender.so.1)
  unexpected (libXtst.so.6)
  unexpected (libasound.so.2)
  unexpected (libjvm.so)
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
Unexpected missing library linkage detected
```

**Comment by SeekingMeaning** [comment]
Fixed audit, and not sure how to deal with missing libraries (Adding `linuxbrew/xorg` dependencies doesn't work)

**Comment by SeekingMeaning** [comment]
```
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
No broken library linkage detected
```

**Comment by iMichka** [comment]
Can you rebase this on master? The xorg packages gave moved to core now.

**Comment by SeekingMeaning** [comment]
Formula deleted in #21670

**Pull request closed without merging**
