### PR TITLE
mysql: Build with GCC 5

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

### CODE REVIEW

**Comment by sjackman** [comment]
The patch https://raw.githubusercontent.com/NixOS/nixpkgs/dae42566dbee37a3b7a609fa86eca9618f4f4b67/pkgs/servers/sql/mysql/abi-check.patch doesn't appear necessary to build on CI. I don't know whether this patch has another purpose.

**Comment by iMichka** [comment]
If I remember well, there is an internal check in the mysql build process that was checking for mismatched ABI's. I think we had to add it because that check got triggered (because as we just noticed, our whole gcc stack was just broken). This also means that the patch is probably wrong, it was working around that ABI check, which was legit.

**Comment by danielnachun** [comment]
I think you need to add `uses_from_macos "krb5"` and `depends_on "libsasl2"` for this pass CI.  `libsasl2` should be a Linux-only dependency (because it is a Linux only formula).

**Comment by sjackman** [comment]
```
-- CMAKE_SHARED_LINKER_FLAGS_DEBUG  -Wl,-rpath,'$ORIGIN/../../private'
CMake Error at CMakeLists.txt:1395 (MESSAGE):
  Please install the patchelf(1) utility.
```
https://github.com/Homebrew/linuxbrew-core/pull/22500/checks?check_run_id=2059795387#step:7:447
😮

**Review by iMichka — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
I think we should still add:
```uses_from_macos "krb5" and depends_on "libsasl2"```

**Comment by sjackman** [comment]
> I think we should still add:
> `uses_from_macos "krb5"` and `depends_on "libsasl2"`

```console
$ brew linkage mysql
System libraries:
  /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libedit.3.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libsasl2.2.dylib
Homebrew libraries:
  /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (openssl@1.1)
  /usr/local/opt/protobuf/lib/libprotobuf-lite.26.dylib (protobuf)
  /usr/local/opt/protobuf/lib/libprotobuf.26.dylib (protobuf)
Variable-referenced libraries:
…
```

MySQL on macOS has linkage to the macOS-provided `libsasl2.2.dylib`. It has no evident linkage to the macOS-provided `/usr/lib/libkrb*.dylib`. Shall I add `uses_from_macos "libsasl2"` to this formula?

My tendency is not to add any additional dependencies until they're requested by at least one user. Since `libsasl2` is linked on macOS though, I'm fine with doing that as well on Linux.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/brew/pull/10808 `rubocops: Permit uses_from_macos "libsasl2"`

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/homebrew-core/pull/72759 `cyrus-sasl 2.1.27 (new formula) `

**Comment by sjackman** [comment]
I've added `uses_from_macos "cyrus-sasl"`.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
