### PR TITLE
qt: Fix build for Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
rpath,/home/linuxbrew/.linuxbrew/Cellar/libb2/0.98.1/lib::::::::  qtbase/lib/libQt6Core_qobject.a  /home/linuxbrew/.linuxbrew/lib/libz.so  -lm  /home/linuxbrew/.linuxbrew/lib/libicui18n.so  /home/linuxbrew/.linuxbrew/lib/libicuuc.so  /home/linuxbrew/.linuxbrew/lib/libicudata.so  /home/linuxbrew/.linuxbrew/lib/libzstd.so  -ldl  /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so  -lpthread  /home/linuxbrew/.linuxbrew/lib/libdouble-conversion.so.3.1.5  /home/linuxbrew/.linuxbrew/Cellar/libb2/0.98.1/lib/libb2.so  /home/linuxbrew/.linuxbrew/lib/libpcre2-16.so  /home/linuxbrew/.linuxbrew/lib/libgthread-2.0.so  /usr/lib/x86_64-linux-gnu/librt.so && :
2021-03-02T20:17:40.4412855Z /home/linuxbrew/.linuxbrew/bin/ld: qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qmetatype.cpp.o: in function `QMetaType::create(void const*) const':
2021-03-02T20:17:40.4414122Z qmetatype.cpp:(.text+0x8f4): undefined reference to `operator new(unsigned long, std::align_val_t)'
2021-03-02T20:17:40.4415417Z /home/linuxbrew/.linuxbrew/bin/ld: qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qmetatype.cpp.o: in function `QMetaType::destroy(void*) const':
2021-03-02T20:17:40.4416622Z qmetatype.cpp:(.text+0x847): undefined reference to `operator delete(void*, std::align_val_t)'
2021-03-02T20:17:40.4417218Z collect2: error: ld returned 1 exit status
2021-03-02T20:17:40.4417749Z [496/6140] Building CXX object qtbase/src/tools/uic/CMakeFiles/uic.dir/main.cpp.o
2021-03-02T20:17:40.4418406Z [497/6140] Building CXX object qtbase/src/tools/uic/CMakeFiles/uic.dir/driver.cpp.o
2021-03-02T20:17:40.4418955Z ninja: build stopped: subcommand failed.
```

**Comment by danielnachun** [comment]
I suspect given this is occurring with `ld` that this is the same problem we've been dealing with where the `libstdc++.so.6` from brewed gcc-5 is being linked instead of the `libstdc++.so.6` from gcc-7.  The reason we are pulling in brewed gcc-5 in CI is because of the following dependency chain `qt -> mesa -> llvm -> gcc`.

I'm not really sure why LLVM even has a dependency on GCC at all.  It only links `libgcc_s` and `libstdc++`, both of which will be provided by either the  host GCC (in CI) or brewed gcc-5.  I think if LLVM can work without GCC as an explicit dependency, it will remove brewed gcc-5 from the dependency tree of `qt` and I think that will fix this.    

I'm happy to test this in Docker but I don't know how to fetch this pull request locally.

**Comment by iMichka** [comment]
In my #21380 PR I am removing the gcc dependency, so this should be gone soon.

> Im happy to test this in Docker but I don't know how to fetch this pull request locally.

I guess: `git remote add iMichka https://github.com/iMichka/homebrew-core-1 && git fetch iMichka && git checkout qt6`

**Comment by danielnachun** [comment]
I just tried to build LLVM without the GCC dependency and it failed.  It seems to need some headers from GCC which are **not** provided by the host GCC.  I guess this is a scenario I didn't describe in https://github.com/Homebrew/linuxbrew-core/pull/21380.  I'll post over there so we can discuss how to handle that.

For this, I will just edit the LLVM formula to use `gcc@10` for now and install the bottle.  I want to see if anything else fails once we avoid installing brewed gcc-5.

**Comment by danielnachun** [comment]
Great news!  I got this to build after removing gcc-5 from the dependency tree.  I then encountered a test failure because the `heif` and `heic` image formats were not supported.  I temporarily removed those from the list of image formats to test for and now the failure I've hit is that it needs `gcc-7` in the `test` block.  Even when I add use `depends_on "gcc@7" => [:build, :test]`, it still seems to use the host gcc-5.  I think we're close to getting this to work!

**Comment by danielnachun** [comment]
A small update: adding `libheif` a dependency fixes the test failure for missing `heif` and `heic` image support.  This may have been a library that was previously bundled with QT and now has to be provided.  Once we can figure out to make sure we build the test binaries with g++-7, I'm hoping the tests will pass.

**Comment by byxrolland** [comment]
I tried to install qt using gcc-10, and got the error:
```
[722/6138] Linking CXX shared library qtbase/lib/libQt6Network.so.6.0.1
FAILED: qtbase/lib/libQt6Network.so.6.0.1 qtbase/src/network/Network.version
cd /tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/src/network && /home/linuxbrew/.linuxbrew/bin/perl /tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/mkspecs/features/data/unix/findclasslist.pl < /tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/src/network/Network.version.in > /tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/src/network/Network.version && cd /tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1 && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-10 -fPIC -DNDEBUG -O2  -Wl,-Bsymbolic-functions -Wl,--version-script,/tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/src/network/Network.version -Wl,--no-undefined -Wl,--enable-new-dtags -R/home/linuxbrew/.linuxbrew/Cellar/brotli/1.0.9/lib -shared -Wl,-soname,libQt6Network.so.6 -o qtbase/lib/libQt6Network.so.6.0.1 qtbase/src/network/CMakeFiles/Network.dir/Network_autogen/mocs_compilation.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qabstractnetworkcache.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhsts.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhstspolicy.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccessauthenticationmanager.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccessbackend.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccesscache.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccesscachebackend.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccessdebugpipebackend.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccessfilebackend.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkaccessmanager.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkcookie.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkcookiejar.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkfile.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkreply.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkreplydataimpl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkreplyfileimpl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkreplyimpl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkrequest.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qauthenticator.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qhostaddress.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qhostinfo.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetworkdatagram.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetworkinterface.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetworkproxy.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qabstractsocket.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qabstractsocketengine.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qnativesocketengine.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qtcpserver.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qtcpsocket.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qudpsocket.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qasn1element.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qpassworddigestor.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslcertificate.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslcertificateextension.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkdiskcache.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhstsstore.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/bitstreams.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/hpack.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/hpacktable.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/http2frames.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/http2protocol.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/http2streams.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/http2/huffman.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qabstractprotocolhandler.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qdecompresshelper.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttp2configuration.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttp2protocolhandler.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpmultipart.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpnetworkconnection.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpnetworkconnectionchannel.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpnetworkheader.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpnetworkreply.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpnetworkrequest.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpprotocolhandler.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qhttpthreaddelegate.cpp.o qtbase/src/network/CMakeFiles/Network.dir/access/qnetworkreplyhttpimpl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qhttpsocketengine.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qtldurl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qdnslookup.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qhostinfo_unix.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qnativesocketengine_unix.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetworkinterface_linux.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetconmonitor_stub.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qnetworkproxy_libproxy.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qsocks5socketengine.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qlocalserver.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qlocalsocket.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qlocalserver_unix.cpp.o qtbase/src/network/CMakeFiles/Network.dir/socket/qlocalsocket_unix.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qocspresponse.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslcipher.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslconfiguration.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qssldiffiehellmanparameters.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslellipticcurve.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslerror.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslkey_p.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslpresharedkeyauthenticator.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslsocket.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qdtls.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslcertificate_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslcontext_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qssldiffiehellmanparameters_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslellipticcurve_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslkey_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslsocket_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qsslsocket_openssl_symbols.cpp.o qtbase/src/network/CMakeFiles/Network.dir/ssl/qdtls_openssl.cpp.o qtbase/src/network/CMakeFiles/Network.dir/kernel/qdnslookup_unix.cpp.o  -Wl,-rpath,/tmp/qt-20210303-32412-10j7n4x/qt-everywhere-src-6.0.1/qtbase/lib:/home/linuxbrew/.linuxbrew/Cellar/brotli/1.0.9/lib:/home/linuxbrew/.linuxbrew/Cellar/libproxy/0.4.17_1/lib:  /home/linuxbrew/.linuxbrew/lib/libzstd.so  /home/linuxbrew/.linuxbrew/lib/libz.so  -ldl  /home/linuxbrew/.linuxbrew/lib/libgssapi_krb5.so  -ldl  qtbase/lib/libQt6Core.so.6.0.1  -lpthread  /home/linuxbrew/.linuxbrew/Cellar/brotli/1.0.9/lib/libbrotlidec.so  /home/linuxbrew/.linuxbrew/Cellar/libproxy/0.4.17_1/lib/libproxy.so && :
g++-10: error: unrecognized command-line option '-R'
```
But I don't know how to fix it.

**Comment by danielnachun** [comment]
Hmm, I can't reproduce this in the CI Docker environment - it builds fine for me with gcc-10.  Once we get this to build there, it should be a relocatable bottle that nobody will need to compile.

**Comment by byxrolland** [comment]
It keeps happening. Maybe it's because of WSL?

**Comment by iMichka** [comment]
I'm rebuilding `libproxy` with gcc-5 to get rid of gcc@7 from the dependency tree: #22510

**Comment by byxrolland** [comment]
Where can I find the CMakeLists.txt for this project?

**Comment by danielnachun** [comment]
Currently I think the issue is that we ran out of disk space in CI while building.  I think there was some trick to deal with this but I'm not sure how (unless we need to use self-hosted VM?).  Once we get this to build in CI it is a relocatable bottle so no users will need to compile it.

**Comment by iMichka** [comment]
I added the workaround for the disk space issue.

The test is failing now:
```
-- Configuring incomplete, errors occurred!
root@665f57472870:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qttest# vim CMakeLists.txt
root@665f57472870:/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qttest# cmake .
-- The CXX compiler identification is GNU 5.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR)
-- Could NOT find WrapOpenGL (missing: WrapOpenGL_FOUND)
CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Gui could not be found because dependency WrapOpenGL could not be found.

Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:86 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake

  but it set Qt6Widgets_FOUND to FALSE so package "Qt6Widgets" is considered
  to be NOT FOUND.  Reason given by package:

  Qt6Widgets could not be found because dependency Qt6Gui could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Sql/Qt6SqlDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Sql/Qt6SqlConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Sql/Qt6SqlConfig.cmake

  but it set Qt6Sql_FOUND to FALSE so package "Qt6Sql" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Sql could not be found because dependency Qt6 could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Concurrent/Qt6ConcurrentDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Concurrent/Qt6ConcurrentConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Concurrent/Qt6ConcurrentConfig.cmake

  but it set Qt6Concurrent_FOUND to FALSE so package "Qt6Concurrent" is
  considered to be NOT FOUND.  Reason given by package:

  Qt6Concurrent could not be found because dependency Qt6 could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt63DCore/Qt63DCoreDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt63DCore/Qt63DCoreConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt63DCore/Qt63DCoreConfig.cmake

  but it set Qt63DCore_FOUND to FALSE so package "Qt63DCore" is considered to
  be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  Qt6::Network

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""

  Failed to find Qt component "3DCore" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Svg/Qt6SvgDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Svg/Qt6SvgConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Svg/Qt6SvgConfig.cmake

  but it set Qt6Svg_FOUND to FALSE so package "Qt6Svg" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Svg could not be found because dependency Qt6 could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""

  Failed to find Qt component "3DCore" config file at ""

  Failed to find Qt component "Svg" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Quick3D/Qt6Quick3DDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Quick3D/Qt6Quick3DConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Quick3D/Qt6Quick3DConfig.cmake

  but it set Qt6Quick3D_FOUND to FALSE so package "Qt6Quick3D" is considered
  to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: Qt6::Qml
  Qt6::Quick Qt6::Quick3DRuntimeRender Qt6::QmlPrivate
  Qt6::Quick3DRuntimeRenderPrivate Qt6::QuickPrivate

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""

  Failed to find Qt component "3DCore" config file at ""

  Failed to find Qt component "Svg" config file at ""

  Failed to find Qt component "Quick3D" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Network/Qt6NetworkDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Network/Qt6NetworkConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6Network/Qt6NetworkConfig.cmake

  but it set Qt6Network_FOUND to FALSE so package "Qt6Network" is considered
  to be NOT FOUND.  Reason given by package:

  Qt6Network could not be found because dependency Qt6 could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Warning at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.19.7/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""

  Failed to find Qt component "3DCore" config file at ""

  Failed to find Qt component "Svg" config file at ""

  Failed to find Qt component "Quick3D" config file at ""

  Failed to find Qt component "Network" config file at ""



Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6NetworkAuth/Qt6NetworkAuthDependencies.cmake:8 (find_dependency)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6NetworkAuth/Qt6NetworkAuthConfig.cmake:40 (include)
  /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package)
  CMakeLists.txt:12 (find_package)


cmake_minimum_required(VERSION 3.19.0)
CMake Warning at /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake:90 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6NetworkAuth/Qt6NetworkAuthConfig.cmake

  but it set Qt6NetworkAuth_FOUND to FALSE so package "Qt6NetworkAuth" is
  considered to be NOT FOUND.  Reason given by package:

  Qt6NetworkAuth could not be found because dependency Qt6 could not be
  found.

Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


CMake Error at CMakeLists.txt:12 (find_package):
  Found package configuration file:

    /home/linuxbrew/.linuxbrew/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Widgets" config file at ""

  Failed to find Qt component "Sql" config file at ""

  Failed to find Qt component "Concurrent" config file at ""

  Failed to find Qt component "3DCore" config file at ""

  Failed to find Qt component "Svg" config file at ""

  Failed to find Qt component "Quick3D" config file at ""

  Failed to find Qt component "Network" config file at ""

  Failed to find Qt component "NetworkAuth" config file at ""
```

**Comment by danielnachun** [comment]
Which part of the test is this from?  Right now I'm having trouble getting `qmake` to build the `.pro` file.  I figured out that it bypasses the gcc shim, but I made some progress by adding `QMAKE_CXX=#{ENV.cxx}` to the `test.pro` file.  Then it fails at the linking step, which I was also able to force to use the shim with `QMAKE_LINK=#{ENV.cxx}`.  However the shim doesn't appear to recognize it's being used as CXXLD and consequently it doesn't add the other `rpaths` needed to find the external dependencies (including `mesa` for `libGL`).

**Comment by danielnachun** [comment]
We have a pull request open in homebrew-core to fix this: https://github.com/Homebrew/homebrew-core/pull/84007.  It currently builds but has some issue with incorrect paths in PRL files.  I will close this now so please check that PR for future updates.

**Pull request closed without merging**
