### PR TITLE
qt: disable MySQL driver and SDL2 as dependency on Linux

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Can you rebase this, I fixed libproxy in #21777.

Also, bump the revision (only for linux, with an unless OS.mac?), and remove the sha256 line.

**Comment by danielnachun** [comment]
I bungled the rebase a little bit (I'm still a noob with git) and `at-spi2-core` now fails with an error with `gettext`.  Not sure if that was why, though there was a `gettext` update today and I hit that same error while building some R packages.  I solved it by reinstalling R, I'm not sure what's happening here.

**Comment by iMichka** [comment]
Yes, something changed in `gettext`, and now we will need to fix some gettext bugs. See #21785
The fix will be as easy as adding `ENV.append "LDFLAGS", "-lintl"` to the broken formulae.

I fixed `at-spi2-core` and a bottle is being built right now. You can already rebase again.

**Comment by iMichka** [comment]
I fixed the syntax error you can try again. Sorry for the issue.

**Comment by iMichka** [comment]
Nice work here. I merged this, and a bottle build is under way.

Just one small comment: can you squad your commits next time; so that we only have 1 commit to merge. Thanks !

**Pull request merged**
