### PR TITLE
qwt: -spec, audit test fixed.

### PR DESCRIPTION
**Pull request by JuPlutonic**
- [x] Have you followed the [guidelines for contributing](https://github.com/Linuxbrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Linuxbrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by JuPlutonic** [comment]
CircleCI didn't cope with tests normally, my Ubuntu18.10 env:
```
brew test Formula/qwt.rb --verbose            15:59:14  
Testing qwt
==> qmake /tmp/qwt-test-20190216-31295-16mpyfg/plotcurve.pro
Info: creating stash file /tmp/qwt-test-20190216-31295-16mpyfg/.qmake.stash
==> make
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQWT_DLL -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/qwt/6.1.3_5/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/include/QtSvg -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/include/QtWidgets -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/include/QtGui -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/libxau/1.0.8/include -I/home/linuxbrew/.linuxbrew/Cellar/libxdmcp/1.1.2/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.13/include -I/home/linuxbrew/.linuxbrew/Cellar/libdrm/2.4.94/include -I/home/linuxbrew/.linuxbrew/Cellar/libdrm/2.4.94/include/libdrm -I/home/linuxbrew/.linuxbrew/Cellar/libx11/1.6.6/include -I/home/linuxbrew/.linuxbrew/Cellar/libxfixes/5.0.3/include -I/home/linuxbrew/.linuxbrew/Cellar/libxdamage/1.1.4/include -I/home/linuxbrew/.linuxbrew/Cellar/libxext/1.3.3/include -I/home/linuxbrew/.linuxbrew/Cellar/libxxf86vm/1.1.4/include -I/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/include -I/home/linuxbrew/.linuxbrew/Cellar/xorgproto/2018.4/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/mkspecs/linux-g++ -o test.o test.cpp
g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/lib -o plotcurve test.o   -L/home/linuxbrew/.linuxbrew/Cellar/qwt/6.1.3_5/lib -lqwt -L/home/linuxbrew/.linuxbrew/Cellar/qt/5.12.0/lib -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core -L/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib -lGL -lpthread   
==> ./plotcurve
```

**Comment by JuPlutonic** [comment]
(Not sure this is actually stale...?)
How to ask bot to redo tests?
Hey @test-bot …

**Comment by JuPlutonic** [comment]
[Changed ci/circleci url:](https://circleci.com/gh/Homebrew/linuxbrew-core/25619?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by iMichka** [comment]
`qt` is completely broken right now: #11696
So you will have to wait anyway until it is fixed. Sorry about that.

**Pull request closed without merging**
