### PR TITLE
openssl@1.1: ship our own version of the cacert file

### PR DESCRIPTION
**Pull request by iMichka**
This fixes: #19843

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by sjackman** [comment]
It looks like PR https://github.com/Homebrew/linuxbrew-core/pull/19843 was already merged. What specific failure does this PR fix?

**Comment by iMichka** [comment]
Yeah, maybe this was not the right issue number. #19843 was merged, but it did not fix the issue.

**Comment by sjackman** [comment]
What are the instructions to reproduce the issue?

**Comment by iMichka** [comment]
Brew upgrade.

Or brew postinstall openssl@1.1

**Comment by dawidd6** [comment]
I wasn't able to reproduce this issue in a clean Docker container. Upgrading and postinstalling works just fine.

**Comment by sjackman** [comment]
I also was not able to reproduce this issue.

**Comment by iMichka** [comment]
I could not reproduce it, though it was easily reproducible before ... weird. Maybe some weird thing happened after `brew upgrade`. If nobody else complains, I'll just close this.

**Pull request closed without merging**
