### PR TITLE
magic-wormhole: fix build

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I am wondering whether we should merge this `OS.mac?` statements for now as this fix is a workaround something that could be considered a bug in `brew`.  I'll open an issue in homebrew/brew about this when I have a chance, but it could take a while to decide the proper solution and get it merged, and it would be nice to be able to ship the bottle to our users for now.

**Comment by iMichka** [comment]
I think we could even merge this as-is in homebrew-core? It would fix it for Linux, and it still correct for Mac. Maybe add a comment with a link to the brew issue.

**Comment by danielnachun** [comment]
Okay, I'll upstream and see if it's accepted.

**Comment by danielnachun** [comment]
This was merged upstream so we can close this.

**Pull request closed without merging**
