### PR TITLE
glib: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by CL-Jeremy** [comment]
I'm also facing issues with `ldd` complaining about missing `libpcre.so.1` which basically breaks everything. The previous bottle was fine.

**Comment by CL-Jeremy** [comment]
While this is unrelated, I just spotted a small mistake here...
```
diff --git a/Formula/glib.rb b/Formula/glib.rb
index 1e5f63e4e0..46e3b5cf77 100644
--- a/Formula/glib.rb
+++ b/Formula/glib.rb
@@ -58,9 +58,9 @@ class Glib < Formula
   # `pkg-config --libs glib-2.0` includes -lintl, and gettext itself does not
   # have a pkgconfig file, so we add gettext lib and include paths here.
   gettext = Formula["gettext"].opt_prefix
-  lintl = OS.mac? ? "-lintl ": ""
+  lintl = OS.mac? ? " -lintl": ""
   inreplace lib+"pkgconfig/glib-2.0.pc" do |s|
-    s.gsub! "Libs: #{lintl}-L${libdir} -lglib-2.0",
+    s.gsub! "Libs:#{lintl} -L${libdir} -lglib-2.0",
             "Libs: -L${libdir} -lglib-2.0 -L#{gettext}/lib#{lintl}"
     s.gsub! "Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include",
             "Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -I#{gettext}/include"
```

**Comment by iMichka** [comment]
> I'm also facing issues with ldd complaining about missing libpcre.so.1

I do not see this issue here. I just uploaded the bottle. If you still have issues, please open an issue.

> While this is unrelated, I just spotted a small mistake here...

This  looks fine. The end result is the following, which seems correct to me:
```
$ cat /home/linuxbrew/.linuxbrew/Cellar/glib/2.60.4/lib/pkgconfig/glib-2.0.pc
prefix=/home/linuxbrew/.linuxbrew/Cellar/glib/2.60.4
libdir=${prefix}/lib
includedir=${prefix}/include

bindir=${prefix}/bin
glib_genmarshal=${bindir}/glib-genmarshal
gobject_query=${bindir}/gobject-query
glib_mkenums=${bindir}/glib-mkenums

Name: GLib
Description: C Utility Library
Version: 2.60.4
Requires.private: libpcre >=  8.31
Libs: -L${libdir} -lglib-2.0 -L/home/linuxbrew/.linuxbrew/opt/gettext/lib
Libs.private: -pthread
Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include
```

**Comment by CL-Jeremy** [comment]
The bottle works well, thanks.
Regarding that part, it obviously wouldn't affect Linux, but would cause a problem when merged back to upstream Homebrew, a mistake that practically never make a difference but is logically wrong per se.

**Comment by iMichka** [comment]
The file will look differently on mac.

I am not a pkg-config specialist, so if you think something is wrong with this line (on linux, or on mac), please tell me, so we can improve this.

**Comment by CL-Jeremy** [comment]
I mean, it's obvious that according to the above code, `lintl` resolves to `-lintl ` and `-L#{gettext}/lib#{lintl}` becomes `-L#{HOMEBREW_PREFIX}/opt/gettext/lib-intl ` under macOS.

**Comment by iMichka** [comment]
Right, I missed that. Fixed with cb091402cf351bc98fa978ab21019c322e23089f

**Comment by jonchang** [comment]
Having build-from-source issues caused by https://github.com/Homebrew/linuxbrew-core/commit/cb091402cf351bc98fa978ab21019c322e23089f. This patch fixes it.

```diff
-  lintl = OS.mac? ? " -lintl ": ""
+  lintl = OS.mac? ? " -lintl": ""
   inreplace lib+"pkgconfig/glib-2.0.pc" do |s|
-    s.gsub! "Libs:#{lintl}-L${libdir} -lglib-2.0",
+    s.gsub! "Libs:#{lintl} -L${libdir} -lglib-2.0",
```

**Comment by jonchang** [comment]
8b65d3dec8

**Comment by CL-Jeremy** [comment]
> [8b65d3d](https://github.com/Homebrew/linuxbrew-core/commit/8b65d3dec82e1254a6cc1485b38bc9afaf26a792)

That's what I originally did in https://github.com/Homebrew/linuxbrew-core/pull/13627#issuecomment-502094412. The difference with https://github.com/Homebrew/linuxbrew-core/commit/cb091402cf351bc98fa978ab21019c322e23089f after the `gsub` would be one single trailing space, which I thought would not cause any problem.

**Comment by iMichka** [comment]
Thanks @jonchang!

**Pull request closed without merging**
