### PR TITLE
terraform: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> make tools test bin
.
Last 150 lines from /root/.cache/Homebrew/Logs/terraform/01.make:
2019-03-10 21:15:43 +0000

make
tools
test
bin

GO111MODULE=off go get -u golang.org/x/tools/cmd/stringer
GO111MODULE=off go get -u golang.org/x/tools/cmd/cover
GO111MODULE=off go get -u github.com/golang/mock/mockgen
==> Checking that code complies with gofmt requirements...
GOFLAGS=-mod=vendor go generate ./...
2019/03/10 21:15:51 Generated command/internal_plugin_list.go
# go fmt doesn't support -mod=vendor but it still wants to populate the
# module cache with everything in go.mod even though formatting requires
# no dependencies, and so we're disabling modules mode for this right
# now until the "go fmt" behavior is rationalized to either support the
# -mod= argument or _not_ try to install things.
GO111MODULE=off go fmt command/internal_plugin_list.go > /dev/null
go list -mod=vendor ./... | xargs -t -n4 go test  -mod=vendor -timeout=2m -parallel=4
build flag -mod=vendor only valid when using modules
go test -mod=vendor -timeout=2m -parallel=4 
build flag -mod=vendor only valid when using modules
Makefile:35: recipe for target 'test' failed
make: *** [test] Error 123

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/terraform.rb
```

**Comment by dornera** [comment]
Does this help you at all? https://github.com/hashicorp/terraform/issues/20208#issuecomment-460010034
I was wondering what was going on with the installs since .11.12

**Comment by dornera** [comment]
Would adding this line fix it? https://github.com/Homebrew/homebrew-core/blob/a6fc7849abf7d93ec823c55ba37052c0ba22e799/Formula/go.rb#L59

**Comment by iMichka** [comment]
Hi. Yes, this would fix it.
See the discussion in https://github.com/Homebrew/linuxbrew-core/issues/11215#issuecomment-455651298, we used the same strategy there. Nobody understand how this works and what it does, but it seems to be the usual hack to get this working.

Would you like to open a pull request for this?

**Comment by iMichka** [comment]
Superseded by #12049

**Comment by Automobileengineeringservices** [comment]
#12003

**Pull request closed without merging**
