### PR TITLE
harfbuzz: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by JuPlutonic** [comment]
CI/CIRCLECI
> brew install --verbose --build-bottle harfbuzz
Cannot change ownership to uid 115242, gid 89939: Invalid argument
The same error #11729 because harfbuzz is a dependency for netpbm
@iMichka would you like to answer if is it possible to overcome the ownership problem

**Comment by iMichka** [comment]
I think our `tar` command needs `--no-same-owner` when run as `root`:
https://www.krenger.ch/blog/linux-tar-cannot-change-ownership-to-permission-denie

We changed the docker user to `root` a few days ago. That may explain it. I still have an old linuxbrew container and there the build was successful.

**Comment by iMichka** [comment]
There is a file called `Homebrew/unpack_strategy/tar.rb` in brew. Can you try to edit it and add the `--no-same-owner` flag to the tar commands? You may need to run `HOMEBREW_NO_AUTO_UPDATE=1 brew install harfbuzz` so that your change is not reset.

**Comment by JuPlutonic** [comment]
> `Homebrew/unpack_strategy/tar.rb`

Now I'm testing it!
Afterwards I'll fill out superseded PR to L-b/homebrew-core because harffbuzz depends_on freetype2

**Comment by JuPlutonic** [comment]
Test is ok!
```
        system_command! "tar",
                        args:    ["xf", tar_path, "-C", unpack_dir, "--no-same-owner"],
                        verbose: verbose
```
I think I need to PR to Homebrew/brew?

**Comment by JuPlutonic** [comment]
Again @iMichka you can use that --no-same-owner fix on CircleCI: installation will be successful🛡

**Comment by iMichka** [comment]
Yes, we need to submit this change to https://github.com/Homebrew/brew. The `--no-same-owner` flag does not exist for the tar version on mac, so we will probably need to safeguard that. Maybe by checking if `root` is the current user.

@sjackman @reitermarkus @MikeMcQuaid Thoughts?

**Comment by sjackman** [comment]
Here's a related StackOverflow question: https://unix.stackexchange.com/questions/285237/tar-without-preserving-user
Files in old bottles will be owned by `linuxbrew:linuxbrew` (`1000:1000`). Files in new bottles will be owned by `root:root` (`0:0`). I'm a bit surprised by this message `Cannot change ownership to 115242:89939`, which is neither of these.

Adding `--no-same-owner` when extracting bottles makes sense to me. This option is specific to GNU tar as @iMichka pointed out, so it'll need to go in `extend/os/linux`. We could also consider adding `--user=0 --group=0` when creating the bottle, so that no special options are needed when extracting it. No harm in doing both.

**Comment by thoughton** [comment]
This fix would be very much appeciated, as this issue is having a knock-on effect and preventing a number of other recipes that depend on `harfbuzz` from updating now too.

**Comment by JuPlutonic** [comment]
@sjackman *--no-same-owner* and *--group=0* are present in *tar* but *--user* is absent. So I use only these two arguments to pass into Tar.

**Comment by sjackman** [comment]
I misspoke. `--user` should have been `--owner`.

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/brew/pull/5811 is merged, resolving the issue with extracting the `harfbuzz` tarball while root on Linux.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/Homebrew/linuxbrew-core/pull/11865

**Pull request closed without merging**
