### PR TITLE
Merge 2021-06-02 e9165be69f7

### PR DESCRIPTION
**Pull request by iMichka**
Merge Homebrew/homebrew-core into Homebrew/linuxbrew-core

+ [ ] aliyun-cli
+ [ ] dnsperf
+ [ ] gdu
+ [ ] gojq
+ [ ] gowsdl
+ [ ] nats-streaming-server
+ [ ] nushell
+ [ ] redis
+ [ ] tanka
+ [ ] terraform-docs
+ [ ] dieharder
+ [ ] inlets
+ [ ] lanraragi
+ [ ] ncspot

### CODE REVIEW

**Comment by develop7** [comment]
> warning Bottle request for nushell [failed](https://github.com/Homebrew/linuxbrew-core/actions/runs/899635444).

@iMichka could you trigger it again? seems like a network hiccup

**Comment by dawidd6** [comment]
Rerunned

**Comment by develop7** [comment]
@dawidd6 failed again https://github.com/Homebrew/linuxbrew-core/runs/2766707795?check_suite_focus=true#step:5:384, looks like another hiccup

**Comment by develop7** [comment]
@dawidd6 another failure https://github.com/Homebrew/linuxbrew-core/runs/2775460819?check_suite_focus=true#step:5:253, different crate though

**Comment by develop7** [comment]
@dawidd6 @iMichka local build succeeds

**Pull request merged**
