### PR TITLE
patchelf 0.12

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by jonchang** [comment]
bootstrap needs automake

waiting on https://github.com/Homebrew/homebrew-linux-dev/runs/1049600797?check_suite_focus=true

**Comment by jonchang** [comment]
CI is 🍏

**Comment by iMichka** [comment]
This did not trigger a bottle upload once merged. Last time I had to modify the upload workflow to make it work. But @dawidd6 added a new "publish and commit bottles" workflow: I looked at the code and was quite sure it should have worked.

Maybe it's because I used "rebase and merge" instead of "squash and merge"?

I reverted the 3 commits on master around 2 minutes after this has been merged.

**Comment by dawidd6** [comment]
We use pr-publish for bottle uploads now, same as it is in homebrew-core.

**Comment by iMichka** [comment]
I see, I should have used the pr-publish command then. I sort of lost track of all these changes and the subtle differences between linuxbrew and homebrew.

I'll re-open a PR later today then. Thanks.

**Comment by dawidd6** [comment]
You can also trigger the publishing job via GitHub UI in Actions tab after selecting proper workflow.

**Pull request merged**
