### PR TITLE
various formulae: add missing conflicts_with

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This PR adds missing symmetric conflicts for remaining linuxbrew only cases (homebrew-core was fixed in https://github.com/Homebrew/homebrew-core/pull/79446).

Audit for this will be added in https://github.com/Homebrew/brew/pull/11541

### CODE REVIEW

**Comment by bayandin** [comment]
Actually, this PR should by kind of `CI-syntax-only`. 

Now it fails with 
```
==> bash-completion@2
Error: `--keep-old` was passed but there are changes in:
sha256 x86_64_linux: old: "c782153690c494c7cbd82fdbec5d7579dae5b9b7453f6670644ebba7df83377f", new: "6c04a90ca8807eff0ed1ba460d896fcfe89f9301106e62e9d692179282a456ff"
```

**Comment by iMichka** [comment]
Why is the `swift-protobuf.rb` change not in homebrew-core?

Don't worry about the CI, it's broken for such cases.

**Comment by bayandin** [comment]
> Why is the swift-protobuf.rb change not in homebrew-core?

Because there's no `protobuf-swift` formula anymore. 
It was removed in https://github.com/Homebrew/homebrew-core/pull/76902. I guess these changes should have been synched, but something went wrong. Shall I delete `protobuf-swift` in linuxbrew as well?

**Comment by iMichka** [comment]
Yes, delete it please. The merge script sometimes keeps files around, so we need to manually delete formulae from time to time.

**Review by iMichka — APPROVED** [review]

**Pull request merged**
