### PR TITLE
poppler: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```


  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:63 (_qt5_Gui_check_file_exists)
  /home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:85 (_qt5gui_find_extra_libs)
  /home/linuxbrew/.linuxbrew/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:187 (include)
  CMakeLists.txt:152 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/poppler-20191008-80330-g4vmn4/poppler-0.81.0/CMakeFiles/CMakeOutput.log".
See also "/tmp/poppler-20191008-80330-g4vmn4/poppler-0.81.0/CMakeFiles/CMakeError.log".

```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/16063
https://github.com/Homebrew/linuxbrew-core/pull/16059

**Comment by dawidd6** [comment]
@iMichka I think rebuilding `qt` may be needed. What do you think about that?

**Comment by abcfy2** [comment]
Same issue here, hope qt5 will be rebuilt.

**Pull request closed without merging**
