### PR TITLE
qt@5: revision bump for icu4c

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
I/home/linuxbrew/.linuxbrew/Cellar/xorgproto/2021.4/include -I/tmp/qtA5-20210503-17216-1om3ksw/qt-everywhere-src-5.15.2/qtbase/mkspecs/linux-g++ -o .obj/openglvertexarrayobject.o renderer/openglvertexarrayobject.cpp
2021-05-03T18:26:14.3826535Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
2021-05-03T18:26:14.3828684Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
2021-05-03T18:26:14.3830740Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
2021-05-03T18:26:14.3832754Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
2021-05-03T18:26:14.3835086Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
2021-05-03T18:26:14.3837008Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `std::_Sp_make_shared_tag::_S_eq(std::type_info const&)@GLIBCXX_3.4.26'
2021-05-03T18:26:14.3838942Z /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/llvm/12.0.0/lib/libLLVM-12.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
```

**Comment by danielnachun** [comment]
I guess this has to be built with `gcc-10` now because of `llvm`.

**Comment by danielnachun** [comment]
Does this also need `fails_with gcc: "5"`?

**Comment by danielnachun** [comment]
I think the test is failing because we need to set `ENV["CXX"] = "#{Formula["gcc"].opt_bin}/g++-10" so it uses GCC 10 instead of the system GCC 5.

**Comment by danielnachun** [comment]
I can't build this branch locally, but I think for the test block since we are using `qmake` I should have said 

`ENV["QMAKE_CXX"] = "#{Formula["gcc"].opt_bin}/g++-10` instead of 

`ENV["CXX"] = "#{Formula["gcc"].opt_bin}/g++-10`.

**Comment by danielnachun** [comment]
I know why this doesn't build now with GCC 11: https://www.gnu.org/software/gcc/gcc-11/porting_to.html
> Some C++ Standard Library headers have been changed to no longer include other headers that they do need to depend on. As such, C++ programs that used standard library components without including the right headers will no longer compile.

>The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:

><limits> (for std::numeric_limits)
><memory> (for std::unique_ptr, std::shared_ptr etc.)
><utility> (for std::pair, std::tuple_size, std::index_sequence etc.)
><thread> (for members of namespace std::this_thread.)

If I use an older version of GCC, it gets past the intial error and fails at the same Qt3D error because of mesa and LLVM are build with GCC 11.  I think this has been fixed by upstream, but it's waiting on a new stable release.  Arch Linux is able to build Qt 5 with GCC 11 by using an unstable version, as can be seen in their PKGBUILD: https://github.com/archlinux/svntogit-packages/blob/packages/qt5-base/trunk/PKGBUILD.

If there was a way for us to convert the commits in the version used by Arch Linux to a patch, then it should be build with GCC 11.  Otherwise, we'll have to wait for the next stable release.

**Comment by danielnachun** [comment]
Specifically we need https://invent.kde.org/qt/qt/qtbase/-/tree/cb2da673f53815a5cfe15f50df49b98032429f9e.  I don't know how to make that into a patch but if we can, then I think it will work.

**Comment by danielnachun** [comment]
I figured out how to make the patches.  It's gotten past where it failed before, so I'll see if this was enough to fix it

**Comment by iMichka** [comment]
We might need to build with `gcc@10`

**Comment by danielnachun** [comment]
I pushed the patches need to build with `gcc-11`.  When I built locally, it failed much later in the build process, and the failure seems to be unrelated to using `gcc-11`.  If the same failure happens here and we don't see any obvious problem, I'm going to open an issue upstream.

**Comment by iMichka** [comment]
> 2021-05-27T23:32:52.2330106Z /tmp/qtA5-20210527-17498-uc4mx4/qt-everywhere-src-5.15.2/qtbase/include/QtWidgets/../../src/widgets/dialogs/qwizard.h:265:2: fatal error: cannot write PCH file: No space left on device

**Comment by danielnachun** [comment]
That's weird.  Shouldn't `system "/home/linuxbrew/.linuxbrew/bin/brew", "cleanup", "--prune=0"` take care of that?

**Comment by danielnachun** [comment]
Hmm, I guess I didn't break the cleanup, it just isn't sufficient now that we depend on GCC 11.  Let's hope that LLVM 12 really can be built with GCC 5!

**Comment by YoshitakaMo** [comment]
Now it seems llvm 12 can be built with GCC 5 or 6 ( https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/llvm.rb ). But is there still something missing to prepare qt@5 and qt@6 bottles? I hope that this issue will be solved soon.

**Comment by danielnachun** [comment]
Unfortunately `mesa` must be built with GCC 11 even though LLVM 12 is now built with GCC 5.  This means that anything that depends on `mesa` has to be built with GCC 11 as well.  The limitation now is that we run out of disk space.  This can be overcome by using a self-hosted Linux runner in homebrew-core, but there are currently some dependencies for `qt@5` which are not bottled yet.  I will open a draft PR there to start tracking what needs to be bottled.  Once the dependences are all bottled, we should be able to make progress on this.

**Comment by iMichka** [comment]
Yes, I think the plan is to fix this in homebrew-core now, and close this pull request. People that need Qt can migrate to the homebrew-core version on linuxbrew. They’ll live on the bleeding edge for a few weeks but we should be able to migrate our other users soon. One limitation might be that a fresh linuxbrew installation will be needed, as formula revisions will differ between both repos.

**Comment by aspartamed** [comment]
Sorry this is my first time using brew for anything. I came here from https://github.com/Homebrew/linuxbrew-core/issues/23293 trying to build **opencv3** and dying at **qt@5**. It sounds like the solution from from a few weeks ago is:

 `People that need Qt can migrate to the homebrew-core version on linuxbrew. They’ll live on the bleeding edge for a few weeks but we should be able to migrate our other users soon`
 
 Can any one explain to me what that means I need to do? is this fixed somewhere ? how do I get it?

**Comment by jasjuang** [comment]
Commenting to receive email updates due to #23293 being closed

**Comment by iMichka** [comment]
Fixed by c389985d68c7e6305c9281272d764a34e49331fb, there is now a qt@5 bottle.

**Pull request closed without merging**
