### PR TITLE
latexml: remove redundant resources

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
Most of this was merged upstream, but `Pod::Find` was not for some reason, so I will still have to open a PR for just that.

**Comment by iMichka** [comment]
Looks like it's missing `HTTP::Date` too.

**Comment by danielnachun** [comment]
I ended up having to add two more resources in addition to `HTTP::Date`.  I'm not sure how this passed the test before (because there was already a bottle).  That's probably nothing to worry about?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
It also happened to me in a few other formulae. Weird. No need to investigate.

**Pull request closed without merging**
