### PR TITLE
mingw-w64: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by rfay** [comment]
mingw-w64 is currently broken - it tries to build gcc@9 from source and hangs there  for 10 minutes.

This is apparently since 90c25282216031ca0c0ed56d873cabdc5ed1a042 and 804c5ef33ab96b4a10240282a2a800e100b1ad3e

**Comment by rfay** [comment]
Opened https://github.com/Homebrew/linuxbrew-core/issues/18364 about broken mingw-w64

**Comment by iMichka** [comment]
```
mingw-w64:
2019-12-27T16:35:17.3328625Z   * The URL https://mingw-w64.org/ is not reachable
```

This is the only failure we got, which makes sense as this website does not have a ssl certificate. I pulled the bottle as it built correctly.

@rfay you can now update and upgrade, this should work as we are now providing pre-compiled binaries.

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like util-linux. If it's an option for you, you could open a ticket with your information systems department to ask that they create a linuxbrew role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

http://docs.brew.sh/Installation.html#alternative-installs
http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by rfay** [comment]
Thanks so much for your maintenance of this @iMichka . I confirm that I can now `brew upgrade mingw-w64` (and makensis, which is how I got here)

Per your comment 
> Consider installing Linuxbrew in /home/linuxbrew/.linuxbrew/

I've never installed Linuxbrew anywhere else, all the (many) systems I tested on have it there.

**Pull request closed without merging**
