### PR TITLE
ttyd: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.15.2/bin/cmake -E cmake_link_script CMakeFiles/ttyd.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-5  -D_GNU_SOURCE -DNDEBUG  -rdynamic CMakeFiles/ttyd.dir/src/server.c.o CMakeFiles/ttyd.dir/src/http.c.o CMakeFiles/ttyd.dir/src/protocol.c.o CMakeFiles/ttyd.dir/src/utils.c.o  -o ttyd -lpthread -lssl -lcrypto /home/linuxbrew/.linuxbrew/lib/libwebsockets.a /home/linuxbrew/.linuxbrew/lib/libwebsockets.so.15 -ljson-c -lutil -lssl -lcrypto -luv -levent -lm 
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libwebsockets.a(unix-plugins.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/ttyd.dir/build.make:144: recipe for target 'ttyd' failed
make[2]: *** [ttyd] Error 1
make[2]: Leaving directory '/tmp/ttyd-20190818-29976-1bohvda/ttyd-1.5.2'
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/ttyd.dir/all' failed
make[1]: *** [CMakeFiles/ttyd.dir/all] Error 2
make[1]: Leaving directory '/tmp/ttyd-20190818-29976-1bohvda/ttyd-1.5.2'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by iMichka** [comment]
> libwebsockets.a

Maybe we need a shared library for `libwebsockets`?

**Comment by iMichka** [comment]
Actually there is a shared library:

```
ls /home/linuxbrew/.linuxbrew/Cellar/libwebsockets/3.2.0/lib/
cmake  libwebsockets.a  libwebsockets.so  libwebsockets.so.15  pkgconfig
```

Why does it try to pick up libwebsockets.a ...

**Comment by issyl0** [comment]
I have no idea how this is supposed to be fixed. Closing for now.

**Pull request closed without merging**
