### PR TITLE
Standalone Postgresql Migration runner

### PR DESCRIPTION
**Pull request by turbo-cafe**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by turbo-cafe** [comment]
Which project accepts Formulae for binary packages?

**Comment by turbo-cafe** [comment]
some CI action complained about project not being notable enough. Which is not necessarily true, because [pgmig](https://github.com/leafclick/pgmig) is native build script for [migratus](https://github.com/yogthos/migratus). The latter is quite popular, but author distributes it as jar file only.

**Comment by iMichka** [comment]
On Mac, we accept binary packages at https://github.com/Homebrew/homebrew-cask.
On Linux we do not accept any binary package for the time being, that still needs to be maintained and implemented.

**Comment by iMichka** [comment]
Sorry we will have to pass on this for this repo.

**Pull request closed without merging**
