### PR TITLE
terraform: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by issyl0** [comment]
This PR is trying to build a bottle for version 0.12.0, when the [latest version in master is 0.12.1](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/terraform.rb#L4) from 5 days ago.

If we try and build the newer version it might succeed?

**Comment by issyl0** [comment]
I succeeded in getting this to build by removing `make test` from the formula. I'm not sure that's how it's supposed to be done, because indeed the [Terraform build docs](https://github.com/hashicorp/terraform/blob/master/BUILDING.md) say `make test` is a legitimate step after "tools" and before "bin". Now to find out what's _wrong_ with the tests.

**Comment by BenLiyanage** [comment]
Just for clarity, this is the line to remove `test` from:

https://github.com/Homebrew/linuxbrew-core/pull/13309/files#diff-894421d9cc7cc4f146506e6b88b2f780R38

Can confirm that this fixes the formula.   Wish I grabbed a copy of my make log before trying that.  Maybe circleci has a copy?

**Comment by iMichka** [comment]
Rebase to test the build with the newest version

**Comment by iMichka** [comment]
I disabled the tests. If anybody needs the tests. feel free to fix them, so that we can re-enable them. But I do not think they are critical.

**Pull request closed without merging**
