### PR TITLE
infer: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
# Run eval $(opam env) to update the current shell environment
2019-12-24T09:18:36.5782867Z [34m==>[0m [1mopam exec -- ./build-infer.sh all --yes --user-opam-switch[0m
2019-12-24T09:18:53.4420839Z initializing opam... 
2019-12-24T09:18:53.4422431Z 
2019-12-24T09:18:53.4422785Z installing infer dependencies; this can take up to 30 minutes... 
2019-12-24T09:18:53.4423767Z [WARNING] Lock file opam.locked is outdated, you may want to re-run opam lock:
2019-12-24T09:18:53.4424115Z           Dependencies present in opam file not in lock file:
2019-12-24T09:18:53.4424577Z             - utop
2019-12-24T09:18:53.4424831Z 
2019-12-24T09:18:53.4425458Z The following dependencies couldn't be met:
2019-12-24T09:18:53.4426289Z   - infer â†’ camlp4 = 4.07+1
2019-12-24T09:18:53.4426556Z       conflict with the base packages of this switch
2019-12-24T09:18:53.4426841Z 
2019-12-24T09:18:53.4427083Z No solution found, exiting
2019-12-24T09:18:53.4427724Z 'opam install --deps-only infer /tmp/infer-20191224-17305-1qf9dl7 --locked' failed.
2019-12-24T09:18:53.4427957Z 
2019-12-24T09:18:53.4428193Z *** `install_opam_deps` failed
2019-12-24T09:18:53.4428503Z *** Updating opam then retrying
2019-12-24T09:18:53.4428908Z 
2019-12-24T09:18:53.4429114Z <><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
2019-12-24T09:18:53.4429355Z Processing  1/1: [default: http]
2019-12-24T09:18:53.4429564Z [default] no changes from https://opam.ocaml.org
2019-12-24T09:18:53.4430353Z [WARNING] Lock file opam.locked is outdated, you may want to re-run opam lock:
2019-12-24T09:18:53.4430608Z           Dependencies present in opam file not in lock file:
2019-12-24T09:18:53.4431329Z             - utop
2019-12-24T09:18:53.4433117Z 
2019-12-24T09:18:53.4433704Z The following dependencies couldn't be met:
2019-12-24T09:18:53.4434225Z   - infer â†’ camlp4 = 4.07+1
2019-12-24T09:18:53.4434484Z       conflict with the base packages of this switch
2019-12-24T09:18:53.4434701Z 
2019-12-24T09:18:53.4434903Z No solution found, exiting
2019-12-24T09:18:53.4435734Z 'opam install --deps-only infer /tmp/infer-20191224-17305-1qf9dl7 --locked' failed.
2019-12-24T09:18:53.4435985Z 
2019-12-24T09:18:53.4436181Z *** ERROR: `install_opam_deps` failed
2019-12-24T09:19:00.0960195Z 
2019-12-24T09:19:00.0967635Z [34m==>[0m [1mFormula[0m
2019-12-24T09:19:00.0968599Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/infer.rb
```

**Comment by dawidd6** [comment]
@iMichka uses `python@2` here.

**Comment by dawidd6** [comment]
```
tar (child): xz: Cannot exec: No such file or directory
```

**Comment by dawidd6** [comment]
```
[*ERROR**][102172] Uncaught Internal Error: (Sys_error "/etc/localtime: No such file or directory")
```

**Comment by dawidd6** [comment]
```
echo "ERROR: ldd (Linux?) found but not patchelf, please install patchelf" >&2; exit 1
ERROR: ldd (Linux?) found but not patchelf, please install patchelf
Makefile:673: recipe for target 'install-with-libs' failed
make: *** [install-with-libs] Error 1
```

**Comment by iMichka** [comment]
```
2020-01-06T20:11:15.2252723Z [31mError:[0m --keep-old was passed but there are changes in:
2020-01-06T20:11:15.2253540Z cellar: old: :any, new: "/home/linuxbrew/.linuxbrew/Cellar"
2020-01-06T20:11:15.2321372Z ==> [1m[31mFAILED[0m[0m
2020-01-06T20:11:15.2321788Z 
2020-01-06T20:11:15.2322620Z [34m==>[0m [1mbrew linkage --test infer[0m
2020-01-06T20:11:16.1282182Z Unwanted system libraries:
2020-01-06T20:11:16.1285101Z   /lib/x86_64-linux-gnu/libz.so.1
2020-01-06T20:11:16.1286131Z   /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
2020-01-06T20:11:16.1287203Z ==> [1m[31mFAILED[0m[0m
```

**Pull request closed without merging**
