### PR TITLE
mapserver: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-12-26T11:52:34.8878525Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `PDFDoc::getNumPages()'
2019-12-26T11:52:34.8879002Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `Stream::getPSFilter(int, char const*)'
2019-12-26T11:52:34.8879495Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `SplashOutputDev::paintTransparencyGroup(GfxState*, double const*)'
2019-12-26T11:52:34.8880132Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `SplashOutputDev::unsetSoftMaskFromImageMask(GfxState*, double*)'
2019-12-26T11:52:34.8880595Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `XRef::getCatalog()'
2019-12-26T11:52:34.8881087Z /home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `SplashOutputDev::updateStrokeOpacity(GfxState*)'
2019-12-26T11:52:34.8881305Z collect2: error: ld returned 1 exit status
2019-12-26T11:52:34.8881656Z CMakeFiles/shptreetst.dir/build.make:100: recipe for target 'shptreetst' failed
2019-12-26T11:52:34.8881873Z make[2]: *** [shptreetst] Error 1
2019-12-26T11:52:34.8882242Z make[2]: Leaving directory '/tmp/mapserver-20191226-67632-1pci1v9/mapserver-7.4.2/build'
2019-12-26T11:52:34.8882711Z CMakeFiles/Makefile2:120: recipe for target 'CMakeFiles/shptreetst.dir/all' failed
2019-12-26T11:52:34.8882926Z make[1]: *** [CMakeFiles/shptreetst.dir/all] Error 2
2019-12-26T11:52:34.8883429Z make[1]: Leaving directory '/tmp/mapserver-20191226-67632-1pci1v9/mapserver-7.4.2/build'
2019-12-26T11:52:34.8883828Z Makefile:132: recipe for target 'all' failed
2019-12-26T11:52:34.8884032Z make: *** [all] Error 2
2019-12-26T11:52:35.2842949Z 
2019-12-26T11:52:35.2845185Z [34m==>[0m [1mFormula[0m
2019-12-26T11:52:35.2846427Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mapserver.rb
```

**Comment by dawidd6** [comment]
```
/usr/bin/ld: warning: libpoppler.so.91, needed by /home/linuxbrew/.linuxbrew/lib/libgdal.so, not found (try using -rpath or -rpath-link)
/home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `SplashOutputDev::type3D1(GfxState*, double, double, double, double, double, double)'
/home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `Array::getNF(int) const'
/home/linuxbrew/.linuxbrew/lib/libgdal.so: undefined reference to `SplashOutputDev::endType3Char/(GfxState*usr)/'bin
/
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/18510

**Comment by iMichka** [comment]
This will come back once gdal has been updated.

**Pull request closed without merging**
