### PR TITLE
idris2: fix Linux build

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

@iMichka is this the best way to handle the `.dylib/.so` difference without using `OS.mac?`, or is there a more concise way?  There are many formula that will need a similar fix.

### CODE REVIEW

**Comment by dawidd6** [comment]
You can use `shared_library` for this:

https://github.com/Homebrew/brew/blob/d9064eb65d700270f1aade5dc3adc036a1160a18/Library/Homebrew/test/os/linux/formula_spec.rb#L105

**Comment by danielnachun** [comment]
Awesome, this is super useful.  Thanks @dawidd6!

**Comment by iMichka** [comment]
I had to skip the self-hosted job, you'll need to rebase.

**Comment by danielnachun** [comment]
Okay thanks!

**Pull request merged**
