### PR TITLE
mlton: Fix build for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Needed by `mlkit`

**Comment by dawidd6** [comment]
I guess those are the errors:
```
/tmp/mlton-20210205-12593-a29fqw/mlton-20210117/bootstrap/lib/mlton/mlton-compile: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/mlton-20210205-12593-a29fqw/mlton-20210117/bootstrap/lib/mlton/mlton-compile)
/tmp/mlton-20210205-12593-a29fqw/mlton-20210117/bootstrap/lib/mlton/mlton-compile: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/mlton-20210205-12593-a29fqw/mlton-20210117/bootstrap/lib/mlton/mlton-compile)
```

**Comment by danielnachun** [comment]
I think the problem here is that the bootstrap binaries were built against `glibc` 2.27 and we have 2.23 right now in CI. We could either open an issue upstream asking them to provide binaries built against an older `glibc`, or see if we can use an older version for bootstrapping that was built against `glibc` 2.23 or older.

**Comment by iMichka** [comment]
I'm not working on this.

**Pull request closed without merging**
