### PR TITLE
mpv: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-09-25T20:33:34.9468637Z ==> ./bootstrap.py
2019-09-25T20:33:34.9497796Z .
2019-09-25T20:33:34.9498203Z Last 150 lines from /home/vsts_azpcontainer/.cache/Homebrew/Logs/mpv/01.bootstrap.py:
2019-09-25T20:33:34.9524169Z 2019-09-25 20:33:34 +0000
2019-09-25T20:33:34.9524471Z 
2019-09-25T20:33:34.9524563Z ./bootstrap.py
2019-09-25T20:33:34.9524697Z 
2019-09-25T20:33:34.9525033Z /usr/bin/env: 'python': No such file or directory
2019-09-25T20:33:35.5863500Z 
2019-09-25T20:33:35.5865593Z ==> Formula
2019-09-25T20:33:35.5867032Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpv.rb
```

**Comment by dawidd6** [comment]
```
==> brew bottle --merge --write --no-commit ./mpv--0.29.1_3.x86_64_linux.bottle.json --keep-old
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
==> mpv
==> FAILED
```

**Comment by iMichka** [comment]
`mpv`  was removed in https://github.com/Homebrew/homebrew-core/pull/44282.

**Comment by iMichka** [comment]
Removed in ea8bf6070b94c8772df08a878457abef45a04887

**Pull request closed without merging**
