### PR TITLE
grin: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-11-22T20:51:05.2768563Z --- stderr
2019-11-22T20:51:05.2769242Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/ia32intrin.h:104:1: error: definition of builtin function '__rdtsc'
2019-11-22T20:51:05.2770106Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:127:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2770718Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:133:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2771345Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:139:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2772749Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:145:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2773402Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:239:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values)
2019-11-22T20:51:05.2774032Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:245:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values)
2019-11-22T20:51:05.2774655Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:251:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values)
2019-11-22T20:51:05.2775420Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:257:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values)
2019-11-22T20:51:05.2776165Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:285:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2776811Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:295:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2777446Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:323:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2778070Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:333:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2778696Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:377:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2779316Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:383:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2779918Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:407:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2780562Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:413:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2781323Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:599:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2782453Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/xmmintrin.h:615:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
2019-11-22T20:51:05.2782963Z fatal error: too many errors emitted, stopping now [-ferror-limit=]
2019-11-22T20:51:05.2783491Z /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_5/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/include/ia32intrin.h:104:1: error: definition of builtin function '__rdtsc', err: true
```

**Comment by iMichka** [comment]
Looks like it did not use llvm for the build :(

**Comment by dawidd6** [comment]
Any ideas how to solve this?

**Comment by dawidd6** [comment]
Can't fix it.

**Pull request closed without merging**
