### PR TITLE
libmagic: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by issyl0** [comment]
```
==> brew test libmagic --verbose
Testing libmagic
==> /usr/bin/gcc -I/home/linuxbrew/.linuxbrew/Cellar/libmagic/5.38/include -L/home/linuxbrew/.linuxbrew/Cellar/libmagic/5.38/lib -lmagic test.c -o test
/tmp/ccNeDVRt.o: In function `main':
test.c:(.text+0x15): undefined reference to `magic_open'
test.c:(.text+0x4a): undefined reference to `magic_load'
test.c:(.text+0x81): undefined reference to `magic_file'
collect2: error: ld returned 1 exit status
```

**Comment by dawidd6** [comment]
So, the order of passed arguments to `gcc` matters? That's ridiculous.

**Comment by iMichka** [comment]
Let me tell you a quick Christmas story.

Once upon a time ... I was also wondering why the order was important.

And @sjackman found the answer:

@sjackman:
> That's it! I've found the smoking gun!

Some obscure issue somewhere on internet:
> > Also in Natty, ld runs with the --as-needed option enabled by default. This means that, in the example above, if no symbols from libwheel were needed by racetrack, then libwheel would not be linked even if it was explicitly included in the command-line compiler flags. NOTE: The ld --as-needed default was reverted for the final natty release, and will be re-enabled in the o-series.
https://wiki.ubuntu.com/NattyNarwhal/ToolchainTransition
So Ubuntu has since Ubuntu 11.10 (Oneiric Ocelot) enabled `ld --as-needed` by default, which causes this difference in default behaviour.

You'll find all the explanations in the link. Have fun reading some computer history from 2010/2011 :)

**Comment by dawidd6** [comment]
TIL. Thanks for the lecture. I still think that's unnecessary complexity tho.

**Comment by iMichka** [comment]
Yes, it sort of sucks. The fix is quite easy though.

I also think that the Ubuntu order could be used on mac (it should work). Back then homebrew-core would not accept these kind of updates, but this may have changed now. But this will only work if we enforce the order with an audit check for test blocks.

**Comment by iMichka** [comment]
As not some nay formulae are impacted right now, the manual workaround will be enough ...

**Comment by sjackman** [comment]
It's quite a pain for us that Ubuntu enabled `ld --as-needed` by default, whereas macOS and most other Linux distributions do not (including I believe Debian), so Ubuntu is the weird kid. That means that often Makefiles developed on say Debian then fail on Ubuntu because the order of libraries matters on Ubuntu but not on Debian. It's a pain. So long as we have users running on Ubuntu though and using Ubuntu's `ld`, will need to make these fixes. One possible fix would be to strictly require brewed `binutils` on Ubuntu.

**Pull request closed without merging**
