### PR TITLE
subversion: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
configure: Configuring python swig binding
checking for Python includes... -I/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16/include/python2.7
checking for compiling Python extensions... (cached) /usr/bin/gcc-5
checking for linking Python extensions... cc -pthread -shared -L/home/linuxbrew/.linuxbrew/lib
checking for linking Python libraries... -L/home/linuxbrew/.linuxbrew/lib
checking for apr_int64_t Python/C API format string... 
configure: error: failed to recognize APR_INT64_T_FMT on this platform

==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/subversion.rb

**Comment by JuPlutonic** [comment]
I thing only change we need to get the bottle is to add to line with serf postconditional `if mac.os?`
[Gistlog's](https://gist.github.com/7ee09272f9dbeb3f688f6fea35299ba1) 03.configure file says about it on 70-77 lines and surf isn't connected to our Hashicorp's Serf&Hombrew-formula.

**Comment by mxplusb** [comment]
I can confirm I hit this issue in WSL on Windows 10 1809 17763.437

```bash
 % brew install subversion
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.12.0.tar.bz2
==> Downloading from http://mirrors.sonic.net/apache/subversion/subversion-1.12.0.tar.bz2
######################################################################## 100.0%
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
==> Downloading from http://mirrors.gigenet.com/apache/serf/serf-1.3.9.tar.bz2
######################################################################## 100.0%
==> scons PREFIX=/home/mike/.linuxbrew/Cellar/subversion/1.12.0 GSSAPI=/home/mike/.linuxbrew/opt/krb5 CC=/home/mike/.linuxbrew/bin/gcc-5 CFLA==> scons install
==> ./configure --prefix=/home/mike/.linuxbrew/Cellar/subversion/1.12.0 --enable-optimize --disable-mod-activation --disable-plaintext-passwoLast 15 lines from /home/mike/.cache/Homebrew/Logs/subversion/03.configure:
checking for /home/mike/.linuxbrew/opt/ruby/bin/ruby... /home/mike/.linuxbrew/opt/ruby/bin/ruby
checking rb_hash_foreach... yes
checking for rdoc... /c/tools/ruby24/bin/rdoc
checking for Ruby major version... 2
checking for Ruby minor version... 6
checking for Ruby teeny version... 3
checking for swig... /home/mike/.linuxbrew/bin/swig
checking swig version... 4.0.0
configure: Configuring python swig binding
checking for Python includes... -I/home/mike/.linuxbrew/Cellar/python@2/2.7.16/include/python2.7
checking for compiling Python extensions... (cached) /home/mike/.linuxbrew/bin/gcc-5
checking for linking Python extensions... gcc-5 -pthread -shared -L/home/mike/.linuxbrew/lib
checking for linking Python libraries... -L/home/mike/.linuxbrew/lib
checking for apr_int64_t Python/C API format string...
configure: error: failed to recognize APR_INT64_T_FMT on this platform

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
subversion: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/12828
```

**Comment by iMichka** [comment]
This has been fixed by #13100

**Pull request closed without merging**
