### PR TITLE
patchelf: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
@sjackman this fails with:

```
configure: WARNING: unrecognized options: --disable-debug
==> make install
Making install in src
make[1]: Entering directory `/tmp/patchelf-20190515-4176-yt246u/patchelf-0.10/src'
g++ -DPACKAGE_NAME=\"patchelf\" -DPACKAGE_TARNAME=\"patchelf\" -DPACKAGE_VERSION=\"0.10\" -DPACKAGE_STRING=\"patchelf\ 0.10\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"patchelf\" -DVERSION=\"0.10\" -DPAGESIZE=4096 -I.    -Wall -std=c++11 -D_FILE_OFFSET_BITS=64 -static-libgcc -static-libstdc++ -c -o patchelf.o patchelf.cc
g++: unrecognized option '-static-libstdc++'
cc1plus: error: unrecognized command line option "-std=c++11"
make[1]: *** [patchelf.o] Error 1
make[1]: Leaving directory `/tmp/patchelf-20190515-4176-yt246u/patchelf-0.10/src'
make: *** [install-recursive] Error 1
```

in centos 6

**Comment by iMichka** [comment]
I will remove --disable-debug and static-libstdc++. I already cleaned up the formula and removed other deprecated options.

I am a little bit concerned by the "-std=c++11" flag ...

**Comment by sjackman** [comment]
The resulting executable cannot be dynamically linked against `libstdc++`, so `CXXFLAGS=-static-libgcc -static-libstdc++` is necessary. This bottle must be built to be portable on either `centos:6` or possibly `debian:7` (Wheezy).
See https://github.com/Linuxbrew/brew/wiki/Build-a-portable-bottle
and https://github.com/Linuxbrew/brew/wiki/Bottles

**Comment by sjackman** [comment]
> I am a little bit concerned by the "-std=c++11" flag ...

That's weird. Is it due to a change to Homebrew/brew?

**Comment by iMichka** [comment]
No. This is coming from there: https://github.com/NixOS/patchelf/blob/master/src/Makefile.am

I am trying to build this in the centos 6 docker image. The error message posted above comes from there.

**Comment by sjackman** [comment]
Let's try removing `-std=c++11` and see what happens. If that doesn't work, we could build it with the brewed `gcc` (though I'd rather use the host's).

**Comment by iMichka** [comment]
> Let's try removing -std=c++11 and see what happens.

I tried. It then asks for automake. We can not add that dependency (because it generates a dependency cycle).

**Comment by iMichka** [comment]
With `inreplace "src/Makefile.am", "std=c++11 ", ""`

```
==> make install
Making install in src
make[1]: Entering directory `/tmp/patchelf-20190515-4879-1cxigs5/patchelf-0.10/src'
 cd .. && /bin/sh /tmp/patchelf-20190515-4879-1cxigs5/patchelf-0.10/build-aux/missing automake-1.16 --foreign src/Makefile
/tmp/patchelf-20190515-4879-1cxigs5/patchelf-0.10/build-aux/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make[1]: *** [Makefile.in] Error 127
make[1]: Leaving directory `/tmp/patchelf-20190515-4879-1cxigs5/patchelf-0.10/src'
make: *** [install-recursive] Error 1
```

**Comment by sjackman** [comment]
Try instead…
```ruby
inreplace "src/Makefile.in", "std=c++11 ", ""
```

**Comment by iMichka** [comment]
Right, I had to use:
`inreplace "src/Makefile.in", "-std=c++11 -D_FILE_OFFSET_BITS=64", ""`; because the second flag is also not recognized.

Some new errors after that change:
```
==> make install
Making install in src
make[1]: Entering directory `/tmp/patchelf-20190515-6407-efyjar/patchelf-0.10/src'
g++ -DPACKAGE_NAME=\"patchelf\" -DPACKAGE_TARNAME=\"patchelf\" -DPACKAGE_VERSION=\"0.10\" -DPACKAGE_STRING=\"patchelf\ 0.10\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"patchelf\" -DVERSION=\"0.10\" -DPAGESIZE=4096 -I.    -Wall  -static-libgcc -static-libstdc++ -c -o patchelf.o patchelf.cc
g++: unrecognized option '-static-libstdc++'
patchelf.cc:51: error: expected initializer before ‘<’ token
patchelf.cc: In function ‘bool hasAllowedPrefix(const std::string&, const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
patchelf.cc:76: error: expected initializer before ‘:’ token
patchelf.cc:78: error: expected primary-expression before ‘return’
patchelf.cc:78: error: expected ‘;’ before ‘return’
patchelf.cc:78: error: expected primary-expression before ‘return’
patchelf.cc:78: error: expected ‘)’ before ‘return’
patchelf.cc: At global scope:
patchelf.cc:93: error: ‘FileContents’ does not name a type
patchelf.cc:105: error: ISO C++ forbids initialization of member ‘changed’
patchelf.cc:105: error: making ‘changed’ static
patchelf.cc:105: error: ISO C++ forbids in-class initialization of non-const static member ‘changed’
patchelf.cc:107: error: ISO C++ forbids initialization of member ‘isExecutable’
patchelf.cc:107: error: making ‘isExecutable’ static
patchelf.cc:107: error: ISO C++ forbids in-class initialization of non-const static member ‘isExecutable’
patchelf.cc:118: error: ISO C++ forbids initialization of member ‘sectionAlignment’
patchelf.cc:118: error: making ‘sectionAlignment’ static
patchelf.cc:118: error: ISO C++ forbids in-class initialization of non-const static member ‘sectionAlignment’
patchelf.cc:124: error: expected ‘)’ before ‘fileContents’
patchelf.cc:308: error: variable or field ‘growFile’ declared void
patchelf.cc:308: error: ‘FileContents’ was not declared in this scope
patchelf.cc:308: error: expected primary-expression before ‘newSize’
patchelf.cc:316: error: ‘FileContents’ does not name a type
patchelf.cc:356: error: ISO C++ forbids declaration of ‘FileContents’ with no type
patchelf.cc:356: error: expected ‘,’ or ‘...’ before ‘&’ token
patchelf.cc: In function ‘ElfType getElfType(int)’:
patchelf.cc:359: error: ‘fileContents’ was not declared in this scope
patchelf.cc:361: error: ISO C++ forbids declaration of ‘contents’ with no type
patchelf.cc:361: error: ‘fileContents’ was not declared in this scope
patchelf.cc:363: error: invalid conversion from ‘int’ to ‘const void*’
patchelf.cc:363: error:   initializing argument 1 of ‘int memcmp(const void*, const void*, size_t)’
patchelf.cc:366: error: invalid types ‘int[int]’ for array subscript
patchelf.cc:369: error: invalid types ‘int[int]’ for array subscript
patchelf.cc:369: error: invalid types ‘int[int]’ for array subscript
patchelf.cc:372: error: invalid types ‘int[int]’ for array subscript
patchelf.cc: At global scope:
patchelf.cc:379: error: ISO C++ forbids declaration of ‘FileContents’ with no type
patchelf.cc:379: error: expected ‘,’ or ‘...’ before ‘&’ token
patchelf.cc: In function ‘void checkPointer(int)’:
patchelf.cc:381: error: ‘p’ was not declared in this scope
patchelf.cc:382: error: ‘contents’ was not declared in this scope
patchelf.cc:382: error: ‘size’ was not declared in this scope
patchelf.cc: At global scope:
patchelf.cc:387: error: expected constructor, destructor, or type conversion before ‘(’ token
patchelf.cc:498: error: ‘FileContents’ has not been declared
patchelf.cc: In function ‘void writeFile(std::string, int)’:
patchelf.cc:506: error: base operand of ‘->’ is not a pointer
patchelf.cc:506: error: base operand of ‘->’ is not a pointer
patchelf.cc:509: error: base operand of ‘->’ is not a pointer
patchelf.cc: In member function ‘void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Verneed>::shiftFile(unsigned int, Elf_Addr)’:
patchelf.cc:528: error: ‘fileContents’ was not declared in this scope
patchelf.cc:530: error: there are no arguments to ‘growFile’ that depend on a template parameter, so a declaration of ‘growFile’ must be available
patchelf.cc:530: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
patchelf.cc: In member function ‘void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Verneed>::writeReplacedSections(Elf_Off&, Elf_Addr, Elf_Off)’:
patchelf.cc:642: error: expected initializer before ‘:’ token
patchelf.cc:649: error: expected primary-expression before ‘for’
patchelf.cc:649: error: expected ‘;’ before ‘for’
patchelf.cc:649: error: expected primary-expression before ‘for’
patchelf.cc:649: error: expected ‘)’ before ‘for’
patchelf.cc:649: error: expected initializer before ‘:’ token
patchelf.cc:1767: error: expected primary-expression at end of input
patchelf.cc:1767: error: expected ‘;’ at end of input
patchelf.cc:1767: error: expected primary-expression at end of input
patchelf.cc:1767: error: expected ‘)’ at end of input
patchelf.cc:1767: error: expected statement at end of input
patchelf.cc:1767: error: expected ‘}’ at end of input
make[1]: *** [patchelf.o] Error 1
make[1]: Leaving directory `/tmp/patchelf-20190515-6407-efyjar/patchelf-0.10/src'
make: *** [install-recursive] Error 1
```

**Comment by sjackman** [comment]
`-D_FILE_OFFSET_BITS=64` is definitely recognized by all versions of GCC.

**Comment by iMichka** [comment]
The bottle was built with debian 7, using glibc 2.13 and gcc 4.7.

I will update the documentation accordingly.

**Comment by sjackman** [comment]
Thank you, Michka!

**Comment by sjackman** [comment]
```console
$ brew upgrade patchelf
$ patchelf --version
-bash: /gsc/btl/linuxbrew/bin/patchelf: /home/linuxbrew/.linuxbrew/lib/ld.so: bad ELF interpreter: No such file or directory
```
😢 

`patchelf` is special in that it's _not_ relocated by `keg_relocate`, because `patchelf` can't (easily) relocate its own executable. (a workaround would be possible)
So the interpreter must be set to `/lib64/ld-linux-x86-64.so.2` rather than `/home/linuxbrew/.linuxbrew/lib/ld.so`.
The hacktastic fix for now is to download the bottle, extract it, change the interpreter with `patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 patchelf/0.10/bin/patchelf`, tar it up again, and replace the bottle on Bintray.
A permanent fix involves this code:
https://github.com/Homebrew/brew/blob/3dc3ab97dc9afb63f235fdc1c0c8ef217f735685/Library/Homebrew/extend/os/linux/keg_relocate.rb#L44-L48
A hack fix like `new_interpreter = "/lib64/ld-linux-x86-64.so.2" if File.basename(name) == "patchelf"` is possible.

**Comment by sjackman** [comment]
Fixed in PR https://github.com/Homebrew/linuxbrew-core/pull/13099

**Pull request closed without merging**
