### PR TITLE
awscli: pin botocore dependency

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Fixes https://github.com/Homebrew/linuxbrew-core/issues/23564, https://github.com/Homebrew/linuxbrew-core/issues/23867

**Comment by dawidd6** [comment]
I think we want to backport this to homebrew-core

**Comment by 4ndr4s** [comment]
@dawidd6 @iMichka do we have any eta for this ?

**Comment by dawidd6** [comment]
This is actually a hack and I think upstream should be pinning this dependency, not us. This line is going to need to be updated every time awscli is bumped. Dunno if this is really the best approach here.

**Comment by yermulnik** [comment]
Should regular homebrew/awscli users like me apply this fix manually at the moment as a temporary solution or wait (indefinitely?) for the upstream to resolve this properly?

**Comment by yermulnik** [comment]
BTW, the fix from this PR didn't resolve the issue for me locally =(
```
> brew edit awscli
[added `inreplace` line from thjis PR]

> > brew upgrade
==> Upgrading 1 outdated package:
awscli 2.2.18 -> 2.2.20
==> Upgrading awscli
  2.2.18 -> 2.2.20

==> Downloading https://github.com/aws/aws-cli/archive/2.2.20.tar.gz
Already downloaded: /home/giermulnik/.cache/Homebrew/downloads/6ad560fb45e2950bd3464100a1e41a1f5100bc8151624b84846f20900e751148--aws-cli-2.2.20.tar.gz
==> python3 -m venv --system-site-packages /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.20/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/awscli/2.2.20/libexec/bin/pip install -v -r requirements.txt --ignore-installe
Last 15 lines from /home/giermulnik/.cache/Homebrew/Logs/awscli/02.pip:
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=ExplicitRequirement(LinkCandidate('https://github.com/boto/botocore/zipball/253d303b536eace7103731b8aa8a2b37cc118f0a#egg=botocore')), parent=None), RequirementInformation(requirement=SpecifierRequirement('botocore==2.0.0dev128'), parent=LinkCandidate('file:///tmp/awscli-20210722-193493-16e15qp/aws-cli-2.2.20'))]

The above exception was the direct cause of the following exception:
[…]
```
Any clue?

**Comment by iMichka** [comment]
I don't understand how this built correctly in hombrew-core but not here. I think this should be reported upstream nevertheless first.

**Comment by jonchang** [comment]
> I don't understand how this built correctly in hombrew-core but not here. I think this should be reported upstream nevertheless first.

We don't build awscli for linuxbrew-core at the same time as homebrew-core. The dependency graph changes out from under us since awscli and its dependent packages change so quickly The solution is to pin the dependency graph explicitly with `resource` blocks and have `brew update-python-resources` do the magic of figuring out the right dependencies.

**Comment by dawidd6** [comment]
`brew update-python-resources` resolves only pypi packages AFAIK and botocore v2 is not available on pypi.

**Comment by imranh2** [comment]
The correct version to pin to is `b65ed1e4d06b61f97809c20aba8a5bcc718990d1` for awscli=2.2.20

So 
```
inreplace "requirements.txt", "/v2", "/b65ed1e4d06b61f97809c20aba8a5bcc718990d1"
```

**Comment by yermulnik** [comment]
@imranh2 That did the trick. Thanks a lot!

**Comment by yermulnik** [comment]
Just updating for those who seek for the latest version (20210724):
```
inreplace "requirements.txt", "/v2", "/54f3412f16b92c8b190053edf458125419c23d79"
```

**Comment by iMichka** [comment]
The latests versions of `awscli` have been bottled; so this does not seem to be an issue anymore.

**Pull request closed without merging**
