### PR TITLE
workflows: add two-branch workflow

### PR DESCRIPTION
**Pull request by jonchang**
Here is the proposed workflow, prototyped in brewsci/homebrew-bio and imported here. The idea is to have a branch `develop` which is always in lockstep with `master`. When a pull request needing bottles is opened, GitHub actions will kick off the `Build bottles` job, which does not have permissions to access `secrets` as it is fork pull request.

A maintainer will then merge that pull request into the `develop` branch, which kicks off the second job, `Upload bottles`, which *does* have permissions and can upload and publish bottles. Then the job will squash merge the new formula and bottle onto `master` and attempt to push to `origin`; if this fails, the job will instead open a pull request so a maintainer can manually resolve the conflict.

### CODE REVIEW

**Comment by dawidd6** [comment]
What happens, if maintainer merges multiple PRs quickly one after another? This might be problematic, cause workflows are run simultaneously.

**Comment by jonchang** [comment]
In this case, the push to `master` will fail, and the CI job will open a pull request so a maintainer can manually resolve the conflict.

**Comment by dawidd6** [comment]
Do we do merges to `develop` branch with this workflow?

**Comment by jonchang** [comment]
> Do we do merges to `develop` branch with this workflow?

For now, yes; I think in the future we will make changes to Homebrew/brew so users will update to `stable` and pull requests happen against `master`. It is fairly easy to change the base branch on pull requests so it shouldn't be too tricky to avoid merging to `master` for now.

**Comment by issyl0** [comment]
> > Do we do merges to `develop` branch with this workflow?
> 
> For now, yes; I think in the future we will make changes to Homebrew/brew so users will update to `stable` and pull requests happen against `master`. It is fairly easy to change the base branch on pull requests so it shouldn't be too tricky to avoid merging to `master` for now.

"It's fairly easy" but there's not particularly good messaging around it in GitHub (the branch isn't very visible on PRs) and there's potential for human error. I'll make some edits to `brew merge-homebrew`, I guess, to support this.

**Comment by jonchang** [comment]
> "It's fairly easy" but there's not particularly good messaging around it in GitHub (the branch isn't very visible on PRs) and there's potential for human error. I'll make some edits to brew merge-homebrew, I guess, to support this.

Michka has a change to `brew build-bottle-pr` that correctly sets the base branch.

**Comment by issyl0** [comment]
> > "It's fairly easy" but there's not particularly good messaging around it in GitHub (the branch isn't very visible on PRs) and there's potential for human error. I'll make some edits to brew merge-homebrew, I guess, to support this.
> 
> Michka has a change to `brew build-bottle-pr` that correctly sets the base branch.

I think we may be talking about different things. Are you talking about bottle PRs, or Homebrew => Linuxbrew merges? I was talking about the latter (and I thought Dawid was too).

**Comment by jonchang** [comment]
> I think we may be talking about different things. Are you talking about bottle PRs, or Homebrew => Linuxbrew merges? I was talking about the latter (and I thought Dawid was too).

Yeah I'm talking bottle pull requests. I don't know where core merges would need to go... I think it can still be master for now?

**Pull request merged**
