### PR TITLE
joplin: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by issyl0**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
npm info lifecycle sharp@0.22.1~install: sharp@0.22.1

> sharp@0.22.1 install /home/linuxbrew/.linuxbrew/Cellar/joplin/1.0.141/libexec/lib/node_modules/joplin/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

ERR! sharp EACCES: permission denied, mkdir '/root/.cache/Homebrew/npm_cache'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
```

**Comment by issyl0** [comment]
I rebased this on master to account for the [latest version of the `joplin` formula](https://github.com/Homebrew/linuxbrew-core/commit/1eab5e757d034100bc20f062e36d397afaeac437) that was merged just now. Nothing changed on the NodeJS side, but let's try building this again anyway. It installs fine locally, so we could always manually run `brew test-bot` and push the bottle.

**Comment by issyl0** [comment]
It really didn't like the rebase, as upstream removed the Python2 dependency. :scream: I've reinstated it for Linux... :crossed_fingers:

**Comment by issyl0** [comment]
Still the same error as originally.

**Comment by issyl0** [comment]
No users have complained about this so I’m going to close it for now as I’ve not worked on it in a while.

**Pull request closed without merging**
