### PR TITLE
llvm: make libc++ fully independent of GCC

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
@chandlerc I started working on backporting your fixes to older versions of LLVM and ended up going to down a crazy rabbit hole that ended with several additional improvements to our current LLVM formula.

1) I was able to fully remove the dependency of `libc++` on `libgcc`.  The reason we were still pulling that dependency in was because we also needed to specify `-DLIBUNWIND_USE_COMPILER_RT=ON` (which I thought didn't exist - it does but is not well documented).

2) I was able to remove the dependency on `libatomic` by adding `-DLIBCXX_HAS_ATOMIC_LIB=OFF` as another runtime argument.  I was very puzzled as to why we were pulling in the `libatomic` dependency given that we pass all the CMake tests for atomic support from `compiler-rt`, but it turns out a change was made by https://github.com/llvm/llvm-project/commit/e0184357fc781e939f4e4368fc8aff692ce227ed#diff-7fe4484bb7932f209dd20f48938710edff36401b3c64666325bfee8396de9af0 which forces `libc++` to opportunistically link `libatomic` if it is detected, even if unneeded.

3) Because of the fix in #1, I was able to remove `-static-libgcc` from the linker flags for the static `libc++` tests.  This introduced a new problem where the test binaries were being dynamically linked to `libunwind`, which I was able to fix by adding 
```
-DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON
-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_SHARED_LIBRARY=OFF
-DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_STATIC_LIBRARY=ON
```
so that `libc++abi` is statically linked to `libunwind`.  This allows us to remove `-unwindlib=libunwind` from the linker flags for the static `libc++` test as well.

At this point it's now possible to dynamically link `libc++` with no link time or run time dependency on GCC by using `-stdlib=libc++ -rtlib=compiler-rt`, and to statically link `libc++` with `-stdlib=libc++ -rtlib=compiler-rt -static-libstdc++`, with no link time dependency on GCC, and no runtime dependency on GCC, `libc++` or `libunwind`.  

As you noted in the static linking tests, ideally the Clang driver should know when linking statically to add `-fPIC` and `glibc` libraries like `-lpthread`, `-ldl`, etc. without having to specify those.  However those issues are not related to the C++ runtimes so I could consider that a separate issue.  It might also make sense for `-stdclib=libc++` to set `-rtlib=compiler-rt` by default, but that's also kind of a separate problem.

Let me know what you think about these changes.  I'm really pleased that we've been able to make so many improvements to LLVM on Linux!

**Review by chandlerc — APPROVED** [review]
Very nice. Going to share this with upstream as well to try and get other packages to match this.

**Comment by chandlerc** [comment]
Would it be possible to remove the GCC dependency from this formula? That would be really awesome and would make this much cheaper for folks to install.

**Comment by danielnachun** [comment]
Thanks for looking everything over, and for all your help in making this possible!  From my cursory glance of how other Linux package managers currently ship LLVM, they generally don't seem to build `libc++` so that the end user can build binaries which don't depend on GCC.  Hopefully there can eventually be some simpler build flags for "build static/shared `libc++` so that it doesn't depend on GCC" as it did take a lot of digging to find these flags, some of which are sparsely documented.  

>Would it be possible to remove the GCC dependency from this formula? That would be really awesome and would make this much cheaper for folks to install.

Unfortunately we had to add this as a dependency starting with LLVM 12.  The reason is that the host GCC in our CI is GCC 5, which is too old to build LLVM 12 (we will move to GCC 7 later this year).  For the sake of simplicity, any formula which needs a newer GCC (usually for C++) is built with the latest version of GCC.  

Even if we made an exception for this and used the oldest version of GCC that can build it, we'd still pull that version in as a dependency, to make sure users on systems with an older host GCC can still use the package.  Ideally we will eventually make our GCC dependency checking smarter, and only require users to install a newer GCC if their host one is too old.   

One inconvenience is that GCC 11 currently will try to build from source in non-default prefixes (though this can be circumvented by using `brew install --force-bottle gcc`).  This is not supposed to be this way, but we've had a long standing "bug" where GCC is incorrectly marked as being non-relocatable even though it is.  I want to try to fix that this coming week.  That doesn't help with GCC taking up the extra disk space, but would massively reduce the install time when using a non-default prefix.

**Comment by chandlerc** [comment]
> Thanks for looking everything over, and for all your help in making this possible! From my cursory glance of how other Linux package managers currently ship LLVM, they generally don't seem to build `libc++` so that the end user can build binaries which don't depend on GCC. Hopefully there can eventually be some simpler build flags for "build static/shared `libc++` so that it doesn't depend on GCC" as it did take a lot of digging to find these flags, some of which are sparsely documented.

Yeah, I'm mostly hoping to change this if possible...

> > Would it be possible to remove the GCC dependency from this formula? That would be really awesome and would make this much cheaper for folks to install.
> 
> Unfortunately we had to add this as a dependency starting with LLVM 12. The reason is that the host GCC in our CI is GCC 5, which is too old to build LLVM 12 (we will move to GCC 7 later this year). For the sake of simplicity, any formula which needs a newer GCC (usually for C++) is built with the latest version of GCC.

LLVM still purportedly supports GCC 5.1 as a host toolchain? https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library

I was wondering if the issue with GCC 5 was actually fixed here -- places where the GCC runtimes didn't provide everything needed. Now that things are being built completely w/o the GCC runtimes, I wonder if GCC 5 would work again.

> 
> Even if we made an exception for this and used the oldest version of GCC that can build it, we'd still pull that version in as a dependency, to make sure users on systems with an older host GCC can still use the package. Ideally we will eventually make our GCC dependency checking smarter, and only require users to install a newer GCC if their host one is too old.

Yeah, this doesn't seem worthwhile really.

> 
> One inconvenience is that GCC 11 currently will try to build from source in non-default prefixes (though this can be circumvented by using `brew install --force-bottle gcc`). This is not supposed to be this way, but we've had a long standing "bug" where GCC is incorrectly marked as being non-relocatable even though it is. I want to try to fix that this coming week. That doesn't help with GCC taking up the extra disk space, but would massively reduce the install time when using a non-default prefix.

Ooo, that would definitely help.

**Comment by danielnachun** [comment]
>>Hopefully there can eventually be some simpler build flags for "build static/shared libc++ so that it doesn't depend on GCC" as it did take a lot of digging to find these flags, some of which are sparsely documented.

> Yeah, I'm mostly hoping to change this if possible...

One other thing to note is that I had to slightly patch some of the CMakeLists for LLVM 7 and 8 in order to use `compiler-rt` with `libc++`, `libc++abi`, and `libunwind` (you can see what I did in the PRs for those versions).  I don't know how important those older versions are to upstream or users anymore, but we like to try to make our formula as consistent as possible between versions.

> > Unfortunately we had to add this as a dependency starting with LLVM 12. The reason is that the host GCC in our CI is GCC 5, which is too old to build LLVM 12 (we will move to GCC 7 later this year). For the sake of simplicity, any formula which needs a newer GCC (usually for C++) is built with the latest version of GCC.
> 
> LLVM still purportedly supports GCC 5.1 as a host toolchain? https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library
> 
> I was wondering if the issue with GCC 5 was actually fixed here -- places where the GCC runtimes didn't provide everything needed. Now that things are being built completely w/o the GCC runtimes, I wonder if GCC 5 would work again.

Getting LLVM to build with GCC 5 would be great, as the switch to using GCC 11 created multiple headaches for us.  We have been forced to build everything which links to `libLLVM`, even indirectly, with the newer GCC, which inconveniently includes `mesa`, which we use for OpenGL support.  I don't recall exactly where the failures happened with GCC 5, but unfortunately I don't think these changes will help with that, as `libc++` was disabled at the time we tried to do that (though I suppose it could have been an issue with `libc++abi` or `libunwind`, which were enabled).

Since this PR and all the others are green and you've approved the changes so far, I'm going to get this version merged now, and then open a new PR to try to get LLVM 12 to build with GCC 5.  I'm hoping that we just need some additional flag(s) to get it to work with that version, given that the documentation claims it should.

**Pull request closed without merging**
