### PR TITLE
openjdk@12: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
checking for unzip... no
configure: error: Could not find required tool for UNZIP
configure exiting with result code 1
```

**Comment by iMichka** [comment]
> 2019-11-07T20:01:04.4031057Z checking for zip... no

**Comment by dawidd6** [comment]
I would try to change this `boot_jdk = boot_jdk_dir/"Contents/Home"` to this `boot_jdk = boot_jdk_dir`.

**Comment by iMichka** [comment]
2019-11-07T23:21:24.1343752Z configure: Using default toolchain gcc (GNU Compiler Collection)
2019-11-07T23:21:24.1344499Z configure: Will use user supplied compiler CC=gcc-5
2019-11-07T23:21:24.1344850Z checking for gcc-5... /usr/bin/gcc-5
2019-11-07T23:21:24.1344985Z checking resolved symbolic links for CC... no symlink
2019-11-07T23:21:24.1345355Z configure: Using gcc C compiler version 5.4.0 [gcc-5 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609]
2019-11-07T23:21:24.1345614Z checking whether the C compiler works... no
2019-11-07T23:21:24.1345989Z configure: error: in `/tmp/openjdk@12-20191107-12987-17dlvd0/jdk12u-jdk-12.0.2+10':
2019-11-07T23:21:24.1346129Z configure: error: C compiler cannot create executables
2019-11-07T23:21:24.1346416Z See `config.log' for more details
2019-11-07T23:21:24.1346531Z configure exiting with result code 77

**Comment by iMichka** [comment]
```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
configure:36424: $? = 0
configure:36413: /usr/bin/gcc-5 -V >&5
gcc-5: error: unrecognized command line option '-V'
gcc-5: fatal error: no input files
compilation terminated.
configure:36424: $? = 1
configure:36413: /usr/bin/gcc-5 -qversion >&5
gcc-5: error: unrecognized command line option '-qversion'
gcc-5: fatal error: no input files
compilation terminated.
configure:36424: $? = 1
configure:36444: checking whether the C compiler works
configure:36466: /usr/bin/gcc-5 -m64    -m64  -headerpad_max_install_names conftest.c  >&5
gcc-5: error: unrecognized command line option '-h'
configure:36470: $? = 1
configure:36508: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "openjdk"
| #define PACKAGE_STRING "OpenJDK openjdk"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.java.net"
| #define PACKAGE_URL "http://openjdk.java.net"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:36513: error: in `/tmp/openjdk@12-20191108-65968-3lvyo6/jdk12u-jdk-12.0.2+10':
configure:36515: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by iMichka** [comment]
I made a mistake, I did not want to merge this as this is not done. Follow up PR here: #17223

**Pull request closed without merging**
