### PR TITLE
pypy: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
2019-11-26T12:06:09.4699690Z [34m==>[0m [1mbrew install ./pypy--7.2.0.x86_64_linux.bottle.tar.gz[0m
2019-11-26T12:06:44.8805393Z [34m==>[0m [1mDownloading https://files.pythonhosted.org/packages/11/0a/7f13ef5cd932a107cd4c0f3ebc9d831d9b78e1a0e8c98a098ca17b1d7d97/setuptools-41.6.0.zip[0m
2019-11-26T12:06:45.0679163Z Already downloaded: /home/vsts_azpcontainer/.cache/Homebrew/downloads/8972e259c446d0339621e79cbc2b54d08b6b50db4ab519e3718755188e337894--setuptools-41.6.0.zip
2019-11-26T12:06:45.0704819Z [33mWarning:[0m The post-install step did not complete successfully
2019-11-26T12:06:45.0736194Z You can try again using `brew postinstall pypy`
2019-11-26T12:06:45.0737213Z [34m==>[0m [1mundefined method `shelljoin' for nil:NilClass[0m
2019-11-26T12:06:45.0738394Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:537:in `initialize'
2019-11-26T12:06:45.0739043Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:9:in `new'
2019-11-26T12:06:45.0739732Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:9:in `rewrite_child_error'
2019-11-26T12:06:45.0740381Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
2019-11-26T12:06:45.0741516Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:361:in `ignore_interrupts'
2019-11-26T12:06:45.0742207Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
2019-11-26T12:06:45.0742862Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:31:in `open'
2019-11-26T12:06:45.0744152Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block in safe_fork'
2019-11-26T12:06:45.0744987Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
2019-11-26T12:06:45.0745742Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:30:in `safe_fork'
2019-11-26T12:06:45.0746997Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:921:in `post_install'
2019-11-26T12:06:45.0747802Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:641:in `finish'
2019-11-26T12:06:45.0748529Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:330:in `install_formula'
2019-11-26T12:06:45.0749652Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
2019-11-26T12:06:45.0750276Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
2019-11-26T12:06:45.0751081Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
2019-11-26T12:06:45.0751703Z /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by iMichka** [comment]
I think the error message is a red herring. There is definitively a bug in brew, which has a problem with shelljoin on a nil class somewhere. But I think the real issue is a failing folder creation: `ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'`

**Comment by dawidd6** [comment]
Same, but nicer output:
```
==> brew install ./pypy--7.2.0.x86_64_linux.bottle.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/0a/7f13ef5cd932a107cd4c0f3ebc9d831d9b78e1a0e8c98a098ca17b1d7d97/setuptools-41.6.0.zip
Already downloaded: /home/vsts_azpcontainer/.cache/Homebrew/downloads/8972e259c446d0339621e79cbc2b54d08b6b50db4ab519e3718755188e337894--setuptools-41.6.0.zip
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall pypy`
==> undefined method `shelljoin' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:537:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:9:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:9:in `rewrite_child_error'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:361:in `ignore_interrupts'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:31:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block in safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/fork.rb:30:in `safe_fork'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:925:in `post_install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:645:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:330:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by dawidd6** [comment]
I prepared potential fix here: https://github.com/dawidd6/brew/commit/6558c8e378cbdef176945ae4c5ce2e459dc3ffc5, but dunno really how to test it without burning my CPU for hours during compilation.

**Comment by jonchang** [comment]
For posterity's sake: The original error message was a red herring; `dependency_collector.rb` inspects all `resource` blocks to see what is needed for the fetch and stage steps. But it assumes that all resources are only needed during install phase (i.e., as a `:build` dependency), but this formula uses `unzip` in the postinstall phase to stage the setuptools resource.

It's difficult-to-impossible to fix in `brew`, so the expedient `uses_from_macos "unzip"` is used instead.

**Pull request closed without merging**
