### PR TITLE
shtools: fix test on linux

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by MarkWieczorek** [comment]
Hi @dawidd6 . Thanks for porting shtools to linuxbrew! I was just looking into how to do this, and saw that you beat me to it.

Concerning the failed test, this is because the test programs need to link to a working LAPACK and BLAS library. On macOS, the easiest way to do this is to link to Apple's '-framework accelerate'. An alternative way to do this would be to use something like brew's openBLAS. On macos, you would simply need to replace the line

```
                   "LAPACK=-framework accelerate",
```
with
```
                   LAPACK="-L/usr/local/opt/openblas/lib/ -lopenblas",
```
I don't have a linux setup, so I can't test this, but I suspect that you just need to add `depends_on "openblas"` and then replace the LAPACK reference with ` LAPACK="-lopenblas"`.

I see that the homebrew docs suggest that we use openblas instead of Apple's framework accelerate, so I will probably update the homebrew-core formula to use openBLAS with the next release.

**Comment by MarkWieczorek** [comment]
After searching on how other projects deal with openblas, this is probably what we should do:

```
LAPACK="-L#{Formula["openblas"].opt_lib} -lopenblas",
```
Do you know if this works with linux? (I'm not sure if linux brew has an /opt folder). I'll try to put in a PR later today and see what happens.

**Comment by dawidd6** [comment]
It will work. Just need to add `depends_on "openblas"` for Linux.

**Comment by MarkWieczorek** [comment]
Ok. Just opened a PR at homebrew-core. Let me know if the linux tests fail.

https://github.com/Homebrew/homebrew-core/pull/62119

**Pull request closed without merging**
