### PR TITLE
avahi: remove workaround

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
Weird, you were able to remove this work around before and it worked fine.  I wonder what's going on here?

**Comment by iMichka** [comment]
So this one is a little bit special:
```
2021-04-03T21:34:52.5469015Z Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/opt/xmltoman/bin/xmltoman line 21.
2021-04-03T21:34:52.5471075Z BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/xmltoman/bin/xmltoman line 21.
2021-04-03T21:34:52.5472267Z Makefile:860: recipe for target 'avahi-daemon.8' failed
2021-04-03T21:34:52.5473031Z make[1]: *** [avahi-daemon.8] Error 2
2021-04-03T21:34:52.5473757Z make[1]: *** Waiting for unfinished jobs....
2021-04-03T21:34:52.5476431Z Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/opt/xmltoman/bin/xmltoman line 21.
```

It's related to `xmltoman`.

**Comment by iMichka** [comment]
Weird, I fixed `xmltoman`, rebased this, and it still fails:

```
2021-04-12T20:18:00.6749479Z xmltoman avahi-daemon.8.xml > avahi-daemon.8
2021-04-12T20:18:00.6750468Z xmltoman avahi-dnsconfd.8.xml > avahi-dnsconfd.8
2021-04-12T20:18:00.6754403Z Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/bin/xmltoman line 21.
2021-04-12T20:18:00.6757071Z BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/bin/xmltoman line 21.
2021-04-12T20:18:00.6758284Z Makefile:860: recipe for target 'avahi-daemon.8' failed
```

**Comment by iMichka** [comment]
It's using `/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/bin/xmltoman` instead of `/home/linuxbrew/.linuxbrew/opt/xmltoman/bin/xmltoman`

**Comment by danielnachun** [comment]
Hmm, I wonder how the path is being resolved for this to find `xmltoman`?  This isn't a hard problem to fix if we can just make it use the right file.  Or alternately find a way to get the `PERL5LIB` env into `/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/bin/xmltoman`.

**Comment by iMichka** [comment]
Found it!

I edited `/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/bin/xmltoman` and changed the `PERL5LIB` from `"/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/lib/perl5/"` to `"/home/linuxbrew/.linuxbrew/Cellar/xmltoman/0.4_1/libexec/lib/perl5/x86_64-linux-thread-multi"`

I then rebuilt and got an error about mismatched perl versions ...

I then removed my change and added  `perl` as a dependency to this formula, and it worked.

`xmltoman` uses `#!/usr/bin/env perl`.

The `xmltoman` formula defines `uses_from_macos "perl"`, but that does not seem to be enough to put it first in the path?

**Comment by iMichka** [comment]
Right I know why this happens, `depends_on "xmltoman" => :build` is a build time dependency, so no brew perl was installed. Looks like we have no choice to set brewed perl as a dependency again.

**Pull request closed without merging**
