### PR TITLE
ipmitool: Build a bottle for Linuxbrew

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-09-09T20:48:32.7374685Z ==> Applying ipmitool-getpass-segfault.patch
2019-09-09T20:48:32.7375869Z patch -g 0 -f -p1 -i /tmp/ipmitool--patch-20190909-5210-1pten84/ipmitool-getpass-segfault.patch
2019-09-09T20:48:32.7402945Z patching file lib/ipmi_main.c
2019-09-09T20:48:32.7459466Z patching file src/plugins/lanplus/lanplus_crypt_impl.c
2019-09-09T20:48:32.7459832Z Hunk #1 FAILED at 164.
2019-09-09T20:48:32.7477231Z 1 out of 7 hunks FAILED -- saving rejects to file src/plugins/lanplus/lanplus_crypt_impl.c.rej
2019-09-09T20:48:32.7674609Z Error: Failure while executing; `patch -g 0 -f -p0` exited with 1. Here's the output:
2019-09-09T20:48:32.7675113Z 3792
2019-09-09T20:48:32.7787611Z ==> FAILED
```

**Comment by dawidd6** [comment]
I think we can drop this patch as it seems to be macos specific.

**Comment by dawidd6** [comment]
Maybe this patch would be better: https://git.archlinux.org/svntogit/community.git/plain/trunk/ipmitool-openssl-1.1.patch?h=packages/ipmitool

**Comment by iMichka** [comment]
Thanks. Ideally the patches should be hosted on https://github.com/Homebrew/formula-patches, and split with `if OS.mac? / else`, but as upstream (homebrew-core) did not do so, we can keep this as-is. This will be ok.

P.S. I also hate patches/code with mixed tabs and spaces, my text editor always tries to clean that up :(

**Pull request closed without merging**
