### PR TITLE
Merge 2020-10-20 ffec6456d2

### PR DESCRIPTION
**Pull request by iMichka**
Merge Homebrew/homebrew-core into Homebrew/linuxbrew-core

+ [ ] bitcoin
+ [ ] boost-mpi
+ [ ] boost-python3
+ [ ] boost
+ [ ] cucumber-cpp
+ [ ] freetype
+ [ ] gitlab-runner
+ [ ] glib
+ [ ] nushell
+ [ ] source-highlight
+ [ ] widelands

### CODE REVIEW

**Comment by develop7** [comment]
hey @iMichka do you look into bottle build errors?

**Comment by iMichka** [comment]
Sometimes. It depends. These 2 are on my todo, will have a look later today when I am back from work.

Sometimes I can’t fix everything, it’s way too much work for me alone. So I prioritise depending on what I think is most important.

If there is a specific package that is broken for you just let me known I’ll try to prioritise it. Rebuilding both bottles should be easy, the error above are false-positives.

**Comment by iMichka** [comment]
I rebuilt both bottles.

**Comment by develop7** [comment]
Thank you!

**Pull request merged**
