### PR TITLE
php: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by iMichka**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
configure:19196: gcc-5 -o conftest -g -O2 -fvisibility=hidden   -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.10/lib -L/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.10/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib conftest.c -lsqlite3  -lrt -lm -ldl  -lxml2 -lkrb5 -lssl -lcrypto >&5
/usr/bin/ld: cannot find -lkrb5
collect2: error: ld returned 1 exit status
configure:19196: $? = 1
configure: failed program was:
```

**Comment by black-snow** [comment]
```
Last 15 lines from /home/xxx/.cache/Homebrew/Logs/php/02.configure:
checking for atoll... yes
checking whether to build with LIBXML support... yes
checking for libxml-2.0 >= 2.7.6... yes
checking for OpenSSL support... yes
checking for Kerberos support... yes
checking whether to use system default cipher list instead of hardcoded value... no
checking for krb5-gssapi krb5... yes
checking for RAND_egd... no
checking for openssl >= 1.0.1... yes
checking for PCRE library to use... bundled
checking whether to enable PCRE JIT functionality... yes
checking whether to enable the SQLite3 extension... yes
checking for sqlite3 > 3.7.4... yes
checking for sqlite3_stmt_readonly in -lsqlite3... no
configure: error: Please install SQLite 3.7.4 first or check libsqlite3 is present
```

Missing dependency? :)

**Comment by dawidd6** [comment]
`sqlite` is already declared as dependency. Must be something else.

**Comment by iMichka** [comment]
Yes, it is a red herring. There are other hidden errors in the config.log file. I am working on this, and was able to build it locally. I hope I can provide a fix in the next days. But the php setup system is a real pain ...

**Pull request closed without merging**
