### PR TITLE
azure-pipelines: setup bottle upload

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
@ladislas @sjackman I am trying to get the bottle uploading going.
From within the docker container, I can call the upload script.

Right now I get:
```
git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git origin/master:master :refs/tags/pr-13287
Host key verification failed.
fatal: Could not read from remote repository.
```

Of course, this means that I need to get the ssh keys (and some bintray keys) into the env.
I was reading on how to pass secret variables when on a pull request, and found this:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks

@ladislas did you enable the `Make secrets available to builds of forks` checkbox for your project?
I am worried that once this is enabled, anybody could open a pull request, modify the CI code and access the secret variables.

**Comment by ladislas** [comment]
@iMichka regarding the ssh key, you don't need to manually get it into the env. Azure Pipelines has dedicated task for that:

- https://github.com/ladislas/homebrew-hello-world/blob/b955d15417822926223598431fbaab0ef869e961/.azure-ci/brew_test_bot_ci_upload.yml#L16-L21
- the variable that you see (`ssh_hostname`, etc.) are env variables coming from secret variables that are stored in the variable library in azure
- the ssh key is also stored as a private secured file

> did you enable the Make secrets available to builds of forks checkbox for your project?

No I haven't as I'm usually working in my own project.

best way would be to test it with a fake repo with Azure and a secret key that I would fork and make a PR to to see if I can see the secrets.

**Comment by iMichka** [comment]
Regarding the `InstallSSHKey@0`, I can not execute it inside the container. So looks like I need to have a shared folder between the host and the container, to be able to move the bottles out of the container. Don't know if that is allowed.

**Comment by ladislas** [comment]
Regarding this error:

> The pipeline is not valid. Job UploadLinuxbrewCoreBottles: Step InstallSSHKey input sshKeySecureFile references secure file $(ssh_secure_file) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.

You need to force build the master branch so that they become available. Also turn on the "allow for all pipelines"

**Comment by iMichka** [comment]
Ok thanks for all the details. I think I got the main idea. I think I am almost there, I adapted your code. Right now it is a single big .yml file, we can split in sub-steps like you did later on.

```
The pipeline is not valid. Job UploadLinuxbrewCoreBottles: Step InstallSSHKey input sshKeySecureFile references secure file $(ssh_secure_file) which could not be found. The secure file does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

We need to upload the ssh credential file too I guess? Are these the ssh keys of the Linuxbrewtestbot user. @sjackman, can we extract these from somewhere? Are these maybe stored on our AWS lambda console?

From the documentation:
```
How do I authorize a secure file for use in all pipelines?

Navigate to the Library tab in Azure Pipelines.
Select the Secure files tab at the top.
Select the secure file you want to authorize.
In the details view, below the "Properties" section, select Authorize for use in all pipelines, and then select Save.
```

**Comment by ladislas** [comment]
@iMichka regarding ssh, here is my first take at documentation https://github.com/ladislas/homebrew-greetings#create-variable-groups--upload-secure-file-on-azure-pipelines

**Comment by sjackman** [comment]
> By default with GitHub pipelines, secrets associated with your build pipeline are not made available to pull request builds of forks.

> To bypass this precaution on GitHub pipelines, enable the Make secrets available to builds of forks check box. Be aware of this setting's effect on security.

Does Azure have a mechanism to ensure these secrets aren't leaked to the user who owns the fork? We're dead in the water unless it does.

**Comment by iMichka** [comment]
I think I found the solution: build the bottles and publish them to Build.ArtifactStagingDirectory. This is working correctly right now.

Then use a release pipeline: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops

I am clicking through the GUI right now, you can run some bash script with secret credentials. This is separated from the rest of the fork/build process. We just need to curl the bottle into bintray.

**Comment by ladislas** [comment]
If you go through the release pipeline thing, you could even just drop out Bintray as you could replace it with Artifacts. 

> I am clicking through the GUI right now, you can run some bash script with secret credentials. This is separated from the rest of the fork/build process. We just need to curl the bottle into bintray.

but how will you run `brew pull --bottle` if you don't run `brew test-bot --ci-upload`? Can you actually do that?

**Comment by iMichka** [comment]
As we use bintray right now everywhere, I would like to stick to that solution.

Regarding the upload, the ci-upload command basically just runs one or two curl commands to upload the files to bintray. I already did that manually a long time ago. I need to extract that curl command line with the right parameters and it should be ok.

**Comment by ladislas** [comment]
> As we use bintray right now everywhere, I would like to stick to that solution.

yes of course, just a suggestion.

> the ci-upload command basically just runs one or two curl commands to upload the files to bintray

I'm not afraid about the `curl`, but more about the `brew bottle --merge --write` and `git push --force #{remote} origin/master:master :refs/tags/#{git_tag}` but nothing that can't be done eventually.

**Comment by iMichka** [comment]
I will have a look if I can install brew. It should work, because the release steps are just running in a VM and you can execute whatever code you want. If not, we may need to find a different solution. The most important part is to upload the bottles.

It is weird that we need this tag and commit on the repo to be able to pull the bottle. I mean, you just need the bottle on bintray, and your initial pull request. Brew pull should be able to work with only that information.

**Comment by sjackman** [comment]
> I will have a look if I can install brew. It should work, because the release steps are just running in a VM and you can execute whatever code you want. If not, we may need to find a different solution. The most important part is to upload the bottles.

👍 Can you specify a Docker image to use?

> It is weird that we need this tag and commit on the repo to be able to pull the bottle. I mean, you just need the bottle on bintray, and your initial pull request. Brew pull should be able to work with only that information.

Yep, that should be possible if you wanted to go that route, so that you don't need GitHub credentials. It would also eliminated the need for LinuxbrewTestBot, which would be nice.

**Comment by iMichka** [comment]
It is the Ubuntu 16.04 vm from azure. It has git and all the things preinstalled. I just need to git clone the repos, fiddle a little bit with the paths and variables, and it should be ok. I already could run brew config which installed portably ruby. I am almost there, I think I will need a few more hours and it will be ok.

I will just need help to generate a ssh key for git that I can add as a secret to the build. I’ll ping you on slack for this soon.

**Comment by iMichka** [comment]
Ok I am almost there, but I am facing two issues:

I did the ssh setup, following these instructions:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops

Here is what I get:
```
2019-05-26T16:31:12.5243992Z git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git origin/master:master :refs/tags/pr-13287
2019-05-26T16:31:12.6871473Z Host key verification failed.
2019-05-26T16:31:12.6875937Z fatal: Could not read from remote repository.
2019-05-26T16:31:12.6879116Z 
2019-05-26T16:31:12.6879648Z Please make sure you have the correct access rights
2019-05-26T16:31:12.6879726Z and the repository exists.
2019-05-26T16:31:12.6882670Z Error: Failure while executing; `git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git origin/master:master :refs/tags/pr-13287` exited with 128.
```

Right now I do not know how to debug this ... I already tried a lot of things.

I have a second issue: I can not add a PR trigger for the release pipeline, due to this bug:
https://developercommunity.visualstudio.com/content/problem/337049/unable-to-create-pull-request-release-trigger.html

There was an answer from Microsoft 6 days ago that they were working on it.

**Comment by sjackman** [comment]
> Host key verification failed.

When you ssh to a machine for the first time `ssh` asks interactively whether you wish to add the remote machine's key to your `~/.ssh/known_hosts`. My best guess would be that since the session is non-interactive, that step is falling back do denying the connection. Just my best guess.

**Comment by sjackman** [comment]
cc @issyl0

**Comment by ladislas** [comment]
> My best guess would be that since the session is non-interactive, that step is falling back do denying the connection. Just my best guess.

@sjackman the ssh key installation task takes care of that. I had the same issue and it was a problem with the key used. I was not adding my private ssh key to Azure Secure File.

In the end I generated a dedicated ssh key to add to github and to Azure secure file just for this purpose.

I also created an `azure-playground` repo to test all of this before reaching a working solution... the docs from MS are not bad but they lack good examples, a lot of trial and error was needed. :(

**Comment by ladislas** [comment]
@iMichka your host key should start with something like:

```
hostName: github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2[...]
```

**Comment by iMichka** [comment]
Ok got it to work.

I created the ssh keys in a new, clean docker container, to be sure I was not doing anything wrong. It is funny to see that the know host file has two entries, looking like:
```
|1|u4cBTIzMq25wapRnOh7MHGL32+Y=|8LLoWa1Y31qkqDH3nt2XatX8Ioo= ssh-rsa ....
```

No clue why that is, and why there is no IP address in there anymore, but this works.

Here are some screenshots from the release pipeline, the setup is pretty straightforward:

Screen Shot 2019-05-27 at 18 53 34

Screen Shot 2019-05-27 at 18 54 51

The bash script is the following:

```
git clone --depth=1 https://github.com/Homebrew/brew
git clone --depth=1 https://github.com/Homebrew/homebrew-test-bot brew/Library/Taps/homebrew/homebrew-test-bot
git clone --depth=1 https://github.com/Linuxbrew/homebrew-developer brew/Library/Taps/linuxbrew/homebrew-developer
git clone --depth=50 https://github.com/Homebrew/linuxbrew-core brew/Library/Taps/homebrew/homebrew-core

export HOMEBREW_DEVELOPER=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_FILTERING=1
export HOMEBREW_VERBOSE=1
export HOMEBREW_BINTRAY_USER=$HOMEBREW_BINTRAY_USER
export HOMEBREW_BINTRAY_KEY=$HOMEBREW_BINTRAY_KEY
export UPSTREAM_GIT_URL=https://github.com/$BUILD_REPOSITORY_ID
export UPSTREAM_PULL_REQUEST=${BUILD_SOURCEBRANCH:10:5}

echo "############ Brew config"
brew/bin/brew config

echo "############ List bottles"
cd _Homebrew.linuxbrew-core/bottle-linux
ls

echo "############ Upload bottles"
$SYSTEM_DEFAULTWORKINGDIRECTORY/brew/bin/brew test-bot --ci-upload --keep-old --bintray-org=linuxbrew --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
```

This code is stored inside the release pipeline, and can not be modified. The ssh keys are stored as secrets, as the bintray keys. So we are on the safe side here.

With this setup, the release tag was created on https://github.com/LinuxbrewTestBot/homebrew-core/releases, and the bottle was uploaded.

This works only if I manually trigger the release. If I want to enable the release for each PR, I hit the following bug:
https://developercommunity.visualstudio.com/content/problem/337049/unable-to-create-pull-request-release-trigger.html

See also the screenshot below:
Screen Shot 2019-05-27 at 19 01 37

**Comment by sjackman** [comment]
🎉 Woohoo! Nice work, Michka!

They seem to think that issue was resolved.
@imichka Want to post on that ticket that you're also experiencing that issue?

**Comment by ladislas** [comment]
That's some incredible job!

Working on the same topic for my personal taps, I found myself wondering if I should add a release pipeline like you, but it's a lot of work just for a tap.

I understand the security concerns of leaking some confidential keys and such, but I'm wondering if building + publishing a fork PR is always a good thing. The secrets won't be leaked but it doesn't mean the software provided is good.

Of course you'll always need the manual `brew pull --bottle`.

In the end you'll also always review the PR if it's from someone that's not from the core team and/or from a fork. Building/publishing before reviewing seems a bit dangerous if one day you're feeling lazy and just `brew pull --bottle` the PR without looking twice.

What's your take on that?

For personal taps, unless it becomes used by thousands of people, the risk of someone trying to slip in malicious software is lower.

The PR burden is also much lower.

So I decided to:

- not allow secret variables for forks --> it will test the PR but not publish the bottles
- I'll review the PR. If files related to Azure Pipelines were modified I'll ask the contributor to revert them (unless it's safe)
- When I'm sure everything is good, I'll make a new PR from the contributor's PR, let it build and publish
- and then I'll run `brew pull --bottle` to merge the changes

**Comment by iMichka** [comment]
> What's your take on that?

If the bintray key is leaked, anybody can alter bottles on bintray, so we want to avoid that.
I agree that setting up a release pipeline for a tap is a lot of work.

> If files related to Azure Pipelines were modified I'll ask the contributor to revert them (unless it's safe)

They may pipe the content of the keys to stdout, or send it by email, or whatever. But I am not a security specialist.

Please also not that the publishing step on bintray is only done when `brew pull --bottle` is called. So in our case, anybody can open a PR, the bottle will be built and uploaded, but not published. This is done by one of the maintainers. This is exactly the same workflow as now with circle.ci.

**Comment by iMichka** [comment]
The final issue we have is that I can not enable release pipelines for pull requests:
Screen Shot 2019-05-27 at 19 01 37

This has been reported here:
https://developercommunity.visualstudio.com/content/problem/337049/unable-to-create-pull-request-release-trigger.html

Maybe @davidstaheli or @chrispat could help? (Asking you because you commented on our issue tracker before). Our CI integration with azure is ready, and works for manual builds. This is the last issue which prevents us to switch to azure pipelines.

**Comment by davidstaheli** [comment]
@iMichka I've contacted the team who owns this and will get back to you ASAP.

**Comment by sjackman** [comment]
@ladislas If you're expecting that most of the PRs will come from maintainers of the tap, then instead of fork PRs you can use PRs from the same repo, and a lot of these credential issues go away.

**Comment by ladislas** [comment]
> They may pipe the content of the keys to stdout, or send it by email, or whatever. But I am not a security specialist.

@iMichka I've done the test with different repos, trying to echo the secret variables/files to stdout (haven't tried emails, etc.), but as long as you don't allow secrets to be used for external PR, it won't work. 

But I guess you'll never know :)

> Please also not that the publishing step on bintray is only done when brew pull --bottle is called. So in our case, anybody can open a PR, the bottle will be built and uploaded, but not published. This is done by one of the maintainers. This is exactly the same workflow as now with circle.ci.

Yes of course, and it's the exact same workflow I'm reproducing for my own taps.

I'm actually super close to providing a complete and documented solutions for that, I'll post it soon on discourse to gather feedback.

>  If you're expecting that most of the PRs will come from maintainers of the tap, then instead of fork PRs you can use PRs from the same repo, and a lot of these credential issues go away.

@sjackman yes, that's what I do :)

**Comment by iMichka** [comment]
The ETA is another 4 to 5 weeks for the fix. We will have to wait.

I am closing this issue, as I already merged this code with another PR.

**Pull request closed without merging**
