### PR TITLE
git-annex: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Database/Keys/SQL.hs:31:1: error:
    Generating Persistent entities now requires the following language extensions:

DerivingStrategies
StandaloneDeriving

Please enable the extensions by copy/pasting these lines into the top of your file:

{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE StandaloneDeriving #-}
   |
31 | share [mkPersist sqlSettings, mkMigrate "migrateKeysDb"] [persistLowerCase|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
git-annex-7.20191230-JGm7b2Gk5I8w0hi2BDCiw failed during the building phase.
The exception was:
ExitFailure 1
```

**Comment by dankessler** [comment]
Can we try bottling this again, @dawidd6?

The same build failure was encountered in a PR on `homebrew-core` https://github.com/Homebrew/homebrew-core/pull/49731 and subsequently [reported upstream](https://github.com/Homebrew/homebrew-core/pull/49731#issuecomment-582066241) where sounds like it has now [been fixed](https://git-annex.branchable.com/bugs/brew_install_git-annex_failed/). Moreover, this fix is incorporated into version 7.20200204, which is the [version specified by the formula in master](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-annex.rb#L8) now that it's been ported over from [core's master](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/git-annex.rb#L8). 

I am now able to install with `brew install git-annex` in Ubuntu 18.04, but building takes a loooooong time and a bottle would be very welcome.

**Comment by dawidd6** [comment]
@dankessler https://github.com/Homebrew/linuxbrew-core/actions/runs/35590766

**Comment by dankessler** [comment]
For future reference, is this something I could've triggered myself? I've found some documentation of how bottling works for `homebrew-core`, but I have an even fuzzier understanding of the workflow for `linuxbrew-core` bottles. I really appreciate your help with this and want to avoid annoying maintainers by asking them to do things I could've done myself.

**Comment by dawidd6** [comment]
No, you would need to have push access to this repo.

If you want to request a bottle, submit an issue, there is a template specially for this.

**Comment by dankessler** [comment]
Very slick! Thanks for all your help with this; as a user I've been really impressed with `homebrew`, and now that I've gotten a tiny bit involved (I contributed my first formula last week) I'm *super* impressed with the maintainers and organization of the project. Thanks for the work that you do!

**Comment by dankessler** [comment]
@dawidd6  It looks like bottling succeeded but there are some error messages with authentication when it tried to push the updated formula. I assume that I don't need to open an issue to get the formula with the bottle's SHA added since you triggered this manually, but let me know if I need to do so.

**Comment by dawidd6** [comment]
There seems to be some issue with the workflow. Need to investigate.

**Comment by issyl0** [comment]
> Very slick! Thanks for all your help with this; as a user I've been really impressed with `homebrew`, and now that I've gotten a tiny bit involved (I contributed my first formula last week) I'm _super_ impressed with the maintainers and organization of the project. Thanks for the work that you do!

Thanks for the kind words! :heart:

**Comment by dawidd6** [comment]
Here we go again: https://github.com/Homebrew/linuxbrew-core/actions/runs/35654278

**Comment by dawidd6** [comment]
@dankessler uploaded finally: https://github.com/Homebrew/linuxbrew-core/commit/1654c83b4db2a3135c84c3aaa70c3722ccc058e4

**Comment by dankessler** [comment]
@dawidd6 the version of `git-annex` [was bumped in `homebrew/homebrew-core`](https://github.com/Homebrew/homebrew-core/pull/50445)  (and it looks like there's a bot that ported that into linuxbrew). It looks like that automatically triggered construction of a new OS X bottle, but seems like it does not auto-trigger the creation of a new linux bottle, right? I'm currently building it on my Debian system and will open an issue to update the bottle if it succeeds, but wanted to make sure this was the appropriate procedure.

**Comment by jonchang** [comment]
@dankessler i've kicked off a bottle request job here: https://github.com/Homebrew/linuxbrew-core/runs/459438943

We are still working on our infrastructure to catch these things as they come up. If you see this again in the future please file a new issue and ideally link to the failed bottle build workflow.

**Comment by dankessler** [comment]
Thanks for the very fast response, @jonchang (on a fanboy note, I've really been enjoying your blog posts on homebrew!) 

*Should* the version bump in homebrew-core have kicked off a new bottle build here for linuxbrew? I don't think the build ever even started, so there's no failed bottle build to link to, although it seems like a lot of actions were kicked off in the past 8 hours since the merge, so perhaps it's in there somewhere. 

It looks like when `homebrew-core/master` was merged into `linuxbrew-core/master`, the [linux bottle line](https://github.com/Homebrew/linuxbrew-core/commit/0c154b897de5d7b09e970fc66fc0a155fe438615#diff-9154e865029b4d76941a498353329fcdL12) was lost (seems like it was maybe a `theirs` merge?).

For tools that I care about, I'll definitely be happy to manually request new bottles via issues here when the version bumps (especially for tools that take a while to compile), but should I consider these edge cases that fall through the cracks, or is this the expected behavior?

Are there documents for the `linuxbrew` infrastructure, especially with respect to how things migrate from `homebrew-core` into `linuxbrew-core`? I'm not quite clear on how (semi-)automatic it all is, and as I increasingly rely on `homebrew` on both my Mac and linux machines, would be happy to lend a hand if there's a place where it would be useful :)

PS: My build in Debian (with `brew update && brew upgrade git-annex`) just succeeded, so hopefully that's a good portend for the bottler :)

**Comment by jonchang** [comment]
> Thanks for the very fast response, @jonchang (on a fanboy note, I've really been enjoying your blog posts on homebrew!)

Thanks for your kind words! (Go Blue!)

> _Should_ the version bump in homebrew-core have kicked off a new bottle build here for linuxbrew? I don't think the build ever even started, so there's no failed bottle build to link to, although it seems like a lot of actions were kicked off in the past 8 hours since the merge, so perhaps it's in there somewhere.

Yes, I think it should have. I've opened https://github.com/Homebrew/linuxbrew-core/pull/19675 to hopefully provide more information about what bottles are being requested after a merge from Homebrew/core.

> It looks like when `homebrew-core/master` was merged into `linuxbrew-core/master`, the [linux bottle line](https://github.com/Homebrew/linuxbrew-core/commit/0c154b897de5d7b09e970fc66fc0a155fe438615#diff-9154e865029b4d76941a498353329fcdL12) was lost (seems like it was maybe a `theirs` merge?).

> For tools that I care about, I'll definitely be happy to manually request new bottles via issues here when the version bumps (especially for tools that take a while to compile), but should I consider these edge cases that fall through the cracks, or is this the expected behavior?

Yes, this is the expected workflow. A Github actions job will build the bottle and add the linux bottle line in a separate commit, but it seems to not have happened in this case.

> Are there documents for the `linuxbrew` infrastructure, especially with respect to how things migrate from `homebrew-core` into `linuxbrew-core`? I'm not quite clear on how (semi-)automatic it all is, and as I increasingly rely on `homebrew` on both my Mac and linux machines, would be happy to lend a hand if there's a place where it would be useful :)

https://docs.brew.sh/Homebrew-linuxbrew-core-Maintainer-Guide

A few ways to help:

Watch this workflow for failed bottle request jobs and try to fix them by opening a pull request against this repository -- https://github.com/Homebrew/linuxbrew-core/actions?query=workflow%3A%22Build+bottles+from+%27brew+request-bottle%27+trigger.%22

Sync with the Homebrew/core upstream dependencies that we need in Linux that come with macOS with the line `uses_from_macos "zlib"`

e.g., the change from https://github.com/Homebrew/linuxbrew-core/pull/19673 could be submitted as a pull request to Homebrew/homebrew-core

> PS: My build in Debian (with `brew update && brew upgrade git-annex`) just succeeded, so hopefully that's a good portend for the bottler :)

**Comment by jonchang** [comment]
@dankessler git-annex is super slow to build because it brings in all of x.org via gtk+3 and xdot. I don't think this formula should take over an hour to build.

From what I can tell from https://git-annex.branchable.com/git-annex-map/ xdot is only needed at runtime. Can you please test this (e.g., `brew rm --ignore-dependencies xdot`) and confirm that git-annex still works (and that `git annex map` does something reasonable and doesn't :boom:), and if that's the case please submit a pull request to homebrew/homebrew-core removing that dependency? Thanks :heart:

**Comment by dankessler** [comment]
Can confirm that removing `xdot` doesn't make things blow up (and I confirmed that `xdot` is not otherwise available on my system after `brew rm`-ing it). `git annex map` still runs and creates the `map.dot` file, it just doesn't pop up an `xdot` window displaying it. 

I ran a few other `git annex` commands without `xdot` and didn't encounter any big problems. I also ran `git annex`'s test suite, which didn't seem to turn up anything especially problematic.

Also suggestive is that the debian package for `git-annex` *suggests* `xdot` but does not require it, so maybe `xdot` can be dropped as a requirement.
<details>
<summary> apt show git-annex </summary>
<pre>
$ apt show git-annex
Package: git-annex
Version: 6.20170101-1+deb9u2
Priority: optional
Section: utils
Maintainer: Richard Hartmann <richih@debian.org>
Installed-Size: 66.9 MB
Depends: libc6 (>= 2.14), libffi6 (>= 3.0.4), libgmp10, libmagic1 (>= 5.12), libsqlite3-0 (>= 3.6.0), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4), git (>= 1:1.8.1), rsync, wget, curl, openssh-client (>= 1:5.6p1)
Recommends: lsof, gnupg, bind9-host, quvi, git-remote-gcrypt (>= 0.20130908-6), nocache, aria2
Suggests: xdot, bup, tor, magic-wormhole, tahoe-lafs, libnss-mdns
Homepage: http://git-annex.branchable.com/
Tag: devel::rcs, implemented-in::haskell, role::program, works-with::file
Download-Size: 10.9 MB
APT-Sources: http://ftp.us.debian.org/debian stretch/main amd64 Packages
Description: manage files with git, without checking their contents into git
 git-annex allows managing files with git, without checking the file
 contents into git. While that may seem paradoxical, it is useful when
 dealing with files larger than git can currently easily handle, whether due
 to limitations in memory, time, or disk space.
 .
 It can store large files in many places, from local hard drives, to a
 large number of cloud storage services, including S3, WebDAV,
 and rsync, with a dozen cloud storage providers usable via plugins.
 Files can be stored encrypted with gpg, so that the cloud storage
 provider cannot see your data. git-annex keeps track of where each file
 is stored, so it knows how many copies are available, and has many
 facilities to ensure your data is preserved.
 .
 git-annex can also be used to keep a folder in sync between computers,
 noticing when files are changed, and automatically committing them
 to git and transferring them to other computers. The git-annex webapp
 makes it easy to set up and use git-annex this way.

N: There are 2 additional records. Please use the '-a' switch to see them.
</pre>
</details>

The PR should presumably go to `homebrew-core` (and get pulled into `linuxbrew-core` later), right?

PS: Go Blue!

**Comment by dankessler** [comment]
Also, looks like the build process you kicked off failed because the bottle was...[*already built*](https://github.com/Homebrew/linuxbrew-core/runs/459438943#step:5:35)? Digging around it looks like [the commit](https://github.com/Homebrew/linuxbrew-core/commit/fba962ceda81ae34bef3a6dd4509ec8460d5f6ed) that added it was authored by you. So maybe the bottling process did kick off automatically (but under your aegis?), but it was slow enough that it was still in the process of building when I made my initial comment and then you kicked it off?

**Comment by jonchang** [comment]
> The PR should presumably go to homebrew-core (and get pulled into linuxbrew-core later), right?

Yes please.

> Also, looks like the build process you kicked off failed because the bottle was...[_already built_](https://github.com/Homebrew/linuxbrew-core/runs/459438943#step:5:35)? Digging around it looks like [the commit](https://github.com/Homebrew/linuxbrew-core/commit/fba962ceda81ae34bef3a6dd4509ec8460d5f6ed) that added it was authored by @jonchang . So maybe the bottling process did kick off automatically (but under your aegis?), but it was slow enough that it was still in the process of building when I made my initial comment and then you kicked it off?

It had been built but was a falsely passing build. See https://github.com/Homebrew/linuxbrew-core/pull/19676 for the fix

**Pull request closed without merging**
