### PR TITLE
jasper: use freeglut on Linux

### PR DESCRIPTION
**Pull request by mikesep**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
  *Sorry, wasn't able to confirm this locally.*
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.
  *Here's the relevant part of the error log from running `brew install jasper`:*
  ```
  cmake
  ..
  -DJAS_ENABLE_AUTOMATIC_DEPENDENCIES=false
  -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
  -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
  -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/jasper/2.0.22
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_FIND_FRAMEWORK=LAST
  -DCMAKE_VERBOSE_MAKEFILE=ON
  -Wno-dev

  -- The C compiler identification is GNU 5.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-5 - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  Software version: 2.0.22
  Shared library ABI version: 4
  Shared library build version: 4.0.0
  JAS_MULTICONFIGURATION_GENERATOR 0
  CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
    OPENGL_INCLUDE_DIR)
  Call Stack (most recent call first):
    /home/linuxbrew/.linuxbrew/Cellar/cmake/3.18.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    /home/linuxbrew/.linuxbrew/Cellar/cmake/3.18.4/share/cmake/Modules/FindOpenGL.cmake:433 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    build/cmake/modules/JasOpenGL.cmake:7 (find_package)
    CMakeLists.txt:206 (include)
  ```

-----

https://github.com/jasper-software/jasper/pull/248 fixed a GLUT-related build issue, which seems to have exposed an issue with the Linux build of JasPer.

Since there doesn't appear to be an existing build dependency on a GLUT library on Linux, I simply disabled the OpenGL build flag.

Definitely feel free to make or suggest style tweaks -- not sure what's preferred by Linuxbrew maintainers.

### CODE REVIEW

**Comment by iMichka** [comment]
Could we depend on freeglut on linux instead?

**Comment by iMichka** [comment]
Yes, I would prefer freeglut then. As the Mac version is built with glut we want to provide the same functionality to our linux users. I guess that freeglut will be needed at runtime. If jasper links against that library, CI will tell us.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @mikesep !

**Comment by mikesep** [comment]
Thanks @iMichka for your guidance and quick responses. 😄

**Pull request merged**
