### PR TITLE
Merge 2019-10-27 f9aca0a6a1

### PR DESCRIPTION
**Pull request by dawidd6**
Merge Homebrew/homebrew-core into Homebrew/linuxbrew-core

+ [ ] cfn-lint
+ [ ] erlang@20

### CODE REVIEW

**Comment by issyl0** [comment]
@dawidd6 Hmmm, can we fix build failures in merge PRs now? I think I’d prefer to merge them quickly and fix the obvious things later? This has been sat around for an hour and is potentially blocking other things going in.

**Comment by dawidd6** [comment]
Yea, we are trying to make it work with @iMichka and possibly it would be doable, since https://github.com/Homebrew/linuxbrew-core/commit/3c1751e7a59d2fb9c377c9b776302e8f5daa84cf is pushed.

**Comment by dawidd6** [comment]
Bottles built fine but there is an upload error:
```
2019-10-27T09:43:43.6595348Z ==> Applying patch
2019-10-27T09:43:43.6597545Z git am --whitespace=nowarn -3 /home/vsts/.cache/Homebrew/16723.patch
2019-10-27T09:43:43.7132951Z Applying: erlang@20 20.3.8.23
2019-10-27T09:43:43.7133961Z Applying: erlang@20: update 20.3.8.23 bottle.
2019-10-27T09:43:43.7398051Z Using index info to reconstruct a base tree...
2019-10-27T09:43:43.7398350Z M	Formula/erlang@20.rb
2019-10-27T09:43:43.7399240Z Falling back to patching base and 3-way merge...
2019-10-27T09:43:43.7399763Z Auto-merging Formula/erlang@20.rb
2019-10-27T09:43:43.7399852Z CONFLICT (content): Merge conflict in Formula/erlang@20.rb
2019-10-27T09:43:43.7426873Z error: Failed to merge in the changes.
2019-10-27T09:43:43.7427933Z hint: Use 'git am --show-current-patch' to see the failed patch
2019-10-27T09:43:43.7428385Z Patch failed at 0002 erlang@20: update 20.3.8.23 bottle.
2019-10-27T09:43:43.7429879Z When you have resolved this problem, run "git am --continue".
2019-10-27T09:43:43.7430745Z If you prefer to skip this patch, run "git am --skip" instead.
2019-10-27T09:43:43.7431279Z To restore the original branch and stop patching, run "git am --abort".
2019-10-27T09:43:43.8065448Z Error: Patch failed to apply: aborted.
2019-10-27T09:43:43.8116164Z Error: Failure while executing; `brew pull --clean https://github.com/Homebrew/linuxbrew-core/pull/16723` exited with 1.
```

**Comment by dawidd6** [comment]
Last try.

**Pull request closed without merging**
