### PR TITLE
formulae: switch to on_linux block

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I would prefer that we do this in Homebrew-core.

**Comment by iMichka** [comment]
It’s easier to grep for OS.mac instead of making a diff between both repos.

**Comment by iMichka** [comment]
Another strategy is to merge it, and then promise me that you'll backport it :)

**Comment by dawidd6** [comment]
Haha, no can do. Imma try to make those changes upstream.

**Comment by iMichka** [comment]
You'll have to migrate a bunch of linux-only formulae first :D

**Pull request closed without merging**
