### PR TITLE
systemd 247

### PR DESCRIPTION
**Pull request by lexicol**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
I believe @iMichka wanted to get `systemd` added to homebrew/core as a Linux-only formula.  I'm not sure if we had any blockers to adding it. Though before doing so, we may want to figure out why we're getting those linkage errors.

**Comment by iMichka** [comment]
Yes. And I think we want to pin this version to 246 as this is the version of the oldest linux we support. CC @sjackman

**Comment by sjackman** [comment]
> Yes. And I think we want to pin this version to 246 as this is the version of the oldest linux we support. 

I do not recall if/how the version of `systemd` is tied to the version of `linux-headers`, `glibc`, and `gcc`. FWIW Ubuntu 16.04 (Xenial Xerus) has `systemd` version 229 (https://packages.ubuntu.com/xenial/systemd), so updating the brewed version to 229 seems reasonable, if not the latest version. We could potentially have both `systemd@229` and the most recent version if needed.

**Comment by sjackman** [comment]
https://github.com/systemd/systemd/blob/b63dae3168209a06cefe2b9916667b7754b7de34/NEWS#L476

`systemd 247` mentions a `KERNEL API INCOMPATIBILITY` with Linux 4.14 and above. I don't know what that means in practice. The changelog doesn't mention that it removes support for older Linux kernel versions. I'm fine with updating `systemd` to 247 unless we know that it breaks something, or say doesn't build with the version of `linux-headers` that we use.

**Comment by danielnachun** [comment]
I understood that be a fix to deal with an issue that was introduced in kernel 4.14.  It seemed they were waiting for the kernel devs to make a change to address the issue, but they kernel devs did not so they implemented that fix in systemd 247.  I can't find anything about specific `glibc` or `kernel` requirements for `systemd` so I'm inclined to guess that it should work.

**Pull request closed without merging**
