### PR TITLE
gcc@5: align with upstream and improve

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Ping @sjackman @dawidd6 @issyl0 @jonchang for a review.

I finally got this working:
- gcc becomes gcc 9
- the gcc@9 formula has been deleted
- a gcc@9 alias has been added and points to gcc
- gcc@5 has been fixed

This aligns our gcc setup as much as possible with homebrew-core and will greatly simplify the merging of both repositories.

The only thing that was not done in this PR was to check if all the 74 formulae with `depends_on "gcc"` still work (I hope the bottles are fine, I checked a few and the tests were working fine, so I hope we do not need to revision bump everything).

**Comment by sjackman** [comment]
https://github.com/Homebrew/brew/blob/bc882c6c286e66a3db2c638e7908172284f2bc55/Library/Homebrew/compilers.rb#L109

One big effect of this PR is that it changes the default brewed version of GCC on Homebrew from GCC 5 to GCC 9. That may be okay, but definitely needs some testing, since all of our bottles are built with GCC 5.

For example A depends on B depends on C. A and C are `cellar :any` and installed from bottle (which were compiled using GCC 5), and B is not `cellar :any` and installed from source, compiled using the default gcc which is GCC 9. Does this situation work? In particular when A, B, and C are all C++ packages?

A safe approach (and perhaps preferable) would be to make `gcc` an alias to `gcc@5` to keep the current status quo that GCC 5 is the default compiler. Note that making `gcc` an alias may break other assumptions in Homebrew. In a later PR (if it’s desirable, maybe not) change the `gcc` alias from `gcc@5` to `gcc@9`.

The important test system is an Ubuntu 14.04 Docker image (that is a system with glibc < 2.23, so that brewed glibc and gcc are used) with Homebrew installed in a non-default prefix like `/home/foo/.linuxbrew`.

**Comment by robertwt7** [comment]
+1 waiting for this! Thanks

**Comment by iMichka** [comment]
Just for the timeline here: I am currently working on porting the xorg formulae to homebrew-core, which will eat up a lot of time for me. Once this is done I will come back to this. I'll be on vacation too, so do not expect any progress on the gcc side before september 2020.

**Comment by iMichka** [comment]
Superseded by #21380

**Pull request closed without merging**
