### PR TITLE
qt: debug build

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Needs a rebuild once this is fixed:
`qbs`

**Comment by iMichka** [comment]
> 2020-04-29T06:50:21.0732841Z [34m==>[0m [1mdf -h[0m
2020-04-29T06:50:21.0732932Z Filesystem      Size  Used Avail Use% Mounted on
2020-04-29T06:50:21.0733007Z overlay          84G   79G  4.5G  95% /
2020-04-29T06:50:21.0733095Z tmpfs            64M     0   64M   0% /dev
2020-04-29T06:50:21.0733186Z tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
2020-04-29T06:50:21.0733277Z shm              64M     0   64M   0% /dev/shm
2020-04-29T06:50:21.0733351Z /dev/sda1        84G   79G  4.5G  95% /__t
2020-04-29T06:50:21.0733440Z tmpfs           695M  1.1M  694M   1% /run/docker.sock
2020-04-29T06:50:21.0733532Z tmpfs           3.4G     0  3.4G   0% /proc/acpi
2020-04-29T06:50:21.0733621Z tmpfs           3.4G     0  3.4G   0% /proc/scsi
2020-04-29T06:50:21.0733714Z tmpfs           3.4G     0  3.4G   0% /sys/firmware

**Comment by iMichka** [comment]
Probably due to https://github.com/actions/virtual-environments/issues/709

**Comment by iMichka** [comment]
Here is df -h just before running the first brew install steps.
```
2020-05-16T07:27:21.6521371Z overlay          84G   68G   17G  81% /
2020-05-16T07:27:21.6521455Z tmpfs            64M     0   64M   0% /dev
2020-05-16T07:27:21.6521569Z tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
2020-05-16T07:27:21.6521671Z shm              64M     0   64M   0% /dev/shm
2020-05-16T07:27:21.6521769Z /dev/sdb1        84G   68G   17G  81% /__t
2020-05-16T07:27:21.6521851Z tmpfs           693M  1.1M  692M   1% /run/docker.sock
2020-05-16T07:27:21.6521953Z tmpfs           3.4G     0  3.4G   0% /proc/acpi
2020-05-16T07:27:21.6522055Z tmpfs           3.4G     0  3.4G   0% /proc/scsi
2020-05-16T07:27:21.6522160Z tmpfs           3.4G     0  3.4G   0% /sys/firmware
```

Here is it after the installation of all the dependencies and the prune step:
```
2020-05-16T09:16:14.4855160Z [34m==>[0m [1mdf -h[0m
2020-05-16T09:16:14.4855262Z Filesystem      Size  Used Avail Use% Mounted on
2020-05-16T09:16:14.4855362Z overlay          84G   74G  9.8G  89% /
2020-05-16T09:16:14.4855462Z tmpfs            64M     0   64M   0% /dev
2020-05-16T09:16:14.4855563Z tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
2020-05-16T09:16:14.4855746Z shm              64M     0   64M   0% /dev/shm
2020-05-16T09:16:14.4855854Z /dev/sdb1        84G   74G  9.8G  89% /__t
2020-05-16T09:16:14.4855954Z tmpfs           693M  1.1M  692M   1% /run/docker.sock
2020-05-16T09:16:14.4856057Z tmpfs           3.4G     0  3.4G   0% /proc/acpi
2020-05-16T09:16:14.4856139Z tmpfs           3.4G     0  3.4G   0% /proc/scsi
2020-05-16T09:16:14.4856239Z tmpfs           3.4G     0  3.4G   0% /sys/firmware
```

**Comment by iMichka** [comment]
Looks like this built with the latest version. Not sure why but it looks like we did not hit the disk space limit now.

The qt test is failing though:
```
2020-06-15T23:36:16.6282931Z Testing qt
2020-06-15T23:36:16.6284164Z [34m==>[0m [1m/home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/bin/qmake /tmp/qt-test-20200615-108767-1jig475/hello.pro[0m
2020-06-15T23:36:16.6284588Z Info: creating stash file /tmp/qt-test-20200615-108767-1jig475/.qmake.stash
2020-06-15T23:36:16.6284877Z [34m==>[0m [1mmake[0m
2020-06-15T23:36:16.6285467Z g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/include -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/include/QtCore -I. -I/home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/mkspecs/linux-g++ -o main.o main.cpp
2020-06-15T23:36:16.6285955Z g++ -Wl,-O1 -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/lib -o hello main.o   /home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/lib/libQt5Core.so -lpthread   
2020-06-15T23:36:16.6286255Z [34m==>[0m [1m./hello[0m
2020-06-15T23:36:16.6286750Z ./hello: relocation error: /home/linuxbrew/.linuxbrew/Cellar/qt/5.15.0/lib/libQt5Core.so.5: symbol __cxa��'�, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
2020-06-15T23:36:16.6287069Z [31mError:[0m qt: failed
2020-06-15T23:36:16.6287211Z An exception occurred within a child process:
2020-06-15T23:36:16.6287352Z   BuildError: Failed executing: ./hello
```

**Comment by Char-Aznable** [comment]
I got error similar to https://github.com/Homebrew/linuxbrew-core/issues/20487 and can only get around with removing the "-no-avx*" options from config and the related patch and my machine does have avx2 support. It looks like the current build config is not generally applicable. Without looking into the qt docs, shouldn't we leave the architecture-specific things for the build config to decide?

**Comment by iMichka** [comment]
Merging with the current fixes. This will publish a bottle so that people can install QT.
I will work on fixing the test locally, because I can't see what is going on from the logs.

**Comment by lrineau** [comment]
Thanks @iMichka for that merge.

As you probably know, there is something fishy:
  - if I install the `qt` bottle with `brew install qt`, then `brew test qt` fails (a segfault in `/home/linuxbrew/.linuxbrew/lib/ld.so`), but
  - if I install `qt` from sources (with `brew install -s qt`) then `brew test qt` works fine.

**Comment by iMichka** [comment]
I tested this too last week and it also segfaulted for me.

My gdb was not working so I could not debug this right away. I think it would be great if someone could try to run the executable created by the test with gdb and debug the segafault.

**Comment by Char-Aznable** [comment]
I have got various errors when linking against the bottled qt library. Some complains about  undefined reference to functions and some about glibc version mismatch. This bottle is probably not useful.

**Comment by iMichka** [comment]
Yeah, right now I can't do much more. I have been working on the qt formulae for the last 2-3 years and it has been always more or less broken. These issues are too hard for me to fix, and I do not have much more time to invest in this.

I am giving up on this, anyone can pick it up and try to fix it.

**Pull request merged**
