### PR TITLE
Remove JDK formulae (jdk, jdk@8 and jdk@7)

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] ~Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [x] ~Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?~
- [x] ~Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?~
- [x] ~Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.~

-----

- The main `jdk` (9.0.4) formula is no longer installable on Linux (#14124). The download link 404s, and we can't get the "real" one from Oracle because we can't sign the agreements.
- All the `jdk` formulae (all versions) have already been removed from Homebrew/homebrew-core in favour of `adoptopenjdk`.

Formulae we will likely be breaking by doing this:

- [Hbase](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/hbase.rb#L47)
- Maybe some more that don't use `openjdk` or `adoptopenjdk` yet?

As discussed with @sjackman in Slack. :crossed_fingers:

### CODE REVIEW

**Comment by sjackman** [comment]
Please add to this PR (or in a separate PR):
```diff
-      ENV["CPPFLAGS"] = "-I#{OS.mac? ? "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers" : Formula["jdk"].opt_include}"
+      ENV["CPPFLAGS"] = "-I#{OS.mac? ? "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers" : Formula["adoptopenjdk"].opt_include}"
```

**Comment by issyl0** [comment]
>  [exec] configure: error: Native java headers not found. Is $JAVA_HOME set correctly?

Should have done the `hbase` change in a separate PR. :joy:

**Comment by sjackman** [comment]
> Should have done the hbase change in a separate PR. 😂

Hah. Sounds good.

**Comment by issyl0** [comment]
I can't even install `hbase` locally, so I'll work on these changes in a separate PR (or raise an issue and someone else can if it's important to them): `UnsatisfiedRequirements: Unsatisfied requirements failed this build.`

**Comment by sjackman** [comment]
This PR is also needed to install `adoptopenjdk` rather than `openjdk`. https://github.com/Homebrew/brew/pull/6286

**Pull request merged**
