### PR TITLE
mongodb: Fix build for Linux

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

This is a draft PR because it's not ready yet but I wanted to have visibility. I'll squash and rebase and do all the checks at the end.

This attempts to fix issue 12582.

Current error status: https://gist.github.com/issyl0/f0f8ff300d5ecdfb45dffa7c5840c100

### CODE REVIEW

**Comment by issyl0** [comment]
This is blocked on CI on `scons` failing to build. I get an entirely different error locally.

**Comment by iMichka** [comment]
I fixed `scons` with #13660, this PR can be rebased.

**Comment by issyl0** [comment]
> ==> scons install --prefix=/home/linuxbrew/.linuxbrew/Cellar/mongodb/4.0.3_1 -j8 CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5 --build-mongoreplay=true --disable-warnings-as-errors --use-new-tools --ssl CCFLAGS=-I/home/linuxbrew/.linuxbrew/opt/openssl/include LINKFLAGS=-L/home/linuxbrew/.linuxbrew/opt/openssl/lib
[...]
Checking for curl_global_init(0) in C library curl... no
Could not find <curl/curl.h> and curl lib

**Comment by iMichka** [comment]
You'll need to depend on `curl`.

**Comment by iMichka** [comment]
Looks like this did not work. The next step is to look at the mongodb source code to try to find out how to pass the curl paths to the build system ...

**Comment by issyl0** [comment]
Looks like [this code](https://github.com/mongodb/mongo/blob/r4.0.3/SConstruct#L3083-L3090) is the source of the error message, and that it's just looking for `curl` and its headers. The [build instructions for this version](https://github.com/mongodb/mongo/blob/r4.0.3/docs/building.md) do say that `libcurl-dev` is needed - I wonder what's different in our `curl`. :woman_shrugging: :thinking:

**Comment by issyl0** [comment]
I haven't been able to make any progress on this, short of being able to reproduce the Circle error message on another laptop where I _don't_ have `libcurl-dev` installed via `apt`. Seems like SConstruct documents that you might need to set `$PATH`.

> This also means that if the compiler or other commands that you want to use to build your target files are not in standard system locations, scons will not find them unless you explicitly set the PATH to include those locations. Whenever you create an scons construction environment, you can propagate the value of PATH from your external environment.

I've hacked away at the `scons install` section of the formula to no avail so far, setting more vars following the example of the brewed `openssl` dependency which seems to work fine to set the paths to it, but not in `curl`'s case. :confused:

**Comment by issyl0** [comment]
I don't have time to work on this right now. Closing. If someone else wants to pick it up, please do! :disappointed:

**Pull request closed without merging**
