### PR TITLE
mesa: add missing dependency valgrind

### PR DESCRIPTION
**Pull request by danielnachun**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
Can we disable valgrind instead? I guess it's only needed for debugging.

If it's a linux-only dependency, it needs to be added to the on_linux block.

And as we are merging linuxbrew-core into homebrew-core, ideally this needs to be baclported to https://github.com/Homebrew/homebrew-core

**Comment by danielnachun** [comment]
I will see how to disable it, it should be simple enough and should be Linux only.  And I will back port to homebrew-core.

**Comment by danielnachun** [comment]
I was able to disable valgrind.  I'll make a PR for this in homebrew-core once this is approved here.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
- Don't worry about the build failure, it's because we did not rebuild bottles. That's fine in this case.
- No need to backport this one right now.

When you see `unless OS.mac?` blocks, this means the whole thing needs to be backported to homebrew-core. When it is in a `on_linux do` block it means it has already been backported. So when there is a big block like this, the whole file needs to be migrated.

**Pull request merged**
