### PR TITLE
icecream: Build a bottle for Linux

### PR DESCRIPTION
**Pull request by dawidd6**
This is an automated pull request to build a new bottle for linuxbrew-core
based on the existing bottle block from homebrew-core.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2019-11-27T13:05:02.7864589Z checking cap-ng.h usability... no
2019-11-27T13:05:02.7864914Z checking cap-ng.h presence... no
2019-11-27T13:05:02.7865257Z checking for cap-ng.h... no
2019-11-27T13:05:02.7865592Z checking for capng_clear in -lcap-ng... no
2019-11-27T13:05:02.7865942Z configure: error: libcap-ng library was not found
```

**Comment by dawidd6** [comment]
Guess we need a new formula: https://github.com/stevegrubb/libcap-ng.

**Comment by iMichka** [comment]
It has only 10 stars ... weird. Maybe we can disable that feature.

**Comment by dawidd6** [comment]
Well, I just created the formula :D. Also it seems like at least Debian and Arch have this library packaged, so it might be useful in the future for something else too.

**Comment by dawidd6** [comment]
```
make[1]: Entering directory '/tmp/icecream-20191128-16340-ek2wdw/icecream-1.3/doc'
/home/linuxbrew/.linuxbrew/opt/docbook2x/bin/docbook2man man-icecc.1.xml
/home/linuxbrew/.linuxbrew/opt/docbook2x/bin/docbook2man man-icerun.1.xml
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
man-icecc.1.xml:6: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
man-icerun.1.xml:6: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
]>
  ^
Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/docbook2x/0.8.8_1/bin/db2x_manxml line 2413.
Makefile:592: recipe for target 'icecc.1' failed
make[1]: *** [icecc.1] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:595: recipe for target 'icerun.1' failed
make[1]: *** [icerun.1] Error 2
make[1]: Leaving directory '/tmp/icecream-20191128-16340-ek2wdw/icecream-1.3/doc'
Makefile:422: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

Looks like `dockbook2x` is broken.

**Pull request closed without merging**
