### PR TITLE
ponyc: fixes

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> brew audit --skip-style ponyc --online
==> FAILED
Error: 1 problem in 1 formula detected
ponyc:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/ponyc
      lib/native/libponyc.a
```

**Comment by dawidd6** [comment]
```
➜  ponyc/0.35.1  strings bin/ponyc | grep brew
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-5
➜  ponyc/0.35.1  strings lib/native/libponyc.a | grep brew
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-5
```

**Comment by dawidd6** [comment]
@Bo98 gonna need your help with this one.

**Comment by Bo98** [comment]
Try `inreplace` [this](https://github.com/ponylang/ponyc/blob/d401b3b83123bc6aea9192f4a5cb09f98123131b/CMakeLists.txt#L120) so that `PONY_COMPILER` is not set to `CMAKE_C_COMPILER` but instead to where a usable compiler is at runtime (`/usr/bin/gcc` or whatever).

**Comment by dawidd6** [comment]
Thanks again!

**Pull request merged**
