### PR TITLE
deno: hack to get it built on linux

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

Modifications taken from: https://github.com/chrmoritz/homebrew-deno/blob/master/Formula/deno.rb

Thanks @chrmoritz!

### CODE REVIEW

**Comment by chrmoritz** [comment]
Looks like the failing `ldflags` were introduced in https://github.com/denoland/chromium_build/commit/a6687877adc9064b6f4b2845d382e02575be1430 during a suspicious looking clang update. Maybe that's some stuff only available in `llvm` head?

**Comment by chrmoritz** [comment]
Not necessarily as these flags were added only on Linux, Android and Fuchsia and not on mac OS, see: https://github.com/denoland/chromium_build/blob/a6687877adc9064b6f4b2845d382e02575be1430/config/compiler/BUILD.gn#L371-L407

**Comment by jonchang** [comment]
> Good things is, that this is already fixed in V8 8.8 in https://chromium.googlesource.com/chromium/src.git/+/74b0cb5b86f7d7f8f7c1172d85b09096bef147b7%5E%21/#F0 So we will need to just wait until deno upgrades V8 from 8.7 to 8.8 in a couple of weeks.

Ok, I'm in favor of this plan. Feel free to ping here once this happens :+1:

**Comment by iMichka** [comment]
Let's close this, it has been open forever. Anyone can submit a PR later to fix this.

**Comment by waldyrious** [comment]
> Good things is, that this is already fixed in V8 8.8 in https://chromium.googlesource.com/chromium/src/build/+/cd7202be2fa4b06d165cf30f787f8cda517e6d0c%5E%21/#F0 So we will need to just wait until deno upgrades V8 from 8.7 to 8.8 in a couple of weeks.

rusty_v8 has [upgraded](https://github.com/denoland/rusty_v8/commit/b9f48ebd265be1517a5974e1952b0da6fac2874f) to V8 8.8 in [v0.13.0](https://github.com/denoland/rusty_v8/releases/tag/v0.13.0) ([PR #533](https://github.com/denoland/rusty_v8/pull/533)), and Deno has upgraded to that version of rusty_v8 in [v1.5.4](https://github.com/denoland/deno/releases/tag/v1.5.4) ([PR #8446](https://github.com/denoland/deno/pull/8446)), released 23 Nov 2020.

**Pull request closed without merging**
