### PR TITLE
abseil, grpc: Build with GCC 5

### PR DESCRIPTION
**Pull request by sjackman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/linuxbrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/linuxbrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [x] Have you included the output of `brew gist-logs <formula>` of the build failure if your PR fixes a build failure. Please quote the exact error message.

-----

- abseil: Build with GCC 5
- grpc: Build with GCC 5

### CODE REVIEW

**Comment by iMichka** [comment]
Both need c++17, and we had issues with other libraries that linked against this. I need to test if this is still the case.

**Comment by iMichka** [comment]
> Warning: grpc dependency protobuf was built with a different C++ standard
library (libstdc++ from gcc-6). This may cause problems at runtime.

This is because protobuf is built with gcc-6.

**Comment by sjackman** [comment]
> Both need c++17, and we had issues with other libraries that linked against this. I need to test if this is still the case.

`brew install -s abseil grpc bear` and `brew test abseil grpc bear` passes after my two PRS.

**Comment by iMichka** [comment]
Can we redo a full build with protobuf using gcc 5 too? Because it's using gcc-6 libstdc++ I think.

I am really confused as why everything was broken before and now stuff start working magically.

**Comment by sjackman** [comment]
> Can we redo a full build with protobuf using gcc 5 too? Because it's using gcc-6 libstdc++ I think.

I'll test `protobuf`.

> I am really confused as why everything was broken before and now stuff start working magically.

Could be fixes to Homebrew/brew or fixes upstream or both.

**Comment by sjackman** [comment]
>> Can we redo a full build with protobuf using gcc 5 too? Because it's using gcc-6 libstdc++ I think.

> I'll test protobuf.

I've opened PR https://github.com/Homebrew/linuxbrew-core/pull/22498 `protobuf: Build with GCC 5`.

**Comment by dawidd6** [comment]
Ye, really surprising to see all those formulae now magically building with our old trusty gcc5. But if they do build then let's :shipit:.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
